// Diktant uchun gaplar: har darajada 15 ta original gap (hech qayerdan ko'chirilmagan).
// Uzunligi darajaga mos: A2 — 6–10 so'z, B1 — 9–14, B2 — 12–18, C1 — 15–22.
import type { Level } from './types';

export const DICTATION: Record<Level, string[]> = {
  A2: [
    'My sister works in a small bakery near our house.',
    'We usually have dinner at seven o’clock.',
    'Can you open the window, please? It is very hot.',
    'He forgot his umbrella, so he got wet.',
    'There are two big parks in the city centre.',
    'I would like a cup of green tea.',
    'The bus to the airport leaves every twenty minutes.',
    'She is reading a book about famous travellers.',
    'Last summer we visited our grandparents in the village.',
    'My brother wants to become a doctor.',
    'Please write your name at the top of the page.',
    'The shop closes early on Sundays.',
    'I often listen to music on my way to school.',
    'They bought a new sofa for the living room.',
    'How much does this jacket cost?',
  ],
  B1: [
    'I have been learning English for about three years now.',
    'If it rains tomorrow, we will stay at home and watch a film.',
    'The museum was so crowded that we could hardly see the paintings.',
    'She asked me whether I had finished my homework.',
    'Most people in my city travel to work by metro.',
    'We should have booked the tickets a few weeks earlier.',
    'He has lived in Tashkent since he was a child.',
    'Could you tell me where the nearest pharmacy is?',
    'Although the exam was difficult, most students passed it.',
    'The new library is open until ten o’clock every evening.',
    'I am used to getting up early because of my job.',
    'My friends and I are planning a trip to the mountains.',
    'The teacher explained the rule again for those who were absent.',
    'You don’t need to bring any food because lunch is provided.',
    'It took us almost two hours to find a parking space.',
  ],
  B2: [
    'Despite the heavy traffic, we managed to arrive just before the meeting started.',
    'The report suggests that young people are spending less time outdoors than before.',
    'Had I known about the delay, I would have taken an earlier train.',
    'Many companies now allow their employees to work from home twice a week.',
    'The government has promised to invest more money in public transport.',
    'She is considered one of the most talented architects of her generation.',
    'It is widely believed that regular exercise improves concentration and mood.',
    'The festival attracts thousands of visitors from all over the region every autumn.',
    'Nobody expected the small startup to become so successful in such a short time.',
    'Students are encouraged to take part in at least one volunteer project.',
    'The price of fresh vegetables tends to rise sharply during the winter months.',
    'Unless we reduce plastic waste, the problem will only get worse.',
    'The results of the survey were published in a respected scientific journal.',
    'He apologised for the misunderstanding and offered to pay for the damage.',
    'Learning a language requires patience, practice and a certain amount of curiosity.',
  ],
  C1: [
    'Had the committee acted on the early warnings, the crisis might well have been avoided altogether.',
    'The novel explores the tension between personal ambition and loyalty to one’s family.',
    'Critics argue that the new policy places an unfair burden on small businesses.',
    'Not only did the experiment fail, but it also raised serious questions about the methodology.',
    'The rapid growth of online education has transformed the way universities approach teaching.',
    'It remains to be seen whether the agreement will lead to any lasting change.',
    'Researchers have yet to find a convincing explanation for this unusual pattern of behaviour.',
    'The architect’s new design manages to be both strikingly modern and surprisingly practical for families.',
    'Rarely has a single invention had such a profound impact on everyday communication.',
    'The documentary sheds light on the often overlooked contribution of rural women to the economy.',
    'Economic uncertainty has prompted many households across the country to reconsider their long-term spending habits.',
    'While the proposal certainly has its merits, its implementation would be extremely costly for local councils.',
    'The speaker drew attention to the growing gap between scientific evidence and public opinion.',
    'Were the city to expand its cycling network, congestion could be reduced considerably.',
    'Her argument, though persuasive at first glance, rests on a number of questionable assumptions.',
  ],
};
