import type { Level, TopicWord, VocabTopic } from './types';

// Qoʻshimcha mavzuli lugʻat: har mavzuda 16 ta soʻz (A2–C1), oʻzbekcha va ruscha tarjima, taʼrif va misol.
const w = (
  word: string,
  pos: string,
  uz: string,
  ru: string,
  definition: string,
  example: string,
  level: Level,
): TopicWord => ({ word, pos, uz, ru, definition, example, level });

export const VOCAB_TOPICS_MORE: VocabTopic[] = [
  {
    id: 'nature-animals',
    emoji: '🦁',
    title: { uz: "Tabiat va hayvonlar", ru: "Природа и животные", en: "Nature and animals" },
    words: [
      w("pet", "noun", "uy hayvoni", "домашнее животное (питомец)", "an animal that you keep at home and look after", "Our pet cat sleeps on the sofa all day.", 'A2'),
      w("wild", "adjective", "yovvoyi", "дикий", "living in nature, not kept by people", "Wild goats live high up in the mountains.", 'A2'),
      w("feather", "noun", "pat, par", "перо", "one of the soft, light things that cover a bird's body", "The peacock has beautiful blue and green feathers.", 'A2'),
      w("nest", "noun", "uya (qush uyasi)", "гнездо", "a place that a bird builds to lay its eggs in", "A pair of storks built a nest on the roof of our school.", 'A2'),
      w("habitat", "noun", "yashash muhiti, makon", "среда обитания", "the natural place where an animal or plant lives", "The desert is the natural habitat of the camel.", 'B1'),
      w("species", "noun", "tur (biologik)", "вид (биологический)", "a group of animals or plants of the same kind", "Scientists find new species of insects every year.", 'B1'),
      w("hunt", "verb", "ov qilmoq, ovlamoq", "охотиться", "to chase and catch animals in order to eat or kill them", "Owls hunt for mice at night.", 'B1'),
      w("herd", "noun", "poda, gala", "стадо", "a large group of animals of one kind that live or move together", "A herd of sheep blocked the mountain road.", 'B1'),
      w("predator", "noun", "yirtqich", "хищник", "an animal that kills and eats other animals", "The snow leopard is the top predator in these mountains.", 'B2'),
      w("camouflage", "noun", "tabiiy niqob, kamuflyaj", "маскировка, защитная окраска", "colours or patterns that help an animal hide in its surroundings", "The lizard's camouflage makes it almost invisible on the sand.", 'B2'),
      w("hibernate", "verb", "qishki uyquga ketmoq", "впадать в зимнюю спячку", "(of an animal) to sleep through the winter", "Bears hibernate in caves until the spring.", 'B2'),
      w("migrate", "verb", "(mavsumiy) koʻchmoq, uchib ketmoq", "мигрировать, совершать перелёты", "(of birds or animals) to travel to another region at the same time every year", "Many birds migrate south before the winter begins.", 'B2'),
      w("extinct", "adjective", "qirilib ketgan, yoʻq boʻlib ketgan", "вымерший", "(of a type of animal or plant) no longer existing anywhere", "The Turan tiger became extinct in the twentieth century.", 'B2'),
      w("poaching", "noun", "brakonerlik (noqonuniy ov)", "браконьерство", "the illegal hunting or catching of animals", "Poaching is a serious threat to elephants and rhinos.", 'C1'),
      w("nocturnal", "adjective", "tunda faol boʻladigan", "ночной (активный ночью)", "(of an animal) active at night and sleeping during the day", "Bats and hedgehogs are nocturnal animals.", 'C1'),
      w("domesticate", "verb", "xonakilashtirmoq, qoʻlga oʻrgatmoq", "одомашнивать, приручать", "to train a wild animal to live with people or work for them", "People domesticated horses thousands of years ago.", 'C1'),
    ],
  },
  {
    id: 'weather-seasons',
    emoji: '🌦️',
    title: { uz: "Ob-havo va fasllar", ru: "Погода и времена года", en: "Weather and seasons" },
    words: [
      w("foggy", "adjective", "tumanli", "туманный", "with thick, low cloud in the air that makes it hard to see", "It was so foggy that we couldn't see the road.", 'A2'),
      w("freezing", "adjective", "qahraton, juda sovuq", "ледяной, очень холодный", "extremely cold", "It's freezing outside, so wear a warm hat.", 'A2'),
      w("thunderstorm", "noun", "momaqaldiroqli jala", "гроза", "a storm with thunder, lightning and heavy rain", "The thunderstorm woke me up in the middle of the night.", 'A2'),
      w("degree", "noun", "daraja (harorat)", "градус", "a unit for measuring temperature", "It was forty degrees in Tashkent yesterday.", 'A2'),
      w("forecast", "noun", "ob-havo maʼlumoti, prognoz", "прогноз погоды", "a report that says what the weather will probably be like", "The forecast says it will rain tomorrow.", 'B1'),
      w("humid", "adjective", "nam, dim", "влажный", "(of air or weather) hot and wet in an uncomfortable way", "Summers in Tashkent are hot but not very humid.", 'B1'),
      w("heatwave", "noun", "jazirama kunlar, issiq toʻlqini", "аномальная жара", "a period of unusually hot weather", "During the heatwave, people stayed indoors in the afternoon.", 'B1'),
      w("pour", "verb", "chelaklab quymoq (yomgʻir)", "лить как из ведра", "to rain very heavily", "It poured all day, so we cancelled the picnic.", 'B1'),
      w("frost", "noun", "qirov; ayoz", "иней; мороз", "a thin white layer of ice that forms on surfaces when it is very cold", "There was frost on the car windows this morning.", 'B1'),
      w("drizzle", "noun", "shivalama yomgʻir, mayda yomgʻir", "морось, мелкий дождь", "light rain with very small drops", "The drizzle didn't stop us from going for a walk.", 'B2'),
      w("mild", "adjective", "moʻtadil, yumshoq (ob-havo)", "мягкий, тёплый (о погоде)", "not very cold or very hot", "We had a mild winter with very little snow.", 'B2'),
      w("changeable", "adjective", "oʻzgaruvchan, beqaror", "переменчивый, неустойчивый", "likely to change often", "The weather in early spring is very changeable.", 'B2'),
      w("hail", "noun", "doʻl", "град", "small balls of ice that fall from the sky like rain", "The hail damaged the apricot trees in our garden.", 'B2'),
      w("overcast", "adjective", "bulut qoplagan, xira (osmon)", "пасмурный", "(of the sky) completely covered with grey clouds", "The sky was overcast all morning, but it didn't rain.", 'C1'),
      w("sweltering", "adjective", "jazirama, dim va juda issiq", "знойный, изнуряюще жаркий", "so hot that you feel uncomfortable", "We waited for the bus on a sweltering afternoon in July.", 'C1'),
      w("unseasonably", "adverb", "mavsumga xos boʻlmagan holda", "не по сезону", "in a way that is unusual for the time of year", "It was unseasonably warm for January.", 'C1'),
    ],
  },
  {
    id: 'feelings-personality',
    emoji: '😊',
    title: { uz: "Hislar va xarakter", ru: "Чувства и характер", en: "Feelings and personality" },
    words: [
      w("shy", "adjective", "uyatchan, tortinchoq", "застенчивый, стеснительный", "nervous about talking to people you do not know", "He was too shy to speak in front of the class.", 'A2'),
      w("proud", "adjective", "faxrlanayotgan, gʻururli", "гордый", "pleased about something that you or someone close to you has done", "My parents were proud of me when I passed the exam.", 'A2'),
      w("lonely", "adjective", "yolgʻiz, yolgʻizlikdan siqilgan", "одинокий", "unhappy because you are alone or have no friends", "She felt lonely during her first month in the new city.", 'A2'),
      w("upset", "adjective", "xafa, koʻngli choʻkkan", "расстроенный", "unhappy or worried because something bad has happened", "He was upset because he had lost his phone.", 'A2'),
      w("confident", "adjective", "oʻziga ishongan", "уверенный в себе", "sure that you can do things well", "She sounds much more confident when she speaks English now.", 'B1'),
      w("generous", "adjective", "saxiy, qoʻli ochiq", "щедрый", "happy to give money, help or time to others", "My uncle is very generous with his time and money.", 'B1'),
      w("anxious", "adjective", "xavotirli, tashvishli", "тревожный, обеспокоенный", "worried and nervous about something", "I always feel anxious before an exam.", 'B1'),
      w("reliable", "adjective", "ishonchli", "надёжный", "someone you can trust to do what they promise", "Ask Aziz to help — he is very reliable.", 'B1'),
      w("stubborn", "adjective", "oʻjar, qaysar", "упрямый", "not willing to change your ideas or behaviour", "My little brother is too stubborn to say sorry.", 'B1'),
      w("frustrated", "adjective", "asabi buzilgan, jahli chiqqan", "раздражённый, досадующий", "annoyed because you cannot do or change something", "I get frustrated when the internet is slow.", 'B2'),
      w("sensitive", "adjective", "taʼsirchan, nozik tabiatli", "чувствительный, ранимый", "easily upset by what other people say or do", "Be careful what you say — he's very sensitive.", 'B2'),
      w("outgoing", "adjective", "kirishimli, ochiqkoʻngil", "общительный", "friendly and happy to meet new people", "My sister is outgoing and makes friends easily.", 'B2'),
      w("overwhelmed", "adjective", "(ish yoki hislar) bosib ketgan, eplay olmay qolgan", "подавленный, перегруженный", "feeling that something is too much for you to deal with", "I felt overwhelmed by all the work before the holidays.", 'B2'),
      w("resilient", "adjective", "bardoshli, qiyinchilikdan tez oʻziga keladigan", "стойкий, жизнестойкий", "able to recover quickly after something difficult", "Children are often more resilient than adults think.", 'C1'),
      w("conscientious", "adjective", "vijdonan ishlaydigan, masʼuliyatli", "добросовестный", "careful to do your work well and completely", "She is a conscientious student who never misses a deadline.", 'C1'),
      w("ambivalent", "adjective", "ikkilanib turgan, qarama-qarshi hislardagi", "испытывающий противоречивые чувства", "having mixed feelings about something", "I feel ambivalent about moving abroad for work.", 'C1'),
    ],
  },
  {
    id: 'science-research',
    emoji: '🔬',
    title: { uz: "Fan va tadqiqot", ru: "Наука и исследования", en: "Science and research" },
    words: [
      w("scientist", "noun", "olim", "учёный", "a person who studies or works in science", "My cousin wants to become a scientist.", 'A2'),
      w("experiment", "noun", "tajriba", "эксперимент, опыт", "a test that you do to find out or prove something", "We did an experiment with water and salt in class.", 'A2'),
      w("laboratory", "noun", "laboratoriya", "лаборатория", "a room or building used for scientific work", "The students wear white coats in the laboratory.", 'A2'),
      w("discover", "verb", "kashf qilmoq, aniqlamoq", "открывать, обнаруживать", "to find something for the first time", "Alexander Fleming discovered penicillin in 1928.", 'A2'),
      w("research", "noun", "tadqiqot", "исследование", "careful study to find new facts or information", "Her research is about saving water in farming.", 'B1'),
      w("theory", "noun", "nazariya", "теория", "an idea or set of ideas that explains why something happens", "Einstein's theory of relativity is not easy to understand.", 'B1'),
      w("evidence", "noun", "dalil, isbot", "доказательства, данные", "facts that show that something is true", "There is strong evidence that exercise improves memory.", 'B1'),
      w("measure", "verb", "oʻlchamoq", "измерять", "to find the size, amount or temperature of something", "We measured the temperature of the water every hour.", 'B1'),
      w("invention", "noun", "ixtiro", "изобретение", "something new that someone has made or designed", "The printing press was one of the most important inventions in history.", 'B1'),
      w("hypothesis", "noun", "gipoteza, faraz", "гипотеза", "an idea that has not been proved yet and needs to be tested", "The results showed that our hypothesis was wrong.", 'B2'),
      w("findings", "noun", "(tadqiqot) natijalari, xulosalar", "результаты (исследования)", "the information that people discover in a study", "The findings were published in a medical journal.", 'B2'),
      w("conduct", "verb", "oʻtkazmoq (tadqiqot, soʻrovnoma)", "проводить (исследование, опрос)", "to organise and carry out an activity", "The team conducted a survey of five hundred students.", 'B2'),
      w("sample", "noun", "namuna", "образец, проба", "a small amount of something that is tested to learn about the whole", "The researchers tested water samples from ten rivers.", 'B2'),
      w("peer review", "noun", "mutaxassislar taqrizi", "рецензирование (экспертами)", "the checking of a study by other experts before it is published", "Every article in the journal goes through peer review.", 'C1'),
      w("empirical", "adjective", "empirik, tajribaga asoslangan", "эмпирический", "based on observation and experiments, not only on ideas", "There is little empirical support for this popular belief.", 'C1'),
      w("replicate", "verb", "(tajribani) takrorlab bir xil natija olmoq", "воспроизводить (опыт, результат)", "to repeat an experiment and get the same result", "Other scientists were unable to replicate the results.", 'C1'),
    ],
  },
  {
    id: 'business-economy',
    emoji: '📈',
    title: { uz: "Biznes va iqtisodiyot", ru: "Бизнес и экономика", en: "Business and the economy" },
    words: [
      w("company", "noun", "kompaniya, firma", "компания, фирма", "an organisation that makes or sells goods or services", "She works for a small IT company.", 'A2'),
      w("customer", "noun", "xaridor, mijoz", "клиент, покупатель", "a person who buys something from a shop or business", "The shop gives every customer a free bag.", 'A2'),
      w("price", "noun", "narx", "цена", "the amount of money you must pay for something", "The price of bread went up last month.", 'A2'),
      w("sell", "verb", "sotmoq", "продавать", "to give something to someone for money", "My uncle sells fruit at Chorsu Bazaar.", 'A2'),
      w("profit", "noun", "foyda", "прибыль", "the money a business makes after it pays all its costs", "The café made a small profit in its first year.", 'B1'),
      w("advertise", "verb", "reklama qilmoq", "рекламировать", "to tell people about a product or service so that they buy it", "They advertise their products on social media.", 'B1'),
      w("export", "verb", "eksport qilmoq, chetga sotmoq", "экспортировать", "to sell goods to another country", "Uzbekistan exports fruit and vegetables to many countries.", 'B1'),
      w("staff", "noun", "xodimlar", "персонал, сотрудники", "all the people who work for an organisation", "The hotel has fifty staff.", 'B1'),
      w("competitor", "noun", "raqobatchi", "конкурент", "a company that sells the same kind of products as another", "Our main competitor has lowered its prices.", 'B1'),
      w("invest", "verb", "sarmoya kiritmoq", "инвестировать, вкладывать", "to put money into a business to make more money later", "The company plans to invest in new machines.", 'B2'),
      w("inflation", "noun", "inflyatsiya (narxlarning umumiy oʻsishi)", "инфляция", "a general rise in prices across a country", "High inflation makes everyday goods more expensive.", 'B2'),
      w("revenue", "noun", "tushum, daromad", "выручка, доход", "the total money that a business receives from sales", "Online sales now bring in half of the company's revenue.", 'B2'),
      w("start-up", "noun", "startap (yangi ochilgan kompaniya)", "стартап", "a new, small company, often in technology", "She works for a start-up that makes learning apps.", 'B2'),
      w("recession", "noun", "iqtisodiy tanazzul, retsessiya", "рецессия, экономический спад", "a period when a country's economy is doing badly", "Many small businesses closed during the recession.", 'C1'),
      w("merger", "noun", "(kompaniyalarning) qoʻshilishi", "слияние (компаний)", "the joining of two or more companies into one", "After the merger, the two banks became one large bank.", 'C1'),
      w("market share", "noun", "bozor ulushi", "доля рынка", "the part of all sales in a market that one company has", "The firm has increased its market share to thirty per cent.", 'C1'),
    ],
  },
  {
    id: 'arts-music',
    emoji: '🎨',
    title: { uz: "Sanʼat va musiqa", ru: "Искусство и музыка", en: "Art and music" },
    words: [
      w("painting", "noun", "rasm (boʻyoqda chizilgan), kartina", "картина", "a picture made with paint", "There is a beautiful painting of Samarkand in our living room.", 'A2'),
      w("instrument", "noun", "cholgʻu asbobi", "музыкальный инструмент", "an object such as a piano or guitar that you use to make music", "Do you play a musical instrument?", 'A2'),
      w("band", "noun", "(musiqiy) guruh", "(музыкальная) группа", "a group of people who play music together", "My brother plays the guitar in a rock band.", 'A2'),
      w("singer", "noun", "xonanda, qoʻshiqchi", "певец, певица", "a person who sings, often as a job", "The singer thanked everyone at the end of the show.", 'A2'),
      w("exhibition", "noun", "koʻrgazma", "выставка", "a public show of paintings, photos or other objects", "We went to an exhibition of modern art.", 'B1'),
      w("gallery", "noun", "galereya", "галерея", "a building or room where people can look at works of art", "The new gallery shows the work of young artists.", 'B1'),
      w("lyrics", "noun", "qoʻshiq matni", "текст песни", "the words of a song", "I can never remember the lyrics of this song.", 'B1'),
      w("perform", "verb", "ijro etmoq, sahnada chiqish qilmoq", "выступать, исполнять", "to sing, dance, play music or act in front of people", "The students will perform a traditional dance.", 'B1'),
      w("portrait", "noun", "portret", "портрет", "a painting, drawing or photo of a person", "The artist painted a portrait of her grandmother.", 'B1'),
      w("sculpture", "noun", "haykal; haykaltaroshlik", "скульптура", "a piece of art made from stone, metal or wood", "There is a large bronze sculpture in the main square.", 'B2'),
      w("melody", "noun", "kuy, ohang", "мелодия", "a group of musical notes that make a tune", "The melody of this song is very easy to remember.", 'B2'),
      w("abstract", "adjective", "abstrakt, mavhum", "абстрактный", "(of art) using shapes and colours instead of showing real people or things", "I don't really understand abstract paintings.", 'B2'),
      w("rehearsal", "noun", "repetitsiya, tayyorgarlik mashqi", "репетиция", "a practice before a public performance", "The orchestra has a rehearsal every Thursday evening.", 'B2'),
      w("acclaimed", "adjective", "eʼtirof etilgan, yuqori baholangan", "признанный, получивший признание", "praised by many people, especially critics", "The film was acclaimed by critics around the world.", 'C1'),
      w("aesthetic", "adjective", "estetik, goʻzallikka oid", "эстетический", "connected with beauty and art", "The old building has great aesthetic value.", 'C1'),
      w("improvise", "verb", "badiha qilmoq, improvizatsiya qilmoq", "импровизировать", "to play or perform something without preparing it first", "Jazz musicians often improvise during a performance.", 'C1'),
    ],
  },
  {
    id: 'celebrations-traditions',
    emoji: '🎉',
    title: { uz: "Bayramlar va urf-odatlar", ru: "Праздники и традиции", en: "Celebrations and traditions" },
    words: [
      w("celebrate", "verb", "nishonlamoq", "праздновать, отмечать", "to do something enjoyable for a special day or event", "We celebrate Navruz on the twenty-first of March.", 'A2'),
      w("invite", "verb", "taklif qilmoq", "приглашать", "to ask someone to come to a party or event", "They invited two hundred guests to the wedding.", 'A2'),
      w("gift", "noun", "sovgʻa", "подарок", "something that you give to someone, for example on their birthday", "She gave me a lovely gift for my birthday.", 'A2'),
      w("candle", "noun", "sham", "свеча", "a stick of wax that gives light when it burns", "He blew out all the candles on his birthday cake.", 'A2'),
      w("anniversary", "noun", "yillik sana, yubiley", "годовщина", "the same date as an important event in an earlier year", "My parents' wedding anniversary is in June.", 'B1'),
      w("custom", "noun", "odat, rasm-rusum", "обычай", "something that people in a place have done in the same way for a long time", "It is a custom to take off your shoes before entering a house.", 'B1'),
      w("festive", "adjective", "bayramona", "праздничный", "happy and bright because of a celebration", "The streets look very festive before the New Year.", 'B1'),
      w("decorate", "verb", "bezamoq", "украшать", "to make something look nicer by adding pretty things to it", "We decorated the room with balloons and flowers.", 'B1'),
      w("bride", "noun", "kelin", "невеста", "a woman on her wedding day", "The bride and groom danced together for the first time.", 'B1'),
      w("occasion", "noun", "(muhim) voqea, marosim", "(особый) случай, событие", "a special event or celebration", "A grandmother's seventieth birthday is a big occasion for the whole family.", 'B2'),
      w("reunion", "noun", "diydor koʻrishish, uchrashuv", "встреча (после долгой разлуки)", "a meeting of people who have not seen each other for a long time", "We have a big family reunion every summer.", 'B2'),
      w("feast", "noun", "ziyofat, bayram dasturxoni", "пир, праздничное застолье", "a large special meal for many people", "On Navruz, neighbours share a feast of sumalak and halim.", 'B2'),
      w("fireworks", "noun", "mushakbozlik, salyut", "фейерверк, салют", "colourful explosions in the sky, used to celebrate something", "We watched the fireworks from the roof of our building.", 'B2'),
      w("commemorate", "verb", "xotirlamoq, sharafiga nishonlamoq", "отмечать (память о), чтить", "to do something special to remember an important person or event", "The festival commemorates the founding of the city.", 'C1'),
      w("time-honoured", "adjective", "azaldan kelayotgan, qadimiy", "освящённый временем, давний", "respected because it has existed for a very long time", "Cooking sumalak together overnight is a time-honoured Navruz custom.", 'C1'),
      w("festivities", "noun", "bayram tantanalari", "торжества, празднества", "the events and activities that are part of a celebration", "The festivities went on until midnight.", 'C1'),
    ],
  },
  {
    id: 'clothes-appearance',
    emoji: '👗',
    title: { uz: "Kiyim va tashqi koʻrinish", ru: "Одежда и внешность", en: "Clothes and appearance" },
    words: [
      w("fit", "verb", "(oʻlchamiga) toʻgʻri kelmoq", "подходить по размеру, сидеть", "to be the right size for someone", "These jeans don't fit me any more.", 'A2'),
      w("curly", "adjective", "jingalak", "кудрявый, вьющийся", "(of hair) forming curves and circles", "She has long curly hair.", 'A2'),
      w("try on", "phrasal verb", "kiyib koʻrmoq", "примерять", "to put on clothes to see if they fit or look good", "Can I try on this jacket, please?", 'A2'),
      w("beard", "noun", "soqol", "борода", "hair that grows on a man's chin and cheeks", "My grandfather has a long white beard.", 'A2'),
      w("fashionable", "adjective", "moda boʻlgan, zamonaviy", "модный", "popular at a particular time", "Wide trousers are fashionable again this year.", 'B1'),
      w("suit", "verb", "yarashmoq", "идти (кому-то), быть к лицу", "to look good on someone", "That colour really suits you.", 'B1'),
      w("casual", "adjective", "oddiy, kundalik (kiyim)", "повседневный", "(of clothes) comfortable and not formal", "We can wear casual clothes to work on Fridays.", 'B1'),
      w("slim", "adjective", "qomatli, xushbichim", "стройный", "thin in an attractive way", "He is tall and slim, with dark hair.", 'B1'),
      w("match", "verb", "mos kelmoq, uygʻun boʻlmoq", "сочетаться, подходить (к чему-то)", "to look good together because of colour or style", "Your shoes match your bag perfectly.", 'B1'),
      w("outfit", "noun", "libos, kiyim toʻplami", "наряд, комплект одежды", "a set of clothes that you wear together", "She bought a new outfit for her cousin's wedding.", 'B2'),
      w("well-dressed", "adjective", "yaxshi (did) kiyingan", "хорошо одетый", "wearing attractive and good-quality clothes", "Everyone at the ceremony was very well-dressed.", 'B2'),
      w("wrinkle", "noun", "ajin", "морщина", "a small line on your skin that appears as you get older", "My grandmother has a lot of wrinkles, but her eyes are still young.", 'B2'),
      w("hand-me-down", "noun", "kattalardan qolgan (eski) kiyim", "вещь, доставшаяся от старших", "a piece of clothing that an older brother or sister wore first", "Most of my clothes were hand-me-downs from my brother.", 'B2'),
      w("dress code", "noun", "kiyinish qoidasi", "дресс-код", "rules about what clothes people must wear in a place", "The restaurant has a strict dress code.", 'C1'),
      w("scruffy", "adjective", "ust-boshi tartibsiz, pala-partish kiyingan", "неопрятный, потрёпанный", "untidy and a little dirty-looking", "He looked a bit scruffy in his old jeans and T-shirt.", 'C1'),
      w("flattering", "adjective", "yarashadigan, chiroyli koʻrsatadigan", "выгодно подчёркивающий, идущий к лицу", "making someone look more attractive", "Dark colours can be very flattering.", 'C1'),
    ],
  },
];
