import type { Level, TopicWord, VocabTopic } from './types';

// Mavzuli lugʻat: har mavzuda soʻzlar, oʻzbekcha va ruscha tarjima, ta’rif va misol.
const w = (
  word: string,
  pos: string,
  uz: string,
  ru: string,
  definition: string,
  example: string,
  level: Level,
): TopicWord => ({ word, pos, uz, ru, definition, example, level });

export const VOCAB_TOPICS: VocabTopic[] = [
  {
    id: 'home-family',
    emoji: '🏠',
    title: { uz: "Uy va oila", ru: "Дом и семья", en: "Home and family" },
    words: [
      w("relative", "noun", "qarindosh", "родственник", "a member of your family", "Most of my relatives live in Andijan.", 'A2'),
      w("grandparents", "noun", "buvi va bobo", "бабушка и дедушка", "the parents of your mother or father", "We visit our grandparents every weekend.", 'A2'),
      w("flat", "noun", "kvartira, xonadon", "квартира", "a set of rooms for living in, on one floor of a building", "They rent a small flat near the metro.", 'A2'),
      w("neighbour", "noun", "qoʻshni", "сосед", "a person who lives next to you or near you", "Our neighbour always helps us in the garden.", 'A2'),
      w("housework", "noun", "uy yumushlari", "работа по дому", "jobs such as cleaning, washing and cooking at home", "My brother and I share the housework.", 'B1'),
      w("bring up", "phrasal verb", "tarbiyalab voyaga yetkazmoq", "воспитывать, растить", "to care for a child until he or she is an adult", "It isn't easy to bring up three children alone.", 'B1'),
      w("get on with", "phrasal verb", "(kim bilan) chiqishmoq, til topishmoq", "ладить (с кем-то)", "to have a friendly relationship with someone", "I get on well with my mother-in-law.", 'B1'),
      w("household", "noun", "xonadon, bir uyda yashovchilar", "домохозяйство, все живущие в доме", "all the people who live together in one home", "In our household, everyone eats dinner together.", 'B1'),
      w("only child", "noun", "oiladagi yolgʻiz farzand", "единственный ребёнок", "a child who has no brothers or sisters", "As an only child, she spent a lot of time with adults.", 'B1'),
      w("sibling", "noun", "aka-uka yoki opa-singil", "брат или сестра", "a brother or sister", "Do you have any siblings?", 'B2'),
      w("extended family", "noun", "katta oila (barcha qarindoshlar bilan)", "большая семья (включая всех родственников)", "a family that includes grandparents, aunts, uncles and cousins", "In Uzbekistan, the extended family often lives close together.", 'B2'),
      w("upbringing", "noun", "tarbiya", "воспитание", "the way parents care for and teach a child", "She had a strict but loving upbringing.", 'B2'),
      w("take after", "phrasal verb", "(ota-onasiga) oʻxshamoq", "быть похожим (на родителя)", "to look or behave like an older member of your family", "Everyone says I take after my father.", 'B2'),
      w("hospitality", "noun", "mehmondoʻstlik", "гостеприимство", "friendly and generous behaviour towards guests", "Uzbek families are famous for their hospitality.", 'B2'),
      w("close-knit", "adjective", "ahil, bir-biriga mehribon", "сплочённый, дружный", "(of a family or group) whose members support and care about each other", "They are a close-knit family who celebrate every holiday together.", 'C1'),
      w("estranged", "adjective", "aloqasi uzilgan, begonalashgan", "отчуждённый, прервавший отношения", "no longer in contact with a family member because of a disagreement", "He has been estranged from his brother for years.", 'C1'),
      w("breadwinner", "noun", "oila boquvchisi", "кормилец семьи", "the person in a family who earns the money", "For many years my mother was the main breadwinner.", 'C1'),
    ],
  },
  {
    id: 'food-cooking',
    emoji: '🍲',
    title: { uz: "Taom va pazandachilik", ru: "Еда и кулинария", en: "Food and cooking" },
    words: [
      w("recipe", "noun", "retsept (taom tayyorlash usuli)", "рецепт (блюда)", "instructions for cooking a dish", "Can you give me your recipe for plov?", 'A2'),
      w("boil", "verb", "qaynatmoq, suvda pishirmoq", "варить, кипятить", "to heat a liquid until it bubbles, or to cook food in very hot water", "Boil the potatoes for twenty minutes.", 'A2'),
      w("fry", "verb", "qovurmoq", "жарить", "to cook food in hot oil", "First, fry the onions and carrots in oil.", 'A2'),
      w("spicy", "adjective", "achchiq, ziravorli", "острый, пряный", "having a strong, hot taste from spices", "This soup is too spicy for me.", 'A2'),
      w("ingredient", "noun", "masalliq", "ингредиент", "one of the foods used to make a dish", "The main ingredient of this salad is fresh tomatoes.", 'B1'),
      w("vegetarian", "noun", "vegetarian (goʻsht yemaydigan odam)", "вегетарианец", "a person who does not eat meat or fish", "My sister became a vegetarian last year.", 'B1'),
      w("leftovers", "noun", "ortib qolgan ovqat", "остатки еды", "food that is not eaten at the end of a meal", "We had the leftovers for lunch the next day.", 'B1'),
      w("homemade", "adjective", "uyda tayyorlangan", "домашний, приготовленный дома", "made at home, not bought in a shop", "Nothing tastes better than homemade bread.", 'B1'),
      w("portion", "noun", "porsiya", "порция", "the amount of food for one person", "The portions in this restaurant are huge.", 'B1'),
      w("stir", "verb", "aralashtirmoq (qoshiq bilan)", "помешивать", "to move a spoon round and round in food or liquid", "Stir the sauce slowly so that it doesn't burn.", 'B1'),
      w("nutritious", "adjective", "toʻyimli", "питательный", "full of the things your body needs to stay healthy", "Lentils are cheap and very nutritious.", 'B2'),
      w("bland", "adjective", "ta’msiz, bemaza", "пресный, безвкусный", "having very little flavour", "The hospital food was rather bland.", 'B2'),
      w("cuisine", "noun", "milliy oshxona, taomlar", "кухня (национальная)", "the style of cooking of a particular country or region", "Uzbek cuisine is famous for its plov and samsa.", 'B2'),
      w("appetising", "adjective", "ishtahani ochadigan", "аппетитный", "looking or smelling good to eat", "The smell from the kitchen was very appetising.", 'B2'),
      w("savour", "verb", "rohatlanib tatimoq", "смаковать", "to eat or drink slowly to enjoy the taste fully", "He savoured every bite of his grandmother's pie.", 'C1'),
      w("culinary", "adjective", "pazandachilikka oid", "кулинарный", "connected with cooking", "She studied culinary arts in Istanbul.", 'C1'),
      w("palate", "noun", "ta’m bilish qobiliyati", "вкус (умение различать вкус)", "a person's ability to judge good food and drink", "This dessert is too sweet for my palate.", 'C1'),
    ],
  },
  {
    id: 'travel',
    emoji: '✈️',
    title: { uz: "Sayohat", ru: "Путешествия", en: "Travel" },
    words: [
      w("luggage", "noun", "yuk, bagaj", "багаж", "the bags and cases you take on a journey", "How much luggage can I take on the plane?", 'A2'),
      w("book", "verb", "oldindan band qilmoq, bron qilmoq", "бронировать", "to arrange to have a seat, room or ticket in advance", "We booked a hotel room for three nights.", 'A2'),
      w("sightseeing", "noun", "diqqatga sazovor joylarni tomosha qilish", "осмотр достопримечательностей", "visiting interesting places as a tourist", "We spent the whole day sightseeing in Khiva.", 'A2'),
      w("souvenir", "noun", "esdalik sovgʻa", "сувенир", "something you buy to remember a place", "I bought a ceramic plate as a souvenir.", 'A2'),
      w("check in", "phrasal verb", "roʻyxatdan oʻtmoq (aeroport, mehmonxonada)", "зарегистрироваться (в аэропорту, отеле)", "to arrive at a hotel or airport and give your details", "You need to check in two hours before the flight.", 'B1'),
      w("delay", "noun", "kechikish", "задержка", "a situation in which something happens later than planned", "There was a two-hour delay because of the snow.", 'B1'),
      w("destination", "noun", "borish manzili", "пункт назначения", "the place where someone or something is going", "Samarkand is a popular destination for tourists.", 'B1'),
      w("accommodation", "noun", "turar joy", "жильё, размещение", "a place to stay, such as a hotel or a flat", "The price includes flights and accommodation.", 'B1'),
      w("itinerary", "noun", "sayohat rejasi, yoʻnalish", "маршрут, план поездки", "a detailed plan of a journey", "Our itinerary includes Bukhara, Khiva and Samarkand.", 'B2'),
      w("off the beaten track", "idiom", "gavjum yoʻllardan chetda, kam odam boradigan joyda", "вдали от туристических маршрутов", "in a quiet place that few tourists visit", "We found a lovely village off the beaten track.", 'B2'),
      w("jet lag", "noun", "vaqt mintaqasi almashuvidan keyingi holsizlik", "синдром смены часовых поясов", "tiredness after a long flight across time zones", "I had terrible jet lag after flying to New York.", 'B2'),
      w("layover", "noun", "tranzit toʻxtash (reyslar orasida)", "пересадка, остановка между рейсами", "a short stay in a place between two flights", "We had a six-hour layover in Istanbul.", 'B2'),
      w("breathtaking", "adjective", "hayratlanarli darajada goʻzal", "захватывающий дух", "extremely beautiful or impressive", "The view from the mountain was breathtaking.", 'B2'),
      w("picturesque", "adjective", "manzarali, suratdek goʻzal", "живописный", "pretty, like a picture", "Chimgan has many picturesque mountain villages.", 'C1'),
      w("wanderlust", "noun", "sayohatga kuchli ishtiyoq", "страсть к путешествиям", "a strong wish to travel", "Her wanderlust has taken her to over forty countries.", 'C1'),
      w("embark on", "phrasal verb", "(safarni, yangi ishni) boshlamoq", "отправиться (в путь), приступить (к чему-то)", "to start a journey or something new and important", "Next month they will embark on a trip around Central Asia.", 'C1'),
    ],
  },
  {
    id: 'work-careers',
    emoji: '💼',
    title: { uz: "Ish va kasb", ru: "Работа и карьера", en: "Work and careers" },
    words: [
      w("salary", "noun", "maosh, oylik", "зарплата, оклад", "money you receive every month for your job", "She earns a good salary as a programmer.", 'A2'),
      w("colleague", "noun", "hamkasb", "коллега", "a person you work with", "My colleagues are very friendly.", 'A2'),
      w("interview", "noun", "suhbat (ishga qabul qilishda)", "собеседование", "a formal meeting where someone asks you questions for a job", "I have a job interview on Monday.", 'A2'),
      w("apply for", "phrasal verb", "(ishga, oʻqishga) ariza topshirmoq", "подавать заявление (на работу, учёбу)", "to officially ask for a job, a place or a document", "I want to apply for a job at a bank.", 'B1'),
      w("deadline", "noun", "oxirgi muddat", "крайний срок, дедлайн", "the time by which work must be finished", "The deadline for the report is Friday.", 'B1'),
      w("promotion", "noun", "lavozimga koʻtarilish", "повышение по службе", "a move to a higher position at work", "After two years, she got a promotion.", 'B1'),
      w("part-time", "adjective", "yarim stavkali, toʻliq boʻlmagan ish kuni", "с неполной занятостью", "working only part of the day or week", "Many students have part-time jobs.", 'B1'),
      w("CV", "noun", "rezyume, tarjimai hol", "резюме", "a document describing your education and work experience", "Please send your CV to our HR department.", 'B1'),
      w("resign", "verb", "(oʻz xohishi bilan) ishdan boʻshamoq", "уволиться по собственному желанию", "to officially leave your job", "He resigned because he wanted to start his own business.", 'B2'),
      w("workload", "noun", "ish hajmi, yuklama", "рабочая нагрузка", "the amount of work a person has to do", "Teachers often complain about their heavy workload.", 'B2'),
      w("entrepreneur", "noun", "tadbirkor", "предприниматель", "a person who starts their own business", "Young entrepreneurs in Tashkent are opening IT companies.", 'B2'),
      w("freelance", "adjective", "mustaqil (shtatdan tashqari) ishlaydigan", "внештатный, фрилансерский", "working for different companies, not employed by one", "She is a freelance translator.", 'B2'),
      w("job security", "noun", "ish joyining barqarorligi", "гарантия занятости", "the feeling that you will not lose your job", "Government jobs usually offer good job security.", 'B2'),
      w("burnout", "noun", "kasbiy toliqish, «kuyib qolish»", "эмоциональное выгорание", "extreme tiredness caused by working too hard for too long", "Long hours without breaks can lead to burnout.", 'C1'),
      w("career ladder", "noun", "martaba zinapoyasi", "карьерная лестница", "the series of steps to higher positions in a job", "He climbed the career ladder very quickly.", 'C1'),
      w("perk", "noun", "qoʻshimcha imtiyoz", "льгота, бонус", "an extra benefit you get from your job", "Free lunches are one of the perks of working here.", 'C1'),
      w("redundant", "adjective", "shtat qisqarishi sababli ishdan boʻshatilgan", "сокращённый (уволенный по сокращению)", "having lost your job because your employer no longer needs you", "Two hundred workers were made redundant last year.", 'C1'),
    ],
  },
  {
    id: 'education',
    emoji: '🎓',
    title: { uz: "Ta’lim", ru: "Образование", en: "Education" },
    words: [
      w("homework", "noun", "uy vazifasi", "домашнее задание", "school work that students do at home", "I usually do my homework after dinner.", 'A2'),
      w("timetable", "noun", "dars jadvali", "расписание", "a list of lessons and the times they happen", "Our new timetable starts next week.", 'A2'),
      w("subject", "noun", "fan (oʻquv fani)", "предмет (учебный)", "an area of knowledge studied at school", "My favourite subject is chemistry.", 'A2'),
      w("pass", "verb", "(imtihondan) oʻtmoq", "сдать (экзамен)", "to be successful in an exam or test", "Did you pass your driving test?", 'A2'),
      w("revise", "verb", "(imtihonga) takrorlamoq", "повторять (материал к экзамену)", "to study again what you have learned before an exam", "I need to revise for my English exam.", 'B1'),
      w("degree", "noun", "oliy ma’lumot diplomi, daraja", "высшее образование, степень", "a qualification you get after finishing university", "She has a degree in economics.", 'B1'),
      w("scholarship", "noun", "grant, stipendiya", "стипендия, грант", "money given to a student to pay for their studies", "He won a scholarship to study in Korea.", 'B1'),
      w("graduate", "verb", "(oʻqishni) tamomlamoq", "окончить (вуз, школу)", "to finish your studies at a university or school", "My sister graduated from university in 2023.", 'B1'),
      w("tuition fees", "noun", "oʻqish toʻlovi, kontrakt", "плата за обучение", "the money you pay to study at a university or school", "Tuition fees at private universities are high.", 'B2'),
      w("curriculum", "noun", "oʻquv dasturi", "учебная программа", "all the subjects taught in a school or course", "Coding is now part of the school curriculum.", 'B2'),
      w("assignment", "noun", "topshiriq, vazifa", "задание", "a piece of work given to students", "The assignment must be submitted online by Friday.", 'B2'),
      w("plagiarism", "noun", "plagiat, oʻzganing ishini oʻzlashtirish", "плагиат", "copying someone else's work and saying it is yours", "The university takes plagiarism very seriously.", 'B2'),
      w("literate", "adjective", "savodli", "грамотный", "able to read and write", "Almost all adults in the country are literate.", 'B2'),
      w("critical thinking", "noun", "tanqidiy fikrlash", "критическое мышление", "the ability to analyse information and judge it carefully", "Good teachers encourage critical thinking.", 'C1'),
      w("rote learning", "noun", "mexanik yodlash", "зубрёжка", "learning by repeating facts without really understanding them", "Rote learning is still common in many schools.", 'C1'),
      w("lifelong learning", "noun", "umrbod ta’lim", "непрерывное образование", "continuing to learn new things throughout your life", "Online courses make lifelong learning easier.", 'C1'),
    ],
  },
  {
    id: 'health',
    emoji: '🩺',
    title: { uz: "Salomatlik", ru: "Здоровье", en: "Health" },
    words: [
      w("headache", "noun", "bosh ogʻrigʻi", "головная боль", "a pain in your head", "I have a terrible headache.", 'A2'),
      w("medicine", "noun", "dori", "лекарство", "something you take to get better when you are ill", "Take this medicine three times a day.", 'A2'),
      w("fever", "noun", "isitma", "температура, жар", "a high body temperature when you are ill", "The child has had a fever since yesterday.", 'A2'),
      w("appointment", "noun", "(shifokor) qabuli, oldindan belgilangan uchrashuv", "запись (к врачу), назначенная встреча", "an arranged time to see a doctor or another person", "I've made an appointment with the dentist.", 'B1'),
      w("prescription", "noun", "retsept (dori uchun)", "рецепт (на лекарство)", "a doctor's written order for medicine", "You need a prescription to buy these tablets.", 'B1'),
      w("injury", "noun", "jarohat, shikast", "травма", "damage to the body, for example in an accident", "He missed the match because of a knee injury.", 'B1'),
      w("diet", "noun", "ovqatlanish tartibi, parhez", "рацион, диета", "the food you usually eat", "A healthy diet includes plenty of vegetables.", 'B1'),
      w("recover", "verb", "tuzalmoq, sogʻaymoq", "выздоравливать", "to become healthy again after an illness", "It took her a month to recover from the flu.", 'B1'),
      w("allergy", "noun", "allergiya", "аллергия", "a bad reaction of the body to certain foods, plants, etc.", "I have an allergy to nuts.", 'B1'),
      w("check-up", "noun", "tibbiy koʻrik", "медосмотр", "a general medical examination", "You should have a check-up once a year.", 'B1'),
      w("symptom", "noun", "alomat, belgi", "симптом", "a sign that you have an illness", "Common symptoms of flu are fever and a sore throat.", 'B2'),
      w("immune system", "noun", "immunitet tizimi", "иммунная система", "the system in your body that fights disease", "Sleep helps your immune system stay strong.", 'B2'),
      w("mental health", "noun", "ruhiy salomatlik", "психическое здоровье", "the health of your mind and emotions", "Regular exercise is good for your mental health.", 'B2'),
      w("chronic", "adjective", "surunkali", "хронический", "(of an illness) lasting for a long time", "She suffers from chronic back pain.", 'B2'),
      w("sedentary", "adjective", "kam harakatli", "малоподвижный, сидячий", "involving a lot of sitting and little physical activity", "A sedentary lifestyle can cause back problems.", 'C1'),
      w("wellbeing", "noun", "farovonlik, oʻzini yaxshi his qilish", "благополучие", "the state of being healthy and happy", "Companies are paying more attention to staff wellbeing.", 'C1'),
      w("relapse", "noun", "kasallikning qaytalanishi", "рецидив", "the return of an illness after a period of improvement", "The doctor warned him that stress could cause a relapse.", 'C1'),
    ],
  },
  {
    id: 'technology',
    emoji: '💻',
    title: { uz: "Texnologiya", ru: "Технологии", en: "Technology" },
    words: [
      w("download", "verb", "yuklab olmoq", "скачивать", "to copy files from the internet to your device", "You can download the app for free.", 'A2'),
      w("password", "noun", "parol", "пароль", "a secret word that lets you use a computer or an account", "Never share your password with anyone.", 'A2'),
      w("keyboard", "noun", "klaviatura", "клавиатура", "the set of keys you press to type on a computer", "I spilled tea on my keyboard.", 'A2'),
      w("charge", "verb", "quvvatlamoq, zaryadlamoq", "заряжать", "to fill a battery with electricity", "I forgot to charge my phone last night.", 'A2'),
      w("update", "noun", "yangilanish", "обновление", "a newer version of a program or app", "Install the latest update to fix the problem.", 'B1'),
      w("device", "noun", "qurilma", "устройство", "a machine or tool made for a special purpose, such as a phone", "How many devices do you use every day?", 'B1'),
      w("user-friendly", "adjective", "foydalanish uchun qulay", "удобный для пользователя", "easy to use and understand", "The new website is much more user-friendly.", 'B1'),
      w("browse", "verb", "(internetda) koʻz yugurtirmoq, sahifalarni koʻrmoq", "просматривать (сайты)", "to look at information on the internet without a fixed plan", "I like to browse online shops in the evening.", 'B1'),
      w("data", "noun", "ma’lumotlar", "данные", "information, especially information stored on a computer", "The app collects data about your location.", 'B1'),
      w("artificial intelligence", "noun", "sun’iy intellekt", "искусственный интеллект", "computer systems that can do tasks that usually need human intelligence", "Artificial intelligence is changing many jobs.", 'B2'),
      w("cybersecurity", "noun", "kiberxavfsizlik", "кибербезопасность", "protecting computers and networks from attacks", "Banks spend millions on cybersecurity.", 'B2'),
      w("breakthrough", "noun", "katta yutuq, kashfiyot", "прорыв", "an important new discovery or development", "Scientists have made a breakthrough in battery technology.", 'B2'),
      w("screen time", "noun", "ekran oldida oʻtkazilgan vaqt", "экранное время", "time spent looking at phones, computers or TV", "Parents often worry about their children's screen time.", 'B2'),
      w("obsolete", "adjective", "eskirgan, iste’moldan chiqqan", "устаревший", "no longer used because something better exists", "CDs are almost obsolete now.", 'C1'),
      w("cutting-edge", "adjective", "eng ilgʻor, eng zamonaviy", "передовой, новейший", "the most modern and advanced", "The lab uses cutting-edge equipment.", 'C1'),
      w("troubleshoot", "verb", "nosozlikni aniqlab bartaraf etmoq", "устранять неполадки", "to find and fix problems in a system or machine", "Our IT team can help you troubleshoot your laptop.", 'C1'),
    ],
  },
  {
    id: 'environment',
    emoji: '🌍',
    title: { uz: "Atrof-muhit", ru: "Окружающая среда", en: "The environment" },
    words: [
      w("pollution", "noun", "ifloslanish", "загрязнение", "dirty or harmful substances in the air, water or land", "Air pollution is a big problem in winter.", 'A2'),
      w("recycle", "verb", "qayta ishlamoq", "перерабатывать (отходы)", "to treat waste so that it can be used again", "We recycle all our plastic bottles.", 'A2'),
      w("rubbish", "noun", "axlat", "мусор", "things that you throw away", "Please don't leave rubbish in the park.", 'A2'),
      w("energy", "noun", "energiya", "энергия", "power from electricity, gas, the sun, etc.", "Turn off the lights to save energy.", 'A2'),
      w("climate change", "noun", "iqlim oʻzgarishi", "изменение климата", "long-term changes in the Earth's temperature and weather", "Climate change affects farmers in Central Asia.", 'B1'),
      w("endangered", "adjective", "yoʻqolib ketish xavfi ostidagi", "находящийся под угрозой исчезновения", "at risk of disappearing completely", "The snow leopard is an endangered species.", 'B1'),
      w("waste", "noun", "chiqindi", "отходы", "material that is thrown away because it is no longer useful", "Factories must reduce their waste.", 'B1'),
      w("drought", "noun", "qurgʻoqchilik", "засуха", "a long period without rain", "The drought destroyed most of the crops.", 'B2'),
      w("renewable", "adjective", "qayta tiklanadigan", "возобновляемый", "(of energy) coming from sources that don't run out, like the sun or wind", "Uzbekistan is building new renewable energy plants.", 'B2'),
      w("carbon footprint", "noun", "uglerod izi", "углеродный след", "the amount of carbon dioxide that your activities produce", "Flying less can reduce your carbon footprint.", 'B2'),
      w("deforestation", "noun", "oʻrmonlarning kesib yuborilishi", "вырубка лесов", "cutting down large areas of forest", "Deforestation threatens many animals.", 'B2'),
      w("sustainable", "adjective", "barqaror, tabiatga zarar yetkazmaydigan", "устойчивый, экологичный", "able to continue for a long time without harming the environment", "We need more sustainable ways of farming.", 'B2'),
      w("emissions", "noun", "zararli chiqindi gazlar", "выбросы", "gases released into the air", "Cars are a major source of emissions in cities.", 'B2'),
      w("biodiversity", "noun", "biologik xilma-xillik", "биоразнообразие", "the variety of plants and animals in an area", "Wetlands are very rich in biodiversity.", 'C1'),
      w("desertification", "noun", "choʻllanish", "опустынивание", "the process by which land turns into desert", "The Aral Sea disaster led to desertification in the region.", 'C1'),
      w("irreversible", "adjective", "qaytarib boʻlmaydigan", "необратимый", "impossible to change back to how it was before", "Some damage to the environment is irreversible.", 'C1'),
    ],
  },
  {
    id: 'city-transport',
    emoji: '🏙️',
    title: { uz: "Shahar va transport", ru: "Город и транспорт", en: "City and transport" },
    words: [
      w("traffic jam", "noun", "tirbandlik", "пробка", "a long line of cars that cannot move", "We were stuck in a traffic jam for an hour.", 'A2'),
      w("crossroads", "noun", "chorraha", "перекрёсток", "a place where two roads cross", "Turn left at the crossroads.", 'A2'),
      w("crowded", "adjective", "gavjum, odam toʻla", "переполненный, многолюдный", "full of people", "The bus was so crowded that I had to stand.", 'A2'),
      w("public transport", "noun", "jamoat transporti", "общественный транспорт", "buses, trains and the metro that everyone can use", "Public transport in our city is cheap.", 'A2'),
      w("pedestrian", "noun", "piyoda", "пешеход", "a person who is walking in the street", "This street is only for pedestrians.", 'B1'),
      w("fare", "noun", "yoʻl haqi", "стоимость проезда", "the money you pay to travel by bus, train, taxi, etc.", "The metro fare has gone up again.", 'B1'),
      w("rush hour", "noun", "tigʻiz soat, eng gavjum vaqt", "час пик", "the busy time when people travel to and from work", "Try to avoid the metro during rush hour.", 'B1'),
      w("commute", "verb", "(har kuni) ishga qatnamoq", "ездить на работу (ежедневно)", "to travel regularly between home and work", "I commute to work by metro.", 'B1'),
      w("suburb", "noun", "shahar atrofidagi turar joy hududi", "пригород", "an area where people live outside the centre of a city", "They moved to a quiet suburb.", 'B1'),
      w("landmark", "noun", "mashhur obida, moʻljal", "достопримечательность, ориентир", "a famous building or place that is easy to recognise", "The TV tower is a well-known landmark in Tashkent.", 'B2'),
      w("urban", "adjective", "shaharga oid, shahar", "городской", "relating to towns and cities", "Urban areas are growing quickly.", 'B2'),
      w("outskirts", "noun", "shahar chekkasi", "окраина", "the outer areas of a city", "The new market is on the outskirts of the city.", 'B2'),
      w("infrastructure", "noun", "infratuzilma", "инфраструктура", "basic systems such as roads, bridges and water supply", "The government is investing in new infrastructure.", 'B2'),
      w("congestion", "noun", "(yoʻllardagi) haddan tashqari tirbandlik", "перегруженность (дорог)", "too much traffic in a place", "Congestion in the city centre is getting worse.", 'C1'),
      w("pedestrianised", "adjective", "faqat piyodalar uchun ajratilgan", "пешеходный (закрытый для машин)", "(of a street or area) closed to cars", "The old town centre has been pedestrianised.", 'C1'),
      w("gentrification", "noun", "eski mahallalarning boy aholi hisobiga yangilanishi", "джентрификация", "the change of a poorer area as richer people move in", "Gentrification has pushed up rents in the old town.", 'C1'),
    ],
  },
  {
    id: 'money-shopping',
    emoji: '💰',
    title: { uz: "Pul va xarid", ru: "Деньги и покупки", en: "Money and shopping" },
    words: [
      w("cash", "noun", "naqd pul", "наличные", "money in coins and notes", "Do you want to pay by card or in cash?", 'A2'),
      w("receipt", "noun", "chek", "чек", "a piece of paper that shows what you paid", "Keep the receipt in case you need to return it.", 'A2'),
      w("discount", "noun", "chegirma", "скидка", "a lower price than usual", "Students get a ten percent discount.", 'A2'),
      w("afford", "verb", "(pulga) qurbi yetmoq", "позволить себе (по деньгам)", "to have enough money to buy something", "I can't afford a new car.", 'B1'),
      w("bargain", "noun", "arzon va foydali xarid", "выгодная покупка", "something bought for less than its usual price", "This jacket was a real bargain.", 'B1'),
      w("refund", "noun", "pulni qaytarish", "возврат денег", "money that is given back to you", "The shop gave me a full refund.", 'B1'),
      w("savings", "noun", "jamgʻarma", "сбережения", "money you keep for the future", "She spent all her savings on the trip.", 'B1'),
      w("budget", "noun", "byudjet, xarajatlar rejasi", "бюджет", "a plan of how much money you can spend", "We're on a tight budget this month.", 'B1'),
      w("loan", "noun", "qarz, kredit", "заём, кредит", "money borrowed from a bank that you must pay back", "They took out a loan to buy a house.", 'B1'),
      w("haggle", "verb", "savdolashmoq", "торговаться", "to argue about the price of something", "At the bazaar, you can haggle over prices.", 'B2'),
      w("debt", "noun", "qarz", "долг", "money that you owe someone", "He is trying to pay off his debts.", 'B2'),
      w("overpriced", "adjective", "narxi haddan tashqari baland", "слишком дорогой", "costing more than it is really worth", "The food at the airport is overpriced.", 'B2'),
      w("interest rate", "noun", "foiz stavkasi", "процентная ставка", "the percentage a bank charges or pays for money", "The bank has raised its interest rate.", 'B2'),
      w("impulse buying", "noun", "oʻylamasdan xarid qilish", "импульсивные покупки", "buying things suddenly without planning to", "Online ads encourage impulse buying.", 'C1'),
      w("frugal", "adjective", "tejamkor", "бережливый, экономный", "careful not to spend much money", "My grandparents lived a frugal life.", 'C1'),
      w("consumerism", "noun", "iste’molchilik", "потребительство, консюмеризм", "the belief that buying more and more things is good", "Some people criticise modern consumerism.", 'C1'),
    ],
  },
  {
    id: 'sport-leisure',
    emoji: '⚽',
    title: { uz: "Sport va boʻsh vaqt", ru: "Спорт и свободное время", en: "Sport and free time" },
    words: [
      w("hobby", "noun", "sevimli mashgʻulot", "хобби, увлечение", "an activity you do for fun in your free time", "My hobby is taking photos.", 'A2'),
      w("team", "noun", "jamoa", "команда", "a group of people who play a sport together", "Which football team do you support?", 'A2'),
      w("win", "verb", "gʻalaba qozonmoq, yutmoq", "выигрывать, побеждать", "to be the best in a game or competition", "Our school hopes to win the cup this year.", 'A2'),
      w("score", "verb", "(gol, ochko) urmoq", "забивать (гол), набирать (очки)", "to get a goal or a point in a game", "He scored twice in the final.", 'B1'),
      w("coach", "noun", "murabbiy", "тренер", "a person who trains a sports team or player", "Our coach makes us run every morning.", 'B1'),
      w("draw", "noun", "durang", "ничья", "a game in which both sides have the same score", "The match ended in a draw.", 'B1'),
      w("work out", "phrasal verb", "(sport zalida) mashq qilmoq", "тренироваться", "to do physical exercise to make your body stronger", "I work out at the gym three times a week.", 'B1'),
      w("take up", "phrasal verb", "(yangi mashgʻulot bilan) shugʻullana boshlamoq", "начать заниматься (чем-то)", "to start doing a new activity", "I'd like to take up chess.", 'B1'),
      w("spectator", "noun", "tomoshabin", "зритель", "a person who watches a sports event", "Thousands of spectators came to the stadium.", 'B2'),
      w("tournament", "noun", "turnir, musobaqa", "турнир", "a competition with many games or matches", "Tashkent hosted an international chess tournament.", 'B2'),
      w("stamina", "noun", "chidamlilik", "выносливость", "the physical strength to keep going for a long time", "Marathon runners need great stamina.", 'B2'),
      w("amateur", "adjective", "havaskor", "любительский", "doing something for pleasure, not as a job", "He plays for an amateur football club.", 'B2'),
      w("leisure", "noun", "hordiq, boʻsh vaqt", "досуг", "free time when you can relax", "How do you spend your leisure time?", 'B2'),
      w("competitive", "adjective", "gʻolib chiqishga intiluvchan", "азартный, стремящийся победить", "wanting very much to win or be the best", "My brother is very competitive, even at board games.", 'B2'),
      w("unwind", "verb", "dam olib, yozilmoq", "расслабиться, отдохнуть", "to relax after work or stress", "Reading helps me unwind in the evening.", 'C1'),
      w("sportsmanship", "noun", "sportchiga xos halollik va odob", "спортивное поведение, честная игра", "fair and polite behaviour in sport", "Both teams showed great sportsmanship after the match.", 'C1'),
      w("adrenaline", "noun", "adrenalin", "адреналин", "a chemical your body produces when you are excited or afraid", "Skydiving gives you a huge rush of adrenaline.", 'C1'),
    ],
  },
  {
    id: 'culture-media',
    emoji: '🎭',
    title: { uz: "Madaniyat va OAV", ru: "Культура и СМИ", en: "Culture and media" },
    words: [
      w("news", "noun", "yangiliklar", "новости", "information about recent events", "I read the news on my phone every morning.", 'A2'),
      w("concert", "noun", "konsert", "концерт", "a performance of music", "We went to a concert on Saturday night.", 'A2'),
      w("museum", "noun", "muzey", "музей", "a building where you can see old or interesting objects", "The history museum is in the centre of the city.", 'A2'),
      w("audience", "noun", "tomoshabinlar, tinglovchilar", "зрители, слушатели, аудитория", "the people who watch or listen to a performance", "The audience clapped for five minutes.", 'B1'),
      w("headline", "noun", "sarlavha", "заголовок", "the title of a newspaper or online article", "The story made headlines around the world.", 'B1'),
      w("review", "noun", "taqriz, sharh", "рецензия, отзыв", "an article giving an opinion about a book, film, etc.", "The film got excellent reviews.", 'B1'),
      w("tradition", "noun", "an’ana", "традиция", "a custom that has existed for a long time", "Cooking sumalak for Navruz is an old tradition.", 'B1'),
      w("social media", "noun", "ijtimoiy tarmoqlar", "социальные сети", "websites and apps for sharing content with other people", "Teenagers spend hours on social media.", 'B1'),
      w("heritage", "noun", "meros", "наследие", "traditions, buildings and art that come from the past", "Khiva is part of the world's cultural heritage.", 'B2'),
      w("broadcast", "verb", "efirga uzatmoq", "транслировать", "to send out a programme on TV or radio", "The match will be broadcast live.", 'B2'),
      w("influencer", "noun", "bloger, ijtimoiy tarmoqlarda ta’sirli shaxs", "инфлюенсер, блогер", "a person who affects what their online followers buy or think", "The influencer has two million followers.", 'B2'),
      w("biased", "adjective", "xolis boʻlmagan, bir tomonlama", "предвзятый", "unfairly supporting one side or opinion", "Some newspapers are clearly biased.", 'B2'),
      w("fake news", "noun", "yolgʻon xabarlar", "фейковые новости", "false stories presented as real news", "Always check the source to avoid fake news.", 'B2'),
      w("masterpiece", "noun", "shoh asar", "шедевр", "an excellent work of art, music or literature", "Navoi's Khamsa is a masterpiece of Turkic literature.", 'B2'),
      w("censorship", "noun", "senzura", "цензура", "controlling what can be published, broadcast or shown", "Censorship limits freedom of speech.", 'C1'),
      w("thought-provoking", "adjective", "oʻylashga undaydigan", "заставляющий задуматься", "making people think seriously about something", "It was a thought-provoking documentary.", 'C1'),
      w("mainstream", "adjective", "ommaviy, keng tarqalgan", "массовый, мейнстримный", "accepted by or popular with most people", "Mainstream media rarely cover this topic.", 'C1'),
    ],
  },
];
