namespace SpeakingCoach.Api.Services.Content;

// Reading mashqlari (A2–C1). Original matnlar — hech qayerdan ko'chirilmagan.
public static partial class PracticeLibrary
{
    private static readonly PracticeItem[] ReadingItems =
    [
        new("r-a2-1", "A2", new ComprehensionExercise(
            "A Saturday at the Bazaar",
            "Every Saturday morning, Dilnoza goes to the big bazaar near her house with her mother. They leave home at eight o'clock, because the market is quiet and the fruit is fresh early in the day.\n\nFirst, they buy bread from an old man who has a small shop at the gate. His bread is round and warm, and it smells wonderful. Then they walk to the fruit section. In summer there are melons, grapes and peaches everywhere. Dilnoza always chooses the melons, because her mother says she has a good nose for sweet ones.\n\nThe sellers are friendly, and many of them know Dilnoza's family. Sometimes they give her a free apple or a handful of dried apricots. Her mother likes to bargain, but she always does it with a smile.\n\nAt about ten o'clock, the bazaar becomes very crowded and noisy. By then their bags are heavy, so they take a taxi home and make tea.",
            [
                new("What is the text mainly about?", ["How to grow melons at home", "A mother and daughter's weekly trip to the market", "A new bread shop in the city", "Why taxis are expensive on Saturdays"], 1, "The first sentence says Dilnoza goes to the bazaar with her mother every Saturday, and the text describes this visit."),
                new("What time do Dilnoza and her mother leave home?", ["At seven o'clock", "At ten o'clock", "At twelve o'clock", "At eight o'clock"], 3, "Paragraph 1 says: \"They leave home at eight o'clock.\""),
                new("In paragraph 3, what does \"bargain\" mean?", ["To ask for a lower price", "To talk about the weather", "To carry heavy bags", "To give fruit for free"], 0, "Her mother talks with the sellers to pay less, and she does it politely, \"with a smile\"."),
                new("What can we guess about the family?", ["They own a fruit shop at the bazaar", "They only go to the bazaar in summer", "They have shopped at this bazaar for a long time", "They do not like the sellers"], 2, "Many sellers \"know Dilnoza's family\", which suggests the family has been coming for years."),
            ])),
        new("r-a2-2", "A2", new ComprehensionExercise(
            "Learning to Swim at Thirty",
            "When Kamola was a child, she lived far from the sea, and there was no swimming pool in her village. So she never learned to swim. For many years she felt a little embarrassed about it, especially on holidays with friends.\n\nLast spring, on her thirtieth birthday, she decided to change this. She found a sports centre with lessons for adults and paid for ten classes. The first lesson was difficult. The water felt cold, and she was afraid to put her face in it. The teacher, a patient woman called Rano, told her to relax and breathe slowly.\n\nAfter four lessons, Kamola could float on her back. After eight, she could swim across the pool without stopping. Now she goes to the pool twice a week before work. She says swimming helps her feel calm and sleep better. Next summer she wants to swim in the lake near her aunt's house.",
            [
                new("What is the main idea of the text?", ["A teacher opens a new swimming pool", "A village builds a sports centre", "An adult learns a skill she did not learn as a child", "A woman travels to the sea for her birthday"], 2, "The text tells how Kamola, who never learned to swim as a child, learned at thirty."),
                new("How many classes did Kamola pay for?", ["Ten", "Four", "Eight", "Twelve"], 0, "Paragraph 2 says she \"paid for ten classes\"."),
                new("In paragraph 1, what does \"embarrassed\" mean?", ["Feeling happy and proud", "Feeling very tired", "Feeling hungry", "Feeling a little ashamed or uncomfortable"], 3, "She felt bad about not swimming, \"especially on holidays with friends\", when others could see it."),
                new("What can we guess about Kamola now?", ["She is still afraid to put her face in the water", "She feels much more confident in the water", "She has stopped going to the pool", "She wants to become a swimming teacher"], 1, "She swims twice a week and plans to swim in a lake, so she is clearly no longer afraid."),
            ])),
        new("r-a2-3", "A2", new ComprehensionExercise(
            "Aziz's First Week at Work",
            "Aziz is twenty-two years old. Last Monday he started his first job at a small company that makes furniture. He works in the office and answers emails from customers.\n\nOn his first day he was very nervous. He woke up at six, ironed his shirt twice and arrived half an hour early. His manager, Mrs Karimova, showed him his desk and introduced him to the team. Everyone was kind, and one colleague, Bekzod, invited him to lunch.\n\nThe week was busy. Aziz learned how to use the company's computer program and how to write polite emails. On Wednesday he made a mistake and sent a price list to the wrong customer. He felt terrible, but his manager just said, \"Everyone makes mistakes in their first week. Check twice next time.\"\n\nOn Friday evening Aziz was tired but happy. He called his parents and told them all about his new colleagues.",
            [
                new("What is the text mainly about?", ["Aziz's experience in his first week at a new job", "How to make furniture", "A big argument between Aziz and his manager", "Aziz's plan to leave his job"], 0, "The text follows Aziz from \"Last Monday\" to \"Friday evening\" at his first job."),
                new("What mistake did Aziz make?", ["He arrived late on Monday", "He forgot to iron his shirt", "He sent a price list to the wrong customer", "He missed lunch with Bekzod"], 2, "Paragraph 3 says he \"sent a price list to the wrong customer\"."),
                new("In paragraph 2, what does \"nervous\" mean?", ["Angry", "Worried and a little afraid", "Bored", "Sleepy"], 1, "He woke up early, ironed his shirt twice and arrived early, which shows he was worried."),
                new("How did the manager probably feel about the mistake?", ["She wanted Aziz to leave the company", "She did not notice it", "She was very pleased about it", "She understood and was not very angry"], 3, "She calmly said, \"Everyone makes mistakes in their first week.\""),
            ])),
        new("r-a2-4", "A2", new ComprehensionExercise(
            "The Library Café",
            "In the centre of our town there is an old library. A few years ago it was very quiet, and not many people visited it. Then the town opened a small café on the ground floor, next to the children's books.\n\nNow the library is one of the busiest places in town. Students come in the afternoon to do their homework and drink hot chocolate. Older people read newspapers there in the morning. On Thursday evenings there is a book club, and anyone can join for free.\n\nThe café has one important rule: you must not put your cup on a library book. There are special tables for reading and different tables for eating.\n\nThe librarian, Mr Tursunov, is very pleased. He says that more people borrow books now than five years ago. \"People come for the coffee,\" he says with a smile, \"and they leave with a book.\"",
            [
                new("What is the main idea of the text?", ["The town closed its old library", "Students prefer coffee to books", "The library opened a new bookshop", "A café helped an old library become popular again"], 3, "The library was quiet until the café opened; \"now the library is one of the busiest places in town\"."),
                new("When does the book club meet?", ["On Monday mornings", "On Thursday evenings", "On Saturday afternoons", "Every day at lunchtime"], 1, "Paragraph 2 says: \"On Thursday evenings there is a book club.\""),
                new("In paragraph 4, what does \"borrow\" mean?", ["Buy something in a shop", "Write a book", "Take something and give it back later", "Throw something away"], 2, "People take library books home and return them later, which is what \"borrow\" means."),
                new("What does Mr Tursunov's last sentence suggest?", ["People who come for the café often become readers", "People only come to drink coffee", "He wants to close the café", "Coffee is more expensive than books"], 0, "He says people \"come for the coffee\" but \"leave with a book\"."),
            ])),
        new("r-a2-5", "A2", new ComprehensionExercise(
            "A Picnic in the Mountains",
            "Last Sunday, my friends and I went for a picnic in the mountains outside the city. We took a bus at seven in the morning, and the journey took about two hours.\n\nWhen we arrived, the air was cool and clean. We walked along a small river for an hour and found a perfect place under some tall trees. Farida put a big blanket on the grass, and Sardor made a small fire to make tea. We had bread, cheese, tomatoes, cucumbers and some cold chicken.\n\nAfter lunch, some of us played football, and others slept in the shade. In the afternoon the sky became dark, and it started to rain. We ran to a small café near the bus stop and waited there with bowls of hot soup.\n\nThe weather was not perfect, but everyone agreed it was a wonderful day. We want to go again next month.",
            [
                new("What is the text mainly about?", ["A football match in the city", "A day trip with friends to the mountains", "A cooking lesson by a river", "A long holiday in a mountain hotel"], 1, "The first sentence says the writer and friends \"went for a picnic in the mountains\"."),
                new("How long was the bus journey?", ["About two hours", "About one hour", "About three hours", "All day"], 0, "Paragraph 1 says \"the journey took about two hours\"."),
                new("In paragraph 3, what does \"in the shade\" mean?", ["In the river", "On the bus", "In a dark room", "In a place out of the sun"], 3, "They were under tall trees, so some friends slept where the sun did not reach them."),
                new("Why did they probably go to the café?", ["To buy a new blanket", "To watch football on TV", "To stay dry because of the rain", "Because they had no food"], 2, "They ran to the café right after \"it started to rain\"."),
            ])),
        new("r-b1-1", "B1", new ComprehensionExercise(
            "A Garden on the Roof",
            "When Malika moved into a flat on the top floor of a ten-storey building, she missed one thing more than anything else: her parents' garden. She had grown up surrounded by apple trees and vegetable beds, and the grey city views from her windows made her feel homesick.\n\nOne evening she noticed that the building's flat roof was completely empty. After talking to the building manager and her neighbours, she got permission to use part of it. She started with just six large pots of tomatoes, herbs and peppers. Some neighbours laughed and said nothing would survive the strong wind and the summer heat.\n\nThey were wrong. Malika put up a simple fence to protect the plants from the wind and watered them early every morning. By August, the tomatoes were so heavy that the branches almost touched the ground. Curious neighbours began to visit, and soon several of them wanted pots of their own.\n\nToday the roof has more than forty containers, a small bench and a shared tank that collects rainwater. Neighbours who had never spoken to each other now swap seeds and recipes. Malika says the vegetables are a nice bonus, but the real harvest is friendship.",
            [
                new("What is the text mainly about?", ["Why city flats are too small for families", "How to protect tomatoes from insects", "How a rooftop garden brought neighbours together", "A building manager who designs gardens"], 2, "The text describes how Malika's garden grew and how neighbours now \"swap seeds and recipes\"."),
                new("What did Malika do to protect the plants from the wind?", ["She moved them indoors", "She covered them with plastic", "She planted them in the ground", "She put up a simple fence"], 3, "Paragraph 3 says she \"put up a simple fence to protect the plants from the wind\"."),
                new("In paragraph 1, what does \"homesick\" mean?", ["Ill because of the bad city air", "Sad because she missed the place where she grew up", "Tired of living in a house", "Excited about living somewhere new"], 1, "The grey views made her miss her parents' garden, so she felt sad for her old home."),
                new("What can we infer about the neighbours before the garden existed?", ["Many of them did not know each other well", "They often shared recipes", "They all worked together on the roof", "They each had their own garden"], 0, "The text says some neighbours \"had never spoken to each other\" before the garden."),
            ])),
        new("r-b1-2", "B1", new ComprehensionExercise(
            "How the Bicycle Changed Everyday Life",
            "Today the bicycle seems like a simple machine, but when it became popular in the late nineteenth century, it changed daily life in surprising ways.\n\nEarly bicycles were difficult and even dangerous to ride. One famous model had a huge front wheel and a tiny back wheel, and riders often fell from a great height. In the 1880s, however, engineers designed the \"safety bicycle\", with two wheels of the same size and a chain that turned the back wheel. This design is very close to the bicycles we ride today.\n\nSuddenly, ordinary workers could travel much further than they could walk. People living in villages could reach factories and markets in nearby towns, and young people could meet friends from other places. Some historians even say the bicycle helped people find partners outside their own village.\n\nThe bicycle also gave women more freedom. They could travel alone, and many started to wear more practical clothes for riding. Cycling clubs appeared in many countries, and the demand for smooth roads grew, which later helped the first car drivers.\n\nSo the next time you see a bicycle, remember that this quiet machine once caused a small revolution.",
            [
                new("What is the main idea of the text?", ["The bicycle had a big effect on how people lived", "Early bicycles were too dangerous to use", "Cars are more useful than bicycles", "How to repair an old bicycle"], 0, "The first sentence says the bicycle \"changed daily life in surprising ways\", and the text gives examples."),
                new("What was special about the \"safety bicycle\"?", ["It had a huge front wheel", "It had no chain", "It had a small engine", "Its two wheels were the same size"], 3, "Paragraph 2 describes it as having \"two wheels of the same size and a chain\"."),
                new("In the last paragraph, what does \"revolution\" mean?", ["A wheel turning once", "A bicycle race", "A big change in the way people live", "A kind of road"], 2, "The text has shown how bicycles changed work, travel and freedom, so \"revolution\" means a big change."),
                new("What can we infer about travel before bicycles became popular?", ["Most people travelled by car", "Most ordinary workers could only go as far as they could walk", "Women travelled alone more often", "Roads were already smooth everywhere"], 1, "Paragraph 3 says that with bicycles, workers \"could travel much further than they could walk\"."),
            ])),
        new("r-b1-3", "B1", new ComprehensionExercise(
            "Saving Money with a Simple Notebook",
            "Jasur always wondered where his money went. He had a good salary, but by the end of every month his bank account was almost empty. He did not buy expensive things, so he could not understand the problem.\n\nHis older sister gave him some advice: \"For one month, write down everything you spend, even the smallest things.\" Jasur thought it was a boring idea, but he bought a small notebook and tried it.\n\nThe results surprised him. He spent almost a fifth of his money on taxis, because he often left home late and could not wait for the bus. He also bought coffee and snacks two or three times a day, and he was paying for three online services he had forgotten about.\n\nJasur did not want to live without any small pleasures, so he made a few realistic changes. He started getting up fifteen minutes earlier and took the bus to work. He cancelled two of the online services and brought a flask of tea from home. After three months, he had saved enough money for a short trip to Samarkand.\n\nNow Jasur recommends the notebook to all his friends. \"It is not about being mean with money,\" he says. \"It is about knowing where it goes.\"",
            [
                new("What is the main idea of the text?", ["Taxis are cheaper than buses", "How to get a better salary", "Why online services are dangerous", "Writing down his spending helped a man control his money"], 3, "After recording everything he spent, Jasur made changes and \"saved enough money for a short trip\"."),
                new("What did Jasur spend almost a fifth of his money on?", ["Coffee", "Online services", "Taxis", "Clothes"], 2, "Paragraph 3 says: \"He spent almost a fifth of his money on taxis.\""),
                new("In the last paragraph, what does \"mean with money\" mean?", ["Not wanting to spend or share money", "Very rich", "Careless with money", "Good at maths"], 0, "Jasur says the idea is not about refusing to spend, but about \"knowing where it goes\"."),
                new("Why did Jasur probably take so many taxis before?", ["The bus did not go to his office", "He did not manage his time well in the mornings", "He enjoyed talking to drivers", "Taxis were free for workers"], 1, "He took taxis because he \"often left home late\", and the solution was getting up earlier."),
            ])),
        new("r-b1-4", "B1", new ComprehensionExercise(
            "Why Teenagers Need More Sleep",
            "Many parents complain that their teenage children stay up late and are impossible to wake up in the morning. It is easy to call this laziness, but scientists say the real reason is biology.\n\nDuring the teenage years, the body's internal clock changes. The brain starts to release melatonin, the hormone that makes us feel sleepy, about two hours later than it does in children or adults. As a result, a fifteen-year-old may simply not feel tired until eleven o'clock or midnight. However, teenagers still need between eight and ten hours of sleep every night to stay healthy.\n\nWhen school starts early, many teenagers get only six or seven hours. Research shows that this lack of sleep can affect memory, mood and concentration. Tired students also find it harder to control their emotions and are more likely to get ill.\n\nSome schools have tried starting lessons later, at nine instead of eight. In several of these schools, attendance improved, and students said they felt more awake in class. Experts also give simple advice to families: keep phones out of the bedroom at night, and try to go to bed at the same time every day, even at weekends.",
            [
                new("What is the main idea of the text?", ["Teenagers are lazier than adults", "Teenagers' late sleeping is mostly caused by changes in their bodies", "Phones are the only reason teenagers sleep badly", "Schools should start at seven o'clock"], 1, "The text says the real reason \"is biology\", as the body's internal clock changes."),
                new("How many hours of sleep do teenagers need each night?", ["Six or seven", "Between five and six", "Between ten and twelve", "Between eight and ten"], 3, "Paragraph 2 says teenagers \"need between eight and ten hours of sleep every night\"."),
                new("In paragraph 3, what does \"lack of sleep\" mean?", ["Not having enough sleep", "Having too much sleep", "Very deep sleep", "A place to sleep"], 0, "It refers to teenagers who get \"only six or seven hours\" instead of eight to ten."),
                new("Why do experts probably suggest keeping phones out of the bedroom?", ["Phones are expensive", "Parents want to use them", "Phones can keep teenagers awake even later", "Phones make the room too cold"], 2, "The advice comes in a text about teenagers already falling asleep late, so phones would make this worse."),
            ])),
        new("r-b1-5", "B1", new ComprehensionExercise(
            "Caravanserais: Hotels of the Silk Road",
            "For hundreds of years, merchants travelled along the Silk Road between China and the Mediterranean, carrying silk, spices, paper and glass. The journey could take months, and the roads crossed deserts and mountains. Travellers needed safe places to rest, and so caravanserais appeared.\n\nA caravanserai was a kind of roadside inn. Most were built in a square shape with thick walls and one large gate, which was closed at night to keep out thieves. Inside there was an open courtyard where camels and horses could rest and drink. Around the courtyard were small rooms for travellers, as well as places to store goods.\n\nCaravanserais were usually built about a day's journey apart, roughly thirty or forty kilometres. This meant a caravan could leave one in the morning and reach the next before dark.\n\nBut these buildings were more than hotels. Merchants from different countries met there, exchanged news and did business. Languages, recipes, music and ideas travelled together with the goods.\n\nSome caravanserais still stand in Central Asia, Iran and Turkey today. A few have been restored and now serve as museums, restaurants or even hotels again.",
            [
                new("What is the text mainly about?", ["Silk was the only product sold on the Silk Road", "Camels travelled faster than horses", "Caravanserais were important places to rest and meet on the Silk Road", "Modern hotels copy the Silk Road style"], 2, "The text explains what caravanserais were, how they were built and why they mattered to travellers."),
                new("Why was the gate closed at night?", ["To keep out thieves", "To keep the camels warm", "To stop merchants from leaving", "To save water"], 0, "Paragraph 2 says the gate \"was closed at night to keep out thieves\"."),
                new("In the last paragraph, what does \"restored\" mean?", ["Destroyed", "Sold to a company", "Moved to another city", "Repaired so that it looks as it did before"], 3, "The old buildings were repaired and are now used again as museums, restaurants or hotels."),
                new("What can we infer from the fourth paragraph?", ["Merchants never spoke to each other", "Caravanserais helped different cultures influence each other", "Only one language was used on the Silk Road", "Music was not allowed in caravanserais"], 1, "It says \"languages, recipes, music and ideas travelled together with the goods\"."),
            ])),
        new("r-b2-1", "B2", new ComprehensionExercise(
            "The Quiet Comeback of Board Games",
            "A decade ago, many people predicted that video games and smartphones would make board games disappear. Instead, the opposite has happened. In cities around the world, board game cafés are opening, crowdfunding websites are full of new game designs, and sales have grown steadily for years. Some shops that once sold only a few classic titles now stock hundreds of games from small independent designers.\n\nPart of the explanation lies in the games themselves. Traditional family games often depended heavily on luck: you rolled the dice, moved your piece and hoped for the best. Many modern games, by contrast, reward planning, negotiation and cooperation. In some of them, players do not compete at all but work together against the game, trying to stop a disease from spreading or to escape from a sinking island before time runs out.\n\nHowever, the social side may be even more important. After a day spent staring at screens, many people are hungry for face-to-face contact. A board game offers a reason to gather around a table, put phones aside and share an experience that does not depend on a strong internet connection. Unlike watching a film together, it requires everyone to take part.\n\nTeachers have noticed the trend too. Some use games to practise maths, languages and problem-solving, arguing that students who would never volunteer an answer in class will happily explain their strategy during a game. A few teachers even design simple games of their own for their classes.\n\nOf course, board games are not replacing digital entertainment; many fans enjoy both. But their revival shows that, even in a highly connected age, people still value the simple pleasure of sitting together and playing.",
            [
                new("What is the main idea of the text?", ["Board games have become popular again, partly because people want real social contact", "Video games have almost completely disappeared", "Board games are now used mainly in schools", "Modern board games depend entirely on luck"], 0, "The text describes growing sales and argues that \"the social side may be even more important\"."),
                new("What is unusual about some modern board games?", ["Players must use a smartphone to play", "The winner is always decided by dice", "Players work together against the game instead of competing", "Only two people are allowed to play"], 2, "Paragraph 2 says \"players do not compete at all but work together against the game\"."),
                new("In the last paragraph, what does \"revival\" mean?", ["A fall in sales", "A return to popularity", "A new kind of screen", "A difficult rule"], 1, "The whole text describes board games becoming popular again after people expected them to disappear."),
                new("What does the writer suggest about shy students?", ["They never enjoy board games", "They prefer to study alone with a screen", "They are usually better at maths than other students", "They may communicate more easily during a game than in a normal lesson"], 3, "Students who \"would never volunteer an answer in class will happily explain their strategy during a game\"."),
            ])),
        new("r-b2-2", "B2", new ComprehensionExercise(
            "Life Without a Phone for a Day",
            "Most of us check our phones dozens of times a day, often without noticing. So what happens when the phone is suddenly gone? A growing number of studies have tried to answer this question, and the results are more complicated than you might expect.\n\nIn the first few hours, many people experience real discomfort. Participants in experiments report reaching for their pockets, imagining that they hear notifications and feeling anxious that they are missing something important. Psychologists have even invented a word for this fear of being without a phone: \"nomophobia\".\n\nYet the discomfort usually fades surprisingly quickly. After a day or two, people often describe a sense of relief. They notice more of their surroundings, have longer conversations and find it easier to concentrate on a single task. Some say that time seems to pass more slowly, in a pleasant way.\n\nOn the other hand, a completely phone-free life is unrealistic for most of us. Phones are how we pay for things, find our way around and stay in touch with family and colleagues. For this reason, many researchers argue that the goal should not be to abandon technology, but to use it more deliberately.\n\nTheir practical suggestions are simple: turn off non-essential notifications, keep the phone out of sight while working or eating, and choose certain times of day to check messages rather than responding to every alert immediately. Small changes like these, they say, can bring many of the benefits of a digital detox without the inconvenience of disappearing from the connected world.",
            [
                new("What is the main idea of the text?", ["Phones should be banned for everyone", "Nomophobia is a serious illness that needs medicine", "People rarely notice when their phone is missing", "Being without a phone is uncomfortable at first but can bring real benefits"], 3, "The text describes early \"discomfort\" followed by \"a sense of relief\" and other benefits."),
                new("How do people often feel after a day or two without their phone?", ["More anxious than before", "Relieved", "Extremely bored", "Angry with their friends"], 1, "Paragraph 3 says: \"After a day or two, people often describe a sense of relief.\""),
                new("In paragraph 4, what does \"deliberately\" mean?", ["By accident", "Very quickly", "Carefully and with a clear purpose", "Only rarely"], 2, "Researchers want people to make conscious choices about technology instead of using it automatically."),
                new("Why do researchers probably suggest checking messages at set times?", ["To reduce constant interruptions without losing contact", "Because phones break if they are used too often", "Because messages only arrive at certain times", "To save money on phone bills"], 0, "The advice aims to keep the benefits of a detox \"without disappearing from the connected world\"."),
            ])),
        new("r-b2-3", "B2", new ComprehensionExercise(
            "The Chocolate Bar Behind the Microwave",
            "Many important inventions were not planned; they happened because someone noticed something strange and asked why. One of the best examples sits in almost every kitchen today: the microwave oven.\n\nIn the 1940s, an American engineer named Percy Spencer was working with radar equipment. Radar used a device called a magnetron to produce microwaves, a type of energy used to detect aircraft. One day, while standing near an active magnetron, Spencer realised that a chocolate bar in his pocket had melted. Other people had probably noticed similar effects before, but Spencer was curious enough to investigate.\n\nHe tried placing popcorn kernels near the device, and they began to pop. Then, according to a well-known story, he tried an egg, which exploded in a colleague's face. It was clear that microwaves could heat food very quickly by making the water molecules inside it vibrate. Spencer and his company quickly realised the commercial potential of the discovery and applied for a patent.\n\nThe first commercial microwave ovens, however, were far from the compact machines we know. They were nearly as tall as a person, weighed hundreds of kilograms and were extremely expensive, so only restaurants, ships and railway companies bought them. It took about another twenty years for smaller, cheaper models to appear in ordinary homes. Even then, many people were suspicious of the new machines and worried, wrongly, that food cooked in them might be unsafe.\n\nToday microwave ovens are so common that few people think about where they came from. Yet the story is a useful reminder that curiosity can turn a small accident, like a ruined snack, into a technology used by millions of people every day.",
            [
                new("What is the main idea of the text?", ["Radar was originally invented to cook food", "A curious engineer turned a small accident into a useful invention", "Chocolate melts easily in warm pockets", "Microwave ovens have always been small and cheap"], 1, "The text shows how Spencer investigated a melted chocolate bar, which led to the microwave oven."),
                new("Who bought the first commercial microwave ovens?", ["Restaurants, ships and railway companies", "Ordinary families", "Schools and hospitals", "Chocolate factories"], 0, "Paragraph 4 says \"only restaurants, ships and railway companies bought them\"."),
                new("In paragraph 4, what does \"compact\" mean?", ["Very noisy", "Very expensive", "Old-fashioned", "Small and not taking up much space"], 3, "The first ovens are contrasted with today's machines: they were \"nearly as tall as a person\"."),
                new("What does the writer suggest about the other people who noticed similar effects?", ["They invented the microwave oven before Spencer", "They did not work with radar", "They did not investigate what had happened", "They were afraid of the magnetron"], 2, "The text says Spencer, unlike them, \"was curious enough to investigate\"."),
            ])),
        new("r-b2-4", "B2", new ComprehensionExercise(
            "Is a Four-Day Week the Future of Work?",
            "For more than a century, the five-day working week has been the standard in most countries. Recently, however, a number of companies have experimented with something that once sounded impossible: paying employees the same salary for working only four days.\n\nThe results of these trials have been encouraging. In many cases, companies reported that productivity stayed the same or even increased. Employees said they felt less stressed, slept better and had more time for family, exercise and hobbies. Because staff were happier, fewer of them left their jobs, which saved the companies the cost of recruiting and training replacements.\n\nHow is it possible to do the same work in less time? Supporters point out that a normal working day contains a lot of wasted time: long meetings, unnecessary emails and constant interruptions. When people know they have only four days, they tend to plan more carefully and cut out activities that add little value.\n\nNevertheless, the idea has its critics. A four-day week is much easier to organise in an office than in a hospital, a school or a shop that must stay open every day. Some employees also found that their four working days became longer and more intense, which partly cancelled out the benefit of the extra day off.\n\nFor now, the four-day week is unlikely to become universal overnight. But the experiments have encouraged many managers to ask a valuable question: are we measuring work by the hours people spend at their desks, or by what they actually achieve?",
            [
                new("What is the main idea of the text?", ["All companies have already moved to a four-day week", "Working fewer days always lowers productivity", "Four-day week trials show benefits, although the idea does not suit every job", "Hospitals are the best places to test shorter weeks"], 2, "The text describes \"encouraging\" results but also explains the critics' concerns."),
                new("Why did the companies save money on recruitment?", ["They paid lower salaries", "They stopped holding meetings", "They closed on Fridays", "Fewer employees left their jobs"], 3, "Paragraph 2 says \"fewer of them left their jobs, which saved the companies the cost of recruiting\"."),
                new("In paragraph 4, what does \"cancelled out\" mean?", ["Made something stronger", "Removed or balanced the effect of something", "Added something extra", "Moved something to a later date"], 1, "Longer, more intense days reduced the advantage of having an extra day off."),
                new("What does the final question suggest the writer believes?", ["Results matter more than the number of hours worked", "People should work longer hours", "Managers should watch employees more closely", "Offices should get rid of desks"], 0, "The writer contrasts \"hours people spend at their desks\" with \"what they actually achieve\"."),
            ])),
        new("r-b2-5", "B2", new ComprehensionExercise(
            "Why Cities Are Hotter Than the Countryside",
            "On a hot summer evening, the temperature in the centre of a large city can be several degrees higher than in the fields just outside it. Scientists call this the urban heat island effect, and as cities grow and summers become hotter, it is attracting more and more attention.\n\nThe main cause is the materials that cities are made of. Asphalt roads, concrete buildings and dark rooftops absorb large amounts of heat from the sun during the day and release it slowly at night. In the countryside, by contrast, plants and soil hold water, and when that water evaporates it cools the air, much as sweat cools our skin. In addition, cars, air conditioners and factories all produce extra heat, and tall buildings can block the wind that might otherwise carry it away.\n\nThe consequences are serious. Higher temperatures increase energy use, as people run air conditioners for longer. They also worsen air quality and can be dangerous for elderly people and young children, especially during heatwaves, when even the nights offer no relief. Hospitals often record more heat-related admissions during such periods, particularly among people who live alone.\n\nFortunately, there are practical solutions. Planting trees along streets provides shade and cools the surrounding air. Some cities are painting roofs white or light grey so that they reflect sunlight instead of absorbing it. Others are creating \"green roofs\" covered with plants, and replacing car parks with parks and fountains. Even a single line of trees along a busy road can lower the temperature that people actually feel by several degrees.\n\nNone of these measures can remove the problem entirely, but together they can make city life noticeably more comfortable and, in extreme heat, safer.",
            [
                new("What is the main idea of the text?", ["Cities are warmer than the countryside, but the effect can be reduced", "The countryside is becoming hotter than cities", "Air conditioners are the only solution to heat", "Trees make city streets more dangerous"], 0, "The text explains the causes of the urban heat island effect and then \"practical solutions\"."),
                new("Why are some cities painting roofs white or light grey?", ["To make buildings look modern", "To protect them from rain", "Because dark paint is expensive", "So that the roofs reflect sunlight"], 3, "Paragraph 4 says roofs are painted \"so that they reflect sunlight instead of absorbing it\"."),
                new("In paragraph 2, what does \"evaporates\" mean?", ["Freezes into ice", "Falls as rain", "Changes from liquid into gas", "Becomes dirty"], 2, "The water leaves the plants and soil as vapour and cools the air, \"much as sweat cools our skin\"."),
                new("Why would a city park probably be cooler than a car park next to it?", ["Parks are always shaded by tall buildings", "Its plants and soil hold water that cools the air", "Car parks get more wind", "Cars are not allowed near parks"], 1, "Paragraph 2 explains that plants and soil hold water which cools the air when it evaporates, unlike asphalt."),
            ])),
        new("r-c1-1", "C1", new ComprehensionExercise(
            "Too Many Jams on the Shelf",
            "Walk into a large supermarket in search of a jar of jam and you may be confronted with dozens of varieties: different fruits, sugar-free versions, organic brands and jars in every imaginable size. Conventional economic thinking assumes that more choice is always better, since it increases the likelihood that each shopper will find exactly what they want. Yet a substantial body of psychological research suggests that the relationship between choice and satisfaction is rather less straightforward.\n\nIn one frequently cited experiment, shoppers were offered samples from either a small or a large selection of jams. The larger display attracted more attention, but those who saw the smaller range were considerably more likely to actually make a purchase. The researchers concluded that an abundance of options can overwhelm people, making the decision feel so burdensome that they postpone it altogether. Notably, the jams were all of similar quality, so the difference could not be explained by the products themselves.\n\nEven when people do choose, an extensive range can undermine their contentment afterwards. With so many alternatives available, it is easy to imagine that one of the rejected options might have been better, and this nagging doubt diminishes the pleasure of the item actually chosen. Psychologists also distinguish between \"maximisers\", who feel compelled to find the best possible option, and \"satisficers\", who settle for one that is good enough. Intriguingly, maximisers often make objectively better decisions yet report feeling less happy with them.\n\nIt would be an oversimplification, however, to conclude that choice is inherently harmful. Later studies have found that the effect depends heavily on context: people who know exactly what they are looking for are rarely troubled by large selections, and well-organised displays that group options into clear categories appear to reduce the burden considerably. The lesson for everyday life may be modest but useful. For decisions that genuinely matter, careful comparison is worthwhile; for trivial ones, deliberately adopting the satisficer's mindset may save both time and a considerable amount of unnecessary regret.",
            [
                new("What is the main idea of the text?", ["Supermarkets should sell only one kind of jam", "Maximisers are generally happier than satisficers", "Economists have proved that choice is always harmful", "Having more options does not always lead to greater satisfaction"], 3, "The text argues that \"the relationship between choice and satisfaction is rather less straightforward\" than economists assume."),
                new("What happened in the jam experiment?", ["The larger display attracted less attention", "Nobody bought any jam at all", "Shoppers who saw fewer jams were more likely to buy one", "Shoppers mostly chose sugar-free jam"], 2, "Paragraph 2 says those who saw the smaller range \"were considerably more likely to actually make a purchase\"."),
                new("In paragraph 3, what does \"nagging doubt\" mean?", ["A persistent feeling of uncertainty", "A strong sense of confidence", "A loud complaint", "A sudden decision"], 0, "It describes the continuing worry that \"one of the rejected options might have been better\"."),
                new("For which decision would the writer most likely recommend a satisficer's mindset?", ["Choosing which university to attend", "Choosing a brand of toothpaste", "Choosing a house to buy", "Choosing a surgeon for an operation"], 1, "The writer advises the satisficer's mindset for \"trivial\" decisions and careful comparison for those that \"genuinely matter\"."),
            ])),
        new("r-c1-2", "C1", new ComprehensionExercise(
            "How Paper Travelled West Through Samarkand",
            "It is difficult to overstate the importance of paper. Before its arrival, scholars in western Asia and Europe wrote on papyrus, which was fragile and came mainly from Egypt, or on parchment, made from carefully prepared animal skins, which was durable but prohibitively expensive. A single large book could require the skins of an entire flock of sheep.\n\nPaper had been invented in China many centuries earlier, and for a long time the technique remained largely confined to East Asia. According to a widely repeated account, the knowledge reached Central Asia in the middle of the eighth century, when Chinese papermakers were taken prisoner after a battle near the Talas River and brought to Samarkand. Historians now treat this story with some caution, suspecting that the craft spread more gradually along trade routes. Whatever the precise route, Samarkand soon became renowned for its paper, which was smooth, pale and made largely from linen rags and plant fibres. Local craftsmen adapted the technique to the resources available to them, and travellers often praised their product for its quality.\n\nFrom Samarkand, papermaking spread to Baghdad, where a paper mill was reportedly established by the end of the eighth century, and then onwards to Damascus, Cairo and eventually Spain and Italy. The consequences were profound. Because paper was far cheaper than parchment, books became more affordable, libraries expanded and administrators could keep far more extensive records. Merchants benefited too, since contracts, letters of credit and accounts could now be written down cheaply and carried over long distances. The flourishing of science, mathematics and literature in cities such as Baghdad owed a great deal to this humble material.\n\nWhen we consider the technologies that transformed the circulation of knowledge, we tend to think first of the printing press or the internet. Yet neither would have had the same impact without the quiet revolution that preceded them, one that owes a considerable debt to the workshops of Samarkand. It is a fitting reminder that the most influential innovations are not always the most dramatic ones.",
            [
                new("What is the main idea of the text?", ["Paper was first invented in Samarkand", "The spread of papermaking through Samarkand had a major effect on learning", "Parchment was cheaper and more practical than paper", "The printing press mattered more than paper"], 1, "The text traces paper's route through Samarkand and says its consequences \"were profound\"."),
                new("What was Samarkand paper mainly made from?", ["Animal skins", "Papyrus from Egypt", "Silk and cotton", "Linen rags and plant fibres"], 3, "Paragraph 2 says it was \"made largely from linen rags and plant fibres\"."),
                new("In paragraph 1, what does \"prohibitively expensive\" mean?", ["So costly that most people could not afford it", "Only slightly more expensive than usual", "Cheap but low in quality", "Free for scholars"], 0, "Parchment was so costly that one book \"could require the skins of an entire flock of sheep\"."),
                new("What can be inferred about books before paper arrived?", ["Most ordinary families owned several of them", "Libraries were larger than they are today", "They were scarce because writing materials were fragile or costly", "Scholars hardly ever wrote anything down"], 2, "Papyrus was \"fragile\" and parchment \"prohibitively expensive\", and only with paper did books become \"more affordable\"."),
            ])),
        new("r-c1-3", "C1", new ComprehensionExercise(
            "The Great Breakfast Debate",
            "\"Breakfast is the most important meal of the day\" is one of those phrases so often repeated that it has come to sound like established fact. Yet among nutrition scientists, the question of whether breakfast genuinely matters has proved surprisingly contentious.\n\nFor decades, the case for breakfast rested largely on observational studies, which consistently found that people who ate breakfast tended to be slimmer and healthier than those who skipped it. The problem with such studies is that they reveal correlation rather than causation. Regular breakfast eaters may also be more likely to exercise, sleep well and avoid smoking; it is almost impossible to separate the effect of the meal from the lifestyle that accompanies it. Moreover, people who know they are being studied may report their eating habits inaccurately, often in ways that flatter them.\n\nWhen researchers turned to randomised controlled trials, in which participants are assigned to eat or skip breakfast, the picture became considerably murkier. Several trials found that skipping breakfast did not lead to weight gain, and some suggested that people who ate breakfast simply consumed more calories over the day. Others found small benefits for particular groups, but the effects were modest and not always consistent. Interestingly, part of the enthusiasm for breakfast may have commercial roots: cereal manufacturers have long had an obvious interest in promoting the morning meal.\n\nNone of this means that breakfast is harmful. For children, some evidence suggests that a nutritious breakfast can support concentration at school, and many adults find that eating in the morning helps them avoid unhealthy snacking later. Athletes and people with certain medical conditions may also have specific needs.\n\nThe most defensible conclusion, therefore, is a rather unexciting one: what matters is less the timing of a meal than the overall quality and quantity of what we eat. For most healthy adults, the decision to eat breakfast can reasonably be guided by appetite and routine rather than by a slogan.",
            [
                new("What is the main idea of the text?", ["Breakfast is harmful for most adults", "Cereal is the healthiest possible breakfast", "The evidence that breakfast is essential for everyone is weaker than often believed", "Children should avoid eating breakfast"], 2, "The text shows the question is \"surprisingly contentious\" and concludes that the timing of meals matters less than their quality."),
                new("What was the main weakness of the early observational studies?", ["They showed correlation but not causation", "They studied only athletes", "They were paid for by doctors", "They included too few adults"], 0, "Paragraph 2 says such studies \"reveal correlation rather than causation\"."),
                new("In paragraph 3, what does \"murkier\" mean?", ["Clearer and simpler", "More exciting", "More expensive", "Less clear and more confusing"], 3, "The trials produced mixed results that made the earlier simple picture harder to interpret."),
                new("Why does the writer mention cereal manufacturers?", ["To recommend a particular brand of cereal", "To suggest the popular belief may partly reflect business interests", "To prove that cereal causes weight gain", "To explain how cereal is produced"], 1, "The writer says the enthusiasm \"may have commercial roots\" because manufacturers benefit from promoting breakfast."),
            ])),
        new("r-c1-4", "C1", new ComprehensionExercise(
            "The True Price of a Cheap T-Shirt",
            "Clothing has never been cheaper. In many countries, a T-shirt can now be bought for less than the price of a sandwich, and fashion retailers introduce new collections not twice a year, as was once traditional, but almost every week. This model, commonly known as fast fashion, has made stylish clothing accessible to millions of people. Its hidden costs, however, are becoming increasingly difficult to ignore.\n\nThe environmental footprint of the industry is considerable. Growing conventional cotton requires vast quantities of water, while synthetic fabrics such as polyester are derived from oil and shed tiny plastic fibres every time they are washed, many of which end up in rivers and oceans. Because garments are designed to be fashionable for a single season, they are frequently discarded after only a handful of wears. A large proportion ends up in landfill or is burned, and only a small fraction of textiles is recycled into new clothing.\n\nThere is also a human dimension. Keeping prices low puts relentless pressure on the factories that produce the clothes, where workers may face long hours, low pay and unsafe conditions. Such realities are rarely visible to shoppers at the end of the supply chain, who see only an attractive price tag.\n\nEncouragingly, alternatives are gaining ground. Second-hand clothing, once associated with necessity rather than choice, has become fashionable in its own right, boosted by apps that allow people to resell garments with ease. Some brands now offer repair services or take back worn items for recycling, and a growing number of consumers are embracing the idea of a \"capsule wardrobe\": a small collection of versatile, durable pieces that can be combined in many ways.\n\nUltimately, the most sustainable garment is often the one already hanging in our wardrobe. Buying less, choosing well and wearing things for longer may not be glamorous advice, but it is arguably the most effective response to an industry built on constant novelty.",
            [
                new("What is the main idea of the text?", ["Fast fashion is cheap for shoppers but has significant hidden costs", "Cotton is always better for the environment than polyester", "Second-hand clothes are usually of poor quality", "Brands should release new collections more often"], 0, "The text states that fast fashion's \"hidden costs\" are \"becoming increasingly difficult to ignore\"."),
                new("What happens to polyester clothes when they are washed?", ["They shrink quickly", "They lose their colour", "They shed tiny plastic fibres", "They become stronger"], 2, "Paragraph 2 says synthetic fabrics \"shed tiny plastic fibres every time they are washed\"."),
                new("In paragraph 4, what does \"versatile\" mean?", ["Very expensive", "Useful in many different ways", "Easily damaged", "Suitable only for special occasions"], 1, "The pieces are described as ones \"that can be combined in many ways\"."),
                new("What does the writer imply about second-hand clothing in the past?", ["It was more fashionable than new clothing", "It was sold mostly through apps", "It was produced in the same factories as fast fashion", "People mainly bought it because they could not afford new clothes"], 3, "The text says it was \"once associated with necessity rather than choice\"."),
            ])),
        new("r-c1-5", "C1", new ComprehensionExercise(
            "Adult Language Learning: Beyond the Myths",
            "It is widely assumed that anyone who begins learning a foreign language after childhood is doomed to fall short. Children, the argument goes, absorb languages effortlessly, while adults struggle with grammar tables and never lose their accent. Like many popular beliefs, this one contains a grain of truth wrapped in a good deal of exaggeration.\n\nThe grain of truth concerns pronunciation. Research consistently indicates that people who start learning a language in early childhood are far more likely to sound like native speakers. There is also evidence that, after many years of immersion, early starters tend to reach higher levels of ultimate attainment in grammar. However, these advantages typically emerge only after a very long period of living in the language.\n\nWhat is often overlooked, however, is that adults typically learn faster, at least in the early stages. They bring a mature understanding of how language works, well-developed memory strategies and, frequently, a clear motivation, whether it is a job, a move abroad or simple curiosity. In classroom settings with limited hours, adults and teenagers often outpace young children, who benefit most from years of constant, natural exposure rather than a few lessons a week. Older learners can also make deliberate use of dictionaries, grammar explanations and recordings, tools that young children cannot yet exploit.\n\nMoreover, a native-like accent is rarely the goal that matters most. The ability to hold a conversation, read a newspaper or negotiate a contract depends on vocabulary, fluency and cultural awareness, all of which adults can develop to a very high level. Plenty of respected writers and scientists acquired their working language as adults and kept a noticeable accent throughout their lives, without it diminishing their achievements in the slightest.\n\nPerhaps the most damaging aspect of the myth is that it becomes self-fulfilling: adults who believe they are too old tend to give up at the first difficulty. The evidence suggests they would be better served by consistent practice, realistic expectations and a little patience with themselves.",
            [
                new("What is the main idea of the text?", ["Only children can learn a foreign language well", "A native-like accent is the most important goal", "Adults should not start a new language after thirty", "Adults can learn languages very successfully, even though children have some advantages"], 3, "The writer says the popular belief \"contains a grain of truth wrapped in a good deal of exaggeration\" and shows adults' strengths."),
                new("In which area do early starters clearly have an advantage?", ["Vocabulary", "Pronunciation", "Motivation", "Memory strategies"], 1, "Paragraph 2 says \"the grain of truth concerns pronunciation\"."),
                new("In the last paragraph, what does \"self-fulfilling\" mean?", ["Impossible to prove", "Personally satisfying", "Becoming true because people believe it", "Popular among teachers"], 2, "Adults who believe they are too old give up, so the belief itself causes the failure it predicts."),
                new("What would the writer most likely say to a forty-year-old beginner?", ["Practise regularly and do not give up because of your age", "Focus mainly on losing your accent", "Do not start unless you can live abroad for years", "Wait until your children can learn with you"], 0, "The writer recommends \"consistent practice, realistic expectations and a little patience\"."),
            ])),
    ];
}
