namespace SpeakingCoach.Api.Services.Content;

// Listening mashqlari (skript — brauzer ovoz chiqarib o'qiydi) (A2–C1). Original matnlar — hech qayerdan ko'chirilmagan.
public static partial class PracticeLibrary
{
    private static readonly PracticeItem[] ListeningItems =
    [
        new("l-a2-1", "A2", new ComprehensionExercise(
            "A Message from the Dentist",
            "Hello, this is a message for Nodira Aliyeva. My name is Madina, and I'm calling from the Smile Dental Clinic. You have an appointment with the dentist tomorrow at ten o'clock in the morning. Unfortunately, the dentist is ill today, and she cannot work tomorrow. We are very sorry. Can you come on Friday instead? We have free times at half past nine in the morning or at three in the afternoon. Please call us back today before six o'clock and tell us which time is better for you. Also, please remember to bring your new insurance card. Thank you, and have a nice day.",
            [
                new("Why is Madina calling?", ["To ask Nodira to pay a bill", "To change the time of an appointment", "To offer Nodira a job at the clinic", "To invite Nodira to a party"], 1, "She says the dentist cannot work tomorrow and asks, \"Can you come on Friday instead?\""),
                new("Why can't the dentist work tomorrow?", ["She is on holiday", "She has a meeting", "The clinic is closed for repairs", "She is ill"], 3, "Madina says, \"Unfortunately, the dentist is ill today, and she cannot work tomorrow.\""),
                new("Which times are free on Friday?", ["Half past nine or three in the afternoon", "Nine o'clock or two in the afternoon", "Ten o'clock or six in the evening", "Half past ten or four in the afternoon"], 0, "She says, \"We have free times at half past nine in the morning or at three in the afternoon.\""),
                new("What should Nodira bring?", ["Her passport", "A photo", "Her new insurance card", "Some money for parking"], 2, "Madina says, \"Please remember to bring your new insurance card.\""),
            ])),
        new("l-a2-2", "A2", new ComprehensionExercise(
            "Welcome to the Sports Centre",
            "Good morning, everyone, and welcome to the Green Park Sports Centre. Here is some information for today. The swimming pool is open until eight o'clock this evening, but it will be closed from twelve to one for cleaning. The yoga class for beginners is in room two at eleven o'clock. Please bring your own mat and a bottle of water. The gym is very busy today, so please do not use one machine for more than twenty minutes. The café on the first floor has a special offer. If you buy a sandwich, you get a free orange juice. Have a great day.",
            [
                new("What is the announcement mainly about?", ["The opening of a new swimming pool", "A yoga competition", "Information for visitors to a sports centre today", "Rules for people who work in the café"], 2, "The speaker says, \"Here is some information for today,\" and talks about the pool, a class, the gym and the café."),
                new("When is the swimming pool closed?", ["From twelve to one", "From eleven to twelve", "All afternoon", "After six o'clock"], 0, "The speaker says the pool \"will be closed from twelve to one for cleaning\"."),
                new("What should people bring to the yoga class?", ["A towel and a swimming cap", "A sandwich", "A friend", "Their own mat and a bottle of water"], 3, "The speaker says, \"Please bring your own mat and a bottle of water.\""),
                new("What do you get free if you buy a sandwich?", ["A cup of coffee", "An orange juice", "A bottle of water", "A piece of cake"], 1, "The speaker says, \"If you buy a sandwich, you get a free orange juice.\""),
            ])),
        new("l-a2-3", "A2", new ComprehensionExercise(
            "My Grandmother's Plov",
            "Every Friday, my whole family goes to my grandmother's house for lunch. She always cooks plov in a big black pot called a kazan. She starts cooking at nine in the morning. First, she fries the meat and the onions. Then she adds lots of yellow carrots. She always cuts them by hand, never with a machine. She says this is her secret. Last Friday she asked me to help her. I washed the rice three times in cold water. It was my first time, and I was a little slow. But Grandma was very patient with me. When the plov was ready, everyone said it was delicious. I felt really proud.",
            [
                new("What is the story mainly about?", ["Helping a grandmother cook a family meal", "Buying food at a market", "A cooking competition on television", "A new restaurant in town"], 0, "The speaker says, \"Last Friday she asked me to help her,\" and describes cooking plov together."),
                new("When does the family visit the grandmother?", ["Every Sunday", "Once a month", "Every Friday", "Only on holidays"], 2, "The speaker says, \"Every Friday, my whole family goes to my grandmother's house for lunch.\""),
                new("What does the grandmother say is her secret?", ["Using a lot of oil", "Cutting the carrots by hand", "Cooking very quickly", "Adding red carrots"], 1, "The speaker says she cuts the carrots \"by hand, never with a machine,\" and \"She says this is her secret.\""),
                new("What did the speaker do to help?", ["Fried the meat", "Cut the onions", "Bought the carrots", "Washed the rice"], 3, "The speaker says, \"I washed the rice three times in cold water.\""),
            ])),
        new("l-a2-4", "A2", new ComprehensionExercise(
            "Train Delay Announcement",
            "Attention, please. This is an announcement for passengers travelling to Samarkand. The fast train at a quarter past two is late today. There is a problem with the train, and engineers are working on it now. The new departure time is ten past three. The train will leave from platform four, not platform two. We are very sorry for the delay. Passengers with tickets for this train can get a free cup of tea or coffee at the station café. Please show your ticket to the staff there. For more information, please go to the information desk near the main entrance. Thank you for your patience.",
            [
                new("What is the main purpose of the announcement?", ["To sell tickets to Samarkand", "To announce a new station café", "To ask passengers to leave the station", "To tell passengers that a train is late"], 3, "The speaker says, \"The fast train at a quarter past two is late today.\""),
                new("What is the new departure time?", ["A quarter past two", "Ten past three", "Half past three", "Ten to three"], 1, "The speaker says, \"The new departure time is ten past three.\""),
                new("Which platform will the train leave from?", ["Platform two", "Platform one", "Platform four", "Platform three"], 2, "The speaker says, \"The train will leave from platform four, not platform two.\""),
                new("What can passengers get at the café?", ["A free cup of tea or coffee", "A free sandwich", "A cheaper ticket", "A free newspaper"], 0, "The speaker says passengers \"can get a free cup of tea or coffee at the station café\"."),
            ])),
        new("l-a2-5", "A2", new ComprehensionExercise(
            "A New Neighbour",
            "Last month a new family moved into the flat next to ours. At first I only saw them on the stairs. Then one evening there was a knock on our door. It was our new neighbour, a young woman called Laylo. She had a plate of warm cookies in her hands. She smiled and said she had made too many. We invited her in for tea. She told us she is a nurse and works at the hospital near the park. She has a little son. He is five years old. Now he plays with my younger brother almost every day. We are already good friends.",
            [
                new("What is the story about?", ["Moving to a new flat", "Meeting a friendly new neighbour", "Baking cookies for a party", "A visit to the hospital"], 1, "The speaker says, \"It was our new neighbour, a young woman called Laylo,\" and \"We are already good friends.\""),
                new("What did Laylo bring?", ["A plate of warm cookies", "A cake", "Some flowers", "A bottle of juice"], 0, "The speaker says, \"She had a plate of warm cookies in her hands.\""),
                new("What is Laylo's job?", ["She is a teacher", "She is a cook", "She is a doctor", "She is a nurse"], 3, "The speaker says, \"She told us she is a nurse and works at the hospital near the park.\""),
                new("How old is Laylo's son?", ["Four", "Six", "Five", "Seven"], 2, "The speaker says, \"She has a little son. He is five years old.\""),
            ])),
        new("l-b1-1", "B1", new ComprehensionExercise(
            "Radio Tip: Revising for Exams",
            "Good evening, and welcome back to Student Hour. Exams are coming soon, so tonight's tip is about revision. Many students read their notes again and again. It feels useful, but research shows it is not very effective. A better idea is to test yourself. Close your book and try to write down everything you remember. Then check what you missed. Another tip is to study in short blocks. Work for about twenty five minutes, then take a five minute break. Walk around and drink some water, but do not look at your phone. Finally, remember that sleep is not a waste of time. While you sleep, your brain stores the information you learned during the day. So please, do not stay up all night before an exam. That's all for today. Tomorrow we'll talk about how to stay calm in the exam room.",
            [
                new("What is the radio tip mainly about?", ["How to choose a university", "Why phones are bad for students", "Better ways to revise for exams", "How to take good notes in class"], 2, "The presenter says, \"Tonight's tip is about revision.\""),
                new("According to the speaker, what works better than reading notes again and again?", ["Studying all night", "Reading faster", "Studying with music", "Testing yourself"], 3, "The speaker says, \"A better idea is to test yourself.\""),
                new("How long should each study block be?", ["About five minutes", "About twenty-five minutes", "About one hour", "About two hours"], 1, "The speaker says, \"Work for about twenty five minutes, then take a five minute break.\""),
                new("What will tomorrow's programme be about?", ["How to stay calm in the exam room", "How to sleep well", "Healthy food for students", "How to choose a career"], 0, "The presenter says, \"Tomorrow we'll talk about how to stay calm in the exam room.\""),
            ])),
        new("l-b1-2", "B1", new ComprehensionExercise(
            "A Tour of the Crafts Museum",
            "Hello everyone, and welcome to the Museum of Traditional Crafts. My name is Otabek, and I'll be your guide this morning. Our tour will take about one hour. We'll start here on the ground floor, in the pottery room. You'll see bowls and plates that are more than three hundred years old. After that, we'll go upstairs to see the carpets and the silk scarves. Please don't touch anything, because many of the objects are very fragile. You are welcome to take photos, but please switch off the flash. At the end of the tour, there is a small workshop where a local artist will show you how to paint a ceramic bowl. You can even try it yourself. The museum shop is next to the exit. Okay, if everyone is ready, let's begin.",
            [
                new("What is the purpose of the talk?", ["To introduce a museum tour", "To sell carpets and scarves", "To explain how to become a guide", "To advertise a new art school"], 0, "Otabek says, \"I'll be your guide this morning,\" and explains the plan for the tour."),
                new("What will visitors see first?", ["The carpets", "The silk scarves", "The museum shop", "The pottery room"], 3, "The guide says, \"We'll start here on the ground floor, in the pottery room.\""),
                new("What are visitors asked not to do?", ["Take photos", "Talk during the tour", "Touch the objects", "Use the stairs"], 2, "The guide says, \"Please don't touch anything, because many of the objects are very fragile.\""),
                new("What happens at the end of the tour?", ["Visitors watch a short film", "An artist shows how to paint a bowl", "Visitors get a free scarf", "The guide sells tickets for another museum"], 1, "The guide says \"a local artist will show you how to paint a ceramic bowl\"."),
            ])),
        new("l-b1-3", "B1", new ComprehensionExercise(
            "A Voicemail from a Travel Agent",
            "Hi, this is Dilshod from Blue Sky Travel, calling for Sanjar Rahimov. I'm calling about your trip to Istanbul next month. I have some good news and some bad news. The bad news is that the hotel you chose is fully booked for your dates. I'm really sorry about that. The good news is that I found another hotel on the same street. It's a little bigger, and it has a swimming pool on the roof. The price is almost the same, only ten dollars more per night, and breakfast is included. I think it's a great option. But I need your answer by Thursday, because rooms are going quickly. Your flights are all confirmed, so you don't need to worry about them. Please call me back or send me an email. Thanks, and speak soon.",
            [
                new("Why is Dilshod calling?", ["To cancel Sanjar's flights", "To ask Sanjar to pay for breakfast", "To invite Sanjar to visit the travel agency", "To offer a different hotel for Sanjar's trip"], 3, "Dilshod says the first hotel is full and \"I found another hotel on the same street.\""),
                new("What is the problem with the first hotel?", ["It is too expensive", "It is closed for repairs", "It is fully booked", "It is far from the city centre"], 2, "Dilshod says, \"The hotel you chose is fully booked for your dates.\""),
                new("What is special about the new hotel?", ["It has a swimming pool on the roof", "It is much cheaper", "It is next to the airport", "It has a view of the sea"], 0, "Dilshod says, \"It's a little bigger, and it has a swimming pool on the roof.\""),
                new("When does Dilshod need an answer?", ["By tomorrow", "By Thursday", "By Friday", "By next month"], 1, "Dilshod says, \"I need your answer by Thursday, because rooms are going quickly.\""),
            ])),
        new("l-b1-4", "B1", new ComprehensionExercise(
            "Why I Started Running",
            "Two years ago, I couldn't run to the bus stop without losing my breath. I worked in an office all day, I ate a lot of fast food, and I felt tired all the time. Then my doctor told me that I needed to move more. I didn't like gyms, so I decided to try running. On my first day, I ran for only two minutes and then walked home. I felt a bit silly. But I kept going, three mornings a week. My friend Aziza joined me, and that helped a lot, because we didn't want to let each other down. After six months, I could run five kilometres without stopping. Last spring I finished my first half marathon. But the best part isn't the medal. It's that I sleep better and feel happier every day.",
            [
                new("What is the talk mainly about?", ["How to win a marathon", "How the speaker became a runner and how it helped", "Why gyms are better than running", "The speaker's problems at work"], 1, "The speaker describes going from losing breath at the bus stop to finishing \"my first half marathon\"."),
                new("Why did the speaker start running?", ["A friend needed a running partner", "The speaker wanted to win a medal", "The office started a running club", "The doctor said the speaker needed to move more"], 3, "The speaker says, \"My doctor told me that I needed to move more.\""),
                new("How often did the speaker run at first?", ["Three mornings a week", "Every day", "Once a week", "Two evenings a week"], 0, "The speaker says, \"I kept going, three mornings a week.\""),
                new("What does the speaker say is the best part?", ["Winning a medal", "Losing weight quickly", "Sleeping better and feeling happier", "Meeting new people"], 2, "The speaker says, \"The best part isn't the medal. It's that I sleep better and feel happier every day.\""),
            ])),
        new("l-b1-5", "B1", new ComprehensionExercise(
            "Community Clean-Up Day",
            "Hello, neighbours! This is a short announcement about this weekend. This Saturday we are organising a clean-up day in Navruz Park. We'll meet at the main gate at nine o'clock in the morning and finish at about one. We'll collect rubbish, paint the old benches and plant twenty new trees along the path. Gloves, bags and tools will be provided, so you only need to bring comfortable clothes and a hat, because it may be sunny. Children are very welcome, but they must come with an adult. After the work, there will be a free lunch for all volunteers. The local bakery has kindly offered bread and pastries. If it rains, the event will move to the following Saturday. We hope to see many of you there. Let's make our park beautiful together.",
            [
                new("What is the announcement mainly about?", ["The opening of a new bakery", "A tree-planting competition for children", "An invitation to help clean a local park", "A meeting about building a new park"], 2, "The speaker says, \"This Saturday we are organising a clean-up day in Navruz Park.\""),
                new("What time will people meet?", ["At nine o'clock", "At one o'clock", "At ten o'clock", "At eight o'clock"], 0, "The speaker says, \"We'll meet at the main gate at nine o'clock in the morning.\""),
                new("What should volunteers bring?", ["Gloves and bags", "Their own tools", "Bread and pastries", "Comfortable clothes and a hat"], 3, "The speaker says, \"You only need to bring comfortable clothes and a hat.\""),
                new("What will happen if it rains?", ["The event will take place indoors", "The event will move to the following Saturday", "The event will be cancelled", "The event will start later in the day"], 1, "The speaker says, \"If it rains, the event will move to the following Saturday.\""),
            ])),
        new("l-b2-1", "B2", new ComprehensionExercise(
            "Podcast: Life Inside a Beehive",
            "Welcome to Wild Minds, the podcast about the surprising lives of animals. Today we're looking at honeybees, and trust me, they're far more organised than most offices. A single hive can contain tens of thousands of bees, but only one of them is the queen. Her main job is to lay eggs, sometimes well over a thousand in a single day. Almost all the other bees are female workers, and what they do depends on their age. Young workers stay inside, cleaning cells and feeding the larvae. Older ones become foragers, flying out to collect nectar and pollen. Now here's my favourite part. When a forager finds a good patch of flowers, she returns to the hive and performs what scientists call the waggle dance. The angle of her dance shows the direction of the flowers compared to the sun, and the length of the dance tells the others how far away they are. It's essentially a map made of movement. After the break, we'll talk to a beekeeper about why bee numbers have been falling, and what gardeners can do to help.",
            [
                new("What is the podcast episode mainly about?", ["How honeybees organise their work and share information", "How to become a beekeeper", "Why honey is good for your health", "The dangers of bee stings"], 0, "The host says \"they're far more organised than most offices\" and describes their jobs and the waggle dance."),
                new("What do young worker bees do?", ["Collect nectar and pollen", "Lay eggs", "Clean cells and feed the larvae", "Guard the entrance of the hive"], 2, "The host says, \"Young workers stay inside, cleaning cells and feeding the larvae.\""),
                new("What does the length of the waggle dance show?", ["The direction of the sun", "How far away the flowers are", "How many flowers there are", "Which bee found the flowers"], 1, "The host says \"the length of the dance tells the others how far away they are\"."),
                new("What will happen after the break?", ["The host will read a report on queen bees", "Listeners will take part in a quiz", "The host will talk about wasps", "The host will talk to a beekeeper"], 3, "The host says, \"After the break, we'll talk to a beekeeper about why bee numbers have been falling.\""),
            ])),
        new("l-b2-2", "B2", new ComprehensionExercise(
            "Budgeting Tips for Students",
            "Hi everyone, thanks for coming to this short session on managing money at university. I know budgeting sounds boring, but trust me, it's much less boring than running out of money in the middle of the month. So, first things first. As soon as your grant or wages arrive, move a small amount into a separate savings account. Even a tenth makes a real difference. Treat that money as if it doesn't exist. Next, look at your fixed costs, things like rent, transport and your phone. These are the same every month, so take them away first. What's left is what you can actually spend on food, going out and everything else. Divide that by four, and you've got a weekly limit. Many students I talk to say their biggest problem isn't rent. It's small daily spending, like coffee on the way to lectures or ordering food late at night. So try cooking in batches on Sundays. It's cheaper and healthier. And finally, don't be embarrassed to use student discounts. Always ask. You'd be amazed how many shops, cinemas and museums offer them.",
            [
                new("What is the session mainly about?", ["How to find a part-time job", "Why students should never go out", "How to open a bank account online", "Practical advice on managing money as a student"], 3, "The speaker welcomes everyone to \"this short session on managing money at university\"."),
                new("What should students do as soon as their money arrives?", ["Pay for a month of food", "Move a small amount into savings", "Buy a monthly transport pass", "Pay their rent for the whole year"], 1, "The speaker says, \"As soon as your grant or wages arrive, move a small amount into a separate savings account.\""),
                new("According to the speaker, what is many students' biggest problem?", ["Paying rent", "Buying textbooks", "Small daily spending", "Phone bills"], 2, "The speaker says, \"Their biggest problem isn't rent. It's small daily spending.\""),
                new("Why does the speaker suggest cooking in batches on Sundays?", ["It is cheaper and healthier", "It saves time for studying", "Friends can eat together", "Shops are closed on Sundays"], 0, "The speaker says, \"Try cooking in batches on Sundays. It's cheaper and healthier.\""),
            ])),
        new("l-b2-3", "B2", new ComprehensionExercise(
            "The Long Road to the Zip",
            "Here's a question for you. What do jackets, bags and tents all have in common? The zip, of course. It's so ordinary that we never think about it. But it took inventors several decades to get it right. In the eighteen nineties, an American inventor called Whitcomb Judson showed a device for fastening shoes. It used hooks and eyes, and it was clever, but it often got stuck or came open by itself. People weren't impressed. Then, in nineteen thirteen, a Swedish engineer working in America, Gideon Sundback, designed a much better version. Instead of hooks, it had small teeth that locked together neatly, and it was far more reliable. Even so, the invention was slow to catch on. At first, it was mainly used for boots and tobacco pouches. The name zipper actually came from a company that made rubber boots, because of the sound the fastener made. It was only in the nineteen thirties, when fashion designers began putting zips into trousers and children's clothes, that the zip truly became part of everyday life.",
            [
                new("What is the talk mainly about?", ["Judson's device was an immediate success", "The zip took a long time to develop and become popular", "The zip was first designed for trousers", "Rubber boots were invented in Sweden"], 1, "The speaker says \"it took inventors several decades to get it right\" and that it \"was slow to catch on\"."),
                new("What was the problem with Judson's device?", ["It often got stuck or came open by itself", "It was too expensive to make", "It was too heavy to wear", "It only worked on bags"], 0, "The speaker says \"it often got stuck or came open by itself\"."),
                new("Where did the name zipper come from?", ["A famous fashion designer", "The inventor's surname", "A Swedish word for teeth", "A company that made rubber boots"], 3, "The speaker says, \"The name zipper actually came from a company that made rubber boots.\""),
                new("When did the zip truly become part of everyday life?", ["In the eighteen nineties", "In nineteen thirteen", "In the nineteen thirties", "In the nineteen fifties"], 2, "The speaker says \"it was only in the nineteen thirties\" that the zip \"truly became part of everyday life\"."),
            ])),
        new("l-b2-4", "B2", new ComprehensionExercise(
            "A Morning Walk Through Old Bukhara",
            "Good morning, and welcome to Bukhara. Before we set off, let me explain today's route. We're going to walk for about two and a half hours, so I hope you're wearing comfortable shoes. We'll begin at Lyabi Hauz, the old pond surrounded by mulberry trees. For centuries it was the social heart of this neighbourhood, a place where people came to drink tea, chat and escape the heat. From there, we'll walk through the trading domes. These covered markets were built so that merchants could do business protected from the sun, and you can still buy spices, knives and embroidered cloth there today. Then we'll see the Kalyan Minaret. It's almost fifty metres tall, and it has been standing for nearly nine hundred years. Many travellers say the square beside it is the most beautiful place in the city. Please drink plenty of water, because it gets very hot here by midday. And one last thing. Bargaining is normal in the markets, but please do it with a smile. Right, follow me.",
            [
                new("What is the guide mainly doing?", ["Giving a history lecture about China", "Selling souvenirs to tourists", "Explaining the route of a walking tour", "Announcing that a museum is closed"], 2, "The guide says, \"Before we set off, let me explain today's route.\""),
                new("What was Lyabi Hauz in the past?", ["A covered market", "A school for merchants", "A place to keep camels", "A place where people met to drink tea and chat"], 3, "The guide says it was \"the social heart of this neighbourhood, a place where people came to drink tea, chat and escape the heat\"."),
                new("Why were the trading domes built?", ["To store water", "To protect merchants from the sun", "To keep animals safe", "To hold festivals"], 1, "The guide says they \"were built so that merchants could do business protected from the sun\"."),
                new("What does the guide say about bargaining?", ["It is normal but should be done with a smile", "It is not allowed in the markets", "Only the guide should do it", "It is considered rude in Bukhara"], 0, "The guide says, \"Bargaining is normal in the markets, but please do it with a smile.\""),
            ])),
        new("l-b2-5", "B2", new ComprehensionExercise(
            "A Manager's Advice on Remote Work",
            "Hello, and thanks for tuning in to Work Smart. A listener asked me what I've learned from managing a team that works almost entirely from home. So here are my three lessons. The first is about boundaries. When your office is also your kitchen, work can easily take over your whole day. I encourage my team to have a clear finishing time and, if possible, a separate space for work, even if it's just a small desk in a corner. The second lesson is about communication. In an office, you notice when a colleague looks stressed. Online, you don't. So I have a short video call with each person every week, and it's not about tasks. It's simply to ask how they're doing. The third lesson surprised me. People who work from home often feel they have to prove they're busy, so they answer messages instantly, even late at night. I tell my team clearly that I judge results, not reply times. Since I started saying that, people seem calmer, and honestly, the quality of their work has improved.",
            [
                new("What is the speaker mainly talking about?", ["Lessons from managing a team that works from home", "How to find a job you can do from home", "Why offices are better than working from home", "How to set up video call software"], 0, "The speaker shares \"what I've learned from managing a team that works almost entirely from home\"."),
                new("What does the speaker encourage to keep work and home separate?", ["Working at the kitchen table", "Answering messages late at night", "Taking long lunch breaks", "A clear finishing time and a separate work space"], 3, "The speaker says, \"I encourage my team to have a clear finishing time and, if possible, a separate space for work.\""),
                new("What is the purpose of the weekly video call?", ["To check tasks and deadlines", "To train new staff", "To ask how each person is doing", "To plan team parties"], 2, "The speaker says the call is \"not about tasks. It's simply to ask how they're doing.\""),
                new("What does the speaker say they judge their team on?", ["How quickly people answer messages", "Results, not reply times", "How many hours people work", "How tidy their desks are"], 1, "The speaker says, \"I tell my team clearly that I judge results, not reply times.\""),
            ])),
        new("l-c1-1", "C1", new ComprehensionExercise(
            "Podcast: Why Habits Stick",
            "Welcome back to The Curious Mind. Today we're exploring a question that has probably frustrated every single one of you at some point. Why is it so hard to build good habits, and so annoyingly easy to keep bad ones? Researchers who study behaviour describe a habit as a kind of loop. There's a cue, something in your environment that triggers the behaviour. There's the routine itself. And there's a reward, which is what persuades your brain that the whole thing is worth repeating. The crucial point is that once a habit is established, it runs largely on autopilot. That's wonderful when the habit is brushing your teeth, and rather less wonderful when it's reaching for your phone the moment you feel bored. Contrary to the popular claim that it takes exactly twenty one days to form a habit, the research suggests the timeframe varies enormously, from a few weeks to the better part of a year, depending on the person and the behaviour. Later in the episode, I'll be speaking to a psychologist who argues that willpower is overrated, and that the smartest strategy is to redesign your surroundings so that the good choice becomes the easy one. Stay with us.",
            [
                new("What is the episode mainly about?", ["The history of the toothbrush", "Why willpower is the key to success", "How to use your phone less at work", "How habits work and why they are hard to change"], 3, "The host asks, \"Why is it so hard to build good habits, and so annoyingly easy to keep bad ones?\""),
                new("According to the host, what is the role of the reward?", ["It triggers the behaviour in the first place", "It replaces the routine", "It persuades the brain that the behaviour is worth repeating", "It makes the habit disappear"], 2, "The host says the reward \"is what persuades your brain that the whole thing is worth repeating\"."),
                new("What does research say about how long it takes to form a habit?", ["It varies greatly depending on the person and the behaviour", "It always takes exactly twenty-one days", "It takes at least two years", "It takes only a few days"], 0, "The host says \"the timeframe varies enormously\", \"depending on the person and the behaviour\"."),
                new("What does the guest psychologist argue?", ["Willpower is the most important factor", "It is smarter to redesign your surroundings than to rely on willpower", "Bad habits can never really be changed", "Rewards should be avoided completely"], 1, "The host says the psychologist \"argues that willpower is overrated\" and recommends redesigning \"your surroundings\"."),
            ])),
        new("l-c1-2", "C1", new ComprehensionExercise(
            "Lecture: Why Great Cities Grew Beside Rivers",
            "Good afternoon. In today's lecture, I want to consider a pattern so familiar that we rarely question it. If you look at a map of the world's great historic cities, a remarkable number of them sit on the banks of a river. Why should that be? The obvious answer is drinking water, but that's only the beginning. Rivers deposit fertile soil when they flood, which allowed early farmers to produce a surplus of food. And a surplus, crucially, is what frees some people from farming altogether, so they can become craftsmen, traders and officials. In other words, city dwellers. Rivers were also the motorways of the ancient world. Moving heavy goods by boat was vastly cheaper and faster than hauling them overland, so places where routes met, or where a river could easily be crossed, tended to flourish as markets. Here in Central Asia, the oasis cities along the Zarafshan depended on careful irrigation for their very existence. That said, rivers were a mixed blessing. The same floods that enriched the soil could sweep away homes, and standing water brought disease. So next week, we'll look at how early engineers tried to control rivers, with varying degrees of success.",
            [
                new("What is the lecture mainly about?", ["How modern motorways are planned", "Why so many historic cities developed beside rivers", "The causes of floods in Central Asia", "Why people are leaving farms today"], 1, "The lecturer notes that many great cities \"sit on the banks of a river\" and asks, \"Why should that be?\""),
                new("Why, according to the lecturer, was a food surplus important?", ["It made rivers flood more often", "It was sold to other continents", "It made boats cheaper to build", "It allowed some people to do jobs other than farming"], 3, "The lecturer says a surplus \"is what frees some people from farming altogether\"."),
                new("What does the lecturer compare rivers to?", ["The motorways of the ancient world", "The walls of a city", "Modern markets", "A map of the world"], 0, "The lecturer says, \"Rivers were also the motorways of the ancient world.\""),
                new("What will next week's lecture be about?", ["The history of boat building", "Diseases in modern cities", "How early engineers tried to control rivers", "Farming in the desert"], 2, "The lecturer says, \"Next week, we'll look at how early engineers tried to control rivers.\""),
            ])),
        new("l-c1-3", "C1", new ComprehensionExercise(
            "Radio Essay: In Praise of Boredom",
            "When did you last do absolutely nothing? I don't mean scrolling through your phone while waiting for a bus. I mean genuinely sitting with no entertainment at all. For many of us, the honest answer is that we can't remember. We've become remarkably efficient at eliminating boredom, and I want to suggest tonight that this may come at a hidden cost. Boredom, after all, is uncomfortable for a reason. It's a signal that our current situation isn't satisfying, a nudge to go and find something more meaningful to do. When we instantly silence that signal with a screen, we never discover where it might have led. There's also intriguing evidence linking boredom to creativity. In one study, participants who first completed a deliberately tedious task, copying numbers out of a phone book, later came up with more imaginative ideas than those who hadn't. The theory is that a bored mind starts to wander, and a wandering mind is where unexpected connections are made. I'm not suggesting we should seek out misery. But perhaps, the next time you're standing in a queue, you might resist the urge to reach for your pocket, and simply see where your thoughts take you.",
            [
                new("What is the speaker's main message?", ["Phones should be banned in public places", "Boredom is usually a sign of illness", "Boredom can be useful, so we should not always avoid it", "Queues in modern cities are getting longer"], 2, "The speaker suggests that \"eliminating boredom\" \"may come at a hidden cost\"."),
                new("According to the speaker, what is boredom a signal of?", ["That our current situation is not satisfying", "That we need more sleep", "That we are hungry", "That we are working too hard"], 0, "The speaker says, \"It's a signal that our current situation isn't satisfying.\""),
                new("What task did participants in the study do first?", ["They read a long novel", "They played a video game", "They sat in silence for an hour", "They copied numbers out of a phone book"], 3, "The speaker describes \"a deliberately tedious task, copying numbers out of a phone book\"."),
                new("What does the speaker suggest doing in a queue?", ["Reading the news", "Resisting the phone and letting your thoughts wander", "Calling a friend", "Planning the rest of your day"], 1, "The speaker suggests you \"resist the urge to reach for your pocket, and simply see where your thoughts take you\"."),
            ])),
        new("l-c1-4", "C1", new ComprehensionExercise(
            "Radio Interview: The Chef Who Wastes Nothing",
            "Good evening, and welcome to Kitchen Table. My guest tonight runs a small restaurant with an unusual promise. Nothing that comes into her kitchen goes into the bin. Not the carrot tops, not the stale bread, not even the coffee grounds. Now, you might assume this is simply a clever marketing idea, but when I visited her last month, I was genuinely struck by how seriously she takes it. Vegetable peelings become stock. Yesterday's bread is turned into a crisp crumb for salads or a rather wonderful dessert. Fruit that's past its best ends up in jams and drinks, and whatever truly can't be eaten is composted for the farm that supplies her vegetables. She tells me the approach began out of necessity rather than principle. When she opened, money was so tight that she simply couldn't afford to throw anything away. Only later did she realise how much food restaurants typically waste, and how much flavour was hiding in the parts most cooks discard. Tonight she'll share some of her techniques, and she's also going to challenge us, the home cooks, to rethink what we consider rubbish. So if you've got a notebook handy, I'd suggest keeping it close.",
            [
                new("What is the presenter mainly doing?", ["Introducing a chef whose restaurant avoids wasting food", "Reviewing an expensive restaurant", "Explaining how to grow vegetables on a farm", "Warning listeners about unhealthy coffee"], 0, "The presenter says the guest's promise is that \"nothing that comes into her kitchen goes into the bin\"."),
                new("What happens to yesterday's bread?", ["It is thrown away", "It is given to the farm", "It becomes a crumb for salads or a dessert", "It is used to make stock"], 2, "The presenter says, \"Yesterday's bread is turned into a crisp crumb for salads or a rather wonderful dessert.\""),
                new("Why did the chef first start avoiding waste?", ["She wanted good publicity", "She could not afford to throw anything away", "A customer asked her to", "A cooking school taught her to"], 1, "The presenter says \"money was so tight that she simply couldn't afford to throw anything away\"."),
                new("What will the chef challenge listeners to do?", ["Open their own restaurants", "Stop eating bread", "Visit her farm", "Rethink what they consider rubbish"], 3, "The presenter says she will \"challenge us, the home cooks, to rethink what we consider rubbish\"."),
            ])),
        new("l-c1-5", "C1", new ComprehensionExercise(
            "Talk: Losing the Night Sky",
            "Thank you all for coming. I'd like to begin with a simple question. When did you last see the Milky Way? If you live in a city, the answer may well be never. Astronomers estimate that a large share of the world's population now lives under skies so brightened by artificial light that our own galaxy is effectively invisible. This is what we call light pollution, and unlike many environmental problems, it's remarkably easy to overlook, precisely because it's the absence of something. Yet its effects reach far beyond disappointed stargazers. Migrating birds, which navigate partly by the stars, can become disoriented by brightly lit buildings. Newly hatched sea turtles, which instinctively head towards the brightest horizon, may crawl inland towards streetlights instead of towards the sea. And in humans, bright light late at night can disrupt the body clock and interfere with sleep. The encouraging part is that, unlike most forms of pollution, this one can be reversed almost instantly. Shielding streetlights so they point downwards, choosing warmer colours and simply switching off lights that nobody needs can make a dramatic difference. Several towns have already been recognised for protecting their dark skies, and visitors now travel specifically to see them.",
            [
                new("What is the talk mainly about?", ["How to become an astronomer", "Why cities need more streetlights", "The migration routes of sea turtles", "The effects of light pollution and how to reduce it"], 3, "The speaker introduces \"what we call light pollution\", describes its effects and then its solutions."),
                new("Why, according to the speaker, is light pollution easy to overlook?", ["Because it only happens in summer", "Because it is the absence of something", "Because it only affects birds", "Because it is very rare"], 1, "The speaker says it is easy to overlook \"precisely because it's the absence of something\"."),
                new("What problem can newly hatched sea turtles face?", ["They cannot see the moon", "They hatch too early in the year", "They may crawl towards streetlights instead of the sea", "They are attacked by migrating birds"], 2, "The speaker says they \"may crawl inland towards streetlights instead of towards the sea\"."),
                new("Which solution does the speaker mention?", ["Shielding streetlights so they point downwards", "Building taller buildings", "Using brighter white lights", "Keeping all lights on through the night"], 0, "The speaker mentions \"shielding streetlights so they point downwards\" as a solution."),
            ])),
    ];
}
