namespace SpeakingCoach.Api.Services.Content;

// Listening mashqlari (skript — brauzer ovoz chiqarib o'qiydi) (A2–C1). Original matnlar — hech qayerdan ko'chirilmagan.
public static partial class PracticeLibrary
{
    private static readonly PracticeItem[] ListeningItems =
    [
        new("l-a2-1", "A2", new ComprehensionExercise(
            "A Message from the Dentist",
            "Hello, this is a message for Nodira Aliyeva. My name is Madina, and I'm calling from the Smile Dental Clinic. You have an appointment with the dentist tomorrow at ten o'clock in the morning. Unfortunately, the dentist is ill today, and she cannot work tomorrow. We are very sorry. Can you come on Friday instead? We have free times at half past nine in the morning or at three in the afternoon. Please call us back today before six o'clock and tell us which time is better for you. Also, please remember to bring your new insurance card. Thank you, and have a nice day.",
            [
                new("Why is Madina calling?", ["To ask Nodira to pay a bill", "To change the time of an appointment", "To offer Nodira a job at the clinic", "To invite Nodira to a party"], 1, "She says the dentist cannot work tomorrow and asks, \"Can you come on Friday instead?\""),
                new("Why can't the dentist work tomorrow?", ["She is on holiday", "She has a meeting", "The clinic is closed for repairs", "She is ill"], 3, "Madina says, \"Unfortunately, the dentist is ill today, and she cannot work tomorrow.\""),
                new("Which times are free on Friday?", ["Half past nine or three in the afternoon", "Nine o'clock or two in the afternoon", "Ten o'clock or six in the evening", "Half past ten or four in the afternoon"], 0, "She says, \"We have free times at half past nine in the morning or at three in the afternoon.\""),
                new("What should Nodira bring?", ["Her passport", "A photo", "Her new insurance card", "Some money for parking"], 2, "Madina says, \"Please remember to bring your new insurance card.\""),
            ])),
        new("l-a2-2", "A2", new ComprehensionExercise(
            "Welcome to the Sports Centre",
            "Good morning, everyone, and welcome to the Green Park Sports Centre. Here is some information for today. The swimming pool is open until eight o'clock this evening, but it will be closed from twelve to one for cleaning. The yoga class for beginners is in room two at eleven o'clock. Please bring your own mat and a bottle of water. The gym is very busy today, so please do not use one machine for more than twenty minutes. The café on the first floor has a special offer. If you buy a sandwich, you get a free orange juice. Have a great day.",
            [
                new("What is the announcement mainly about?", ["The opening of a new swimming pool", "A yoga competition", "Information for visitors to a sports centre today", "Rules for people who work in the café"], 2, "The speaker says, \"Here is some information for today,\" and talks about the pool, a class, the gym and the café."),
                new("When is the swimming pool closed?", ["From twelve to one", "From eleven to twelve", "All afternoon", "After six o'clock"], 0, "The speaker says the pool \"will be closed from twelve to one for cleaning\"."),
                new("What should people bring to the yoga class?", ["A towel and a swimming cap", "A sandwich", "A friend", "Their own mat and a bottle of water"], 3, "The speaker says, \"Please bring your own mat and a bottle of water.\""),
                new("What do you get free if you buy a sandwich?", ["A cup of coffee", "An orange juice", "A bottle of water", "A piece of cake"], 1, "The speaker says, \"If you buy a sandwich, you get a free orange juice.\""),
            ])),
        new("l-a2-3", "A2", new ComprehensionExercise(
            "My Grandmother's Plov",
            "Every Friday, my whole family goes to my grandmother's house for lunch. She always cooks plov in a big black pot called a kazan. She starts cooking at nine in the morning. First, she fries the meat and the onions. Then she adds lots of yellow carrots. She always cuts them by hand, never with a machine. She says this is her secret. Last Friday she asked me to help her. I washed the rice three times in cold water. It was my first time, and I was a little slow. But Grandma was very patient with me. When the plov was ready, everyone said it was delicious. I felt really proud.",
            [
                new("What is the story mainly about?", ["Helping a grandmother cook a family meal", "Buying food at a market", "A cooking competition on television", "A new restaurant in town"], 0, "The speaker says, \"Last Friday she asked me to help her,\" and describes cooking plov together."),
                new("When does the family visit the grandmother?", ["Every Sunday", "Once a month", "Every Friday", "Only on holidays"], 2, "The speaker says, \"Every Friday, my whole family goes to my grandmother's house for lunch.\""),
                new("What does the grandmother say is her secret?", ["Using a lot of oil", "Cutting the carrots by hand", "Cooking very quickly", "Adding red carrots"], 1, "The speaker says she cuts the carrots \"by hand, never with a machine,\" and \"She says this is her secret.\""),
                new("What did the speaker do to help?", ["Fried the meat", "Cut the onions", "Bought the carrots", "Washed the rice"], 3, "The speaker says, \"I washed the rice three times in cold water.\""),
            ])),
        new("l-a2-4", "A2", new ComprehensionExercise(
            "Train Delay Announcement",
            "Attention, please. This is an announcement for passengers travelling to Samarkand. The fast train at a quarter past two is late today. There is a problem with the train, and engineers are working on it now. The new departure time is ten past three. The train will leave from platform four, not platform two. We are very sorry for the delay. Passengers with tickets for this train can get a free cup of tea or coffee at the station café. Please show your ticket to the staff there. For more information, please go to the information desk near the main entrance. Thank you for your patience.",
            [
                new("What is the main purpose of the announcement?", ["To sell tickets to Samarkand", "To announce a new station café", "To ask passengers to leave the station", "To tell passengers that a train is late"], 3, "The speaker says, \"The fast train at a quarter past two is late today.\""),
                new("What is the new departure time?", ["A quarter past two", "Ten past three", "Half past three", "Ten to three"], 1, "The speaker says, \"The new departure time is ten past three.\""),
                new("Which platform will the train leave from?", ["Platform two", "Platform one", "Platform four", "Platform three"], 2, "The speaker says, \"The train will leave from platform four, not platform two.\""),
                new("What can passengers get at the café?", ["A free cup of tea or coffee", "A free sandwich", "A cheaper ticket", "A free newspaper"], 0, "The speaker says passengers \"can get a free cup of tea or coffee at the station café\"."),
            ])),
        new("l-a2-5", "A2", new ComprehensionExercise(
            "A New Neighbour",
            "Last month a new family moved into the flat next to ours. At first I only saw them on the stairs. Then one evening there was a knock on our door. It was our new neighbour, a young woman called Laylo. She had a plate of warm cookies in her hands. She smiled and said she had made too many. We invited her in for tea. She told us she is a nurse and works at the hospital near the park. She has a little son. He is five years old. Now he plays with my younger brother almost every day. We are already good friends.",
            [
                new("What is the story about?", ["Moving to a new flat", "Meeting a friendly new neighbour", "Baking cookies for a party", "A visit to the hospital"], 1, "The speaker says, \"It was our new neighbour, a young woman called Laylo,\" and \"We are already good friends.\""),
                new("What did Laylo bring?", ["A plate of warm cookies", "A cake", "Some flowers", "A bottle of juice"], 0, "The speaker says, \"She had a plate of warm cookies in her hands.\""),
                new("What is Laylo's job?", ["She is a teacher", "She is a cook", "She is a doctor", "She is a nurse"], 3, "The speaker says, \"She told us she is a nurse and works at the hospital near the park.\""),
                new("How old is Laylo's son?", ["Four", "Six", "Five", "Seven"], 2, "The speaker says, \"She has a little son. He is five years old.\""),
            ])),
        new("l-a2-6", "A2", new ComprehensionExercise(
            "A Call About a Lost Suitcase",
            "Hello, this is a message for Bekzod Karimov. My name is Olga, and I work at the lost luggage office at the airport. We have good news. We found your suitcase. It is the big blue one with a yellow ribbon on the handle. It didn't go on your plane yesterday. It went to the wrong city. Now it is here at the airport again. You don't need to come and get it. A driver can bring it to your home tomorrow afternoon. It's free. Please call us back and tell us your address. Our office is open every day from eight in the morning until ten at night. Thank you, goodbye.",
            [
                new("Why is Olga calling?", ["To sell Bekzod a new suitcase", "To say that Bekzod's suitcase has been found", "To tell Bekzod his flight is cancelled", "To offer Bekzod a job at the airport"], 1, "Olga says, \"We have good news. We found your suitcase.\""),
                new("What does the suitcase look like?", ["Big and blue with a yellow ribbon", "Small and black with a red ribbon", "Big and yellow with a blue handle", "Small and green with no ribbon"], 0, "She says, \"It is the big blue one with a yellow ribbon on the handle.\""),
                new("When can a driver bring the suitcase?", ["This evening", "Tomorrow morning", "Next week", "Tomorrow afternoon"], 3, "Olga says, \"A driver can bring it to your home tomorrow afternoon.\""),
                new("What does Bekzod need to tell the office?", ["His flight number", "The colour of his bag", "His address", "His passport number"], 2, "Olga says, \"Please call us back and tell us your address.\""),
            ])),
        new("l-a2-7", "A2", new ComprehensionExercise(
            "A Class Trip to the Zoo",
            "Good afternoon, parents. This is Dilnoza Yusupova, your children's class teacher. I have some information about our trip to the city zoo next Wednesday. The bus will leave the school at nine o'clock, so please bring your child to school by a quarter to nine. We will come back at about three in the afternoon. Each child needs a packed lunch and a bottle of water. Please don't give them any money, because the trip is already paid for. The weather may be cold, so a warm jacket is a good idea. The children will see the lions, the bears and the new baby elephant. If you have any questions, please send me a message. Thank you.",
            [
                new("What is the message mainly about?", ["A new teacher at the school", "A problem with the school bus", "Plans for a school trip to the zoo", "A lesson about wild animals"], 2, "The teacher says, \"I have some information about our trip to the city zoo next Wednesday.\""),
                new("What time should children arrive at school?", ["By nine o'clock", "By half past eight", "By a quarter past nine", "By a quarter to nine"], 3, "She says, \"Please bring your child to school by a quarter to nine.\""),
                new("Why shouldn't parents give their children money?", ["The zoo shop is closed", "The trip is already paid for", "Money often gets lost", "Food is not allowed at the zoo"], 1, "She says, \"Please don't give them any money, because the trip is already paid for.\""),
                new("Which new animal will the children see?", ["A baby elephant", "A baby lion", "A young bear", "A baby giraffe"], 0, "She says the children will see \"the new baby elephant\"."),
            ])),
        new("l-a2-8", "A2", new ComprehensionExercise(
            "Saturdays at the Flower Shop",
            "Last summer I got my first job. I worked every Saturday at a small flower shop near my house. The owner is a kind old man called Rustam. On my first day I was very nervous. I didn't know the names of the flowers. Rustam gave me a little book with pictures, and I studied it at home. My job was to put water in the buckets and to make the shop clean and tidy. Later I learned to make small bouquets. People usually bought roses and tulips. My favourite customer was an old lady. She bought one white rose every week for her husband. I really loved that job.",
            [
                new("What is the story mainly about?", ["The speaker's first job at a flower shop", "How to grow roses at home", "A visit to a flower market", "Buying a present for a husband"], 0, "The speaker says, \"Last summer I got my first job,\" and describes working at the flower shop."),
                new("How did Rustam help on the first day?", ["He took the speaker to a garden", "He let the speaker go home early", "He gave the speaker some roses", "He gave the speaker a book with pictures"], 3, "The speaker says, \"Rustam gave me a little book with pictures, and I studied it at home.\""),
                new("Which flowers did people usually buy?", ["Lilies and roses", "Tulips and sunflowers", "Roses and tulips", "Daisies and lilies"], 2, "The speaker says, \"People usually bought roses and tulips.\""),
                new("What did the old lady buy every week?", ["A big bouquet of tulips", "One white rose", "Two red roses", "A plant in a pot"], 1, "The speaker says, \"She bought one white rose every week for her husband.\""),
            ])),
        new("l-a2-9", "A2", new ComprehensionExercise(
            "The Weekend Weather Report",
            "And now, here is the weather for the weekend. On Saturday morning it will be cloudy and a little cold, about ten degrees. In the afternoon the sun will come out, and it will be warmer. So Saturday afternoon is a good time for a walk in the park. But on Sunday the weather will change. There will be strong wind and heavy rain all day, and it may even snow in the mountains. So if you want to drive to the mountains, please go on Saturday, not Sunday. And don't forget your umbrella on Sunday. Next week it will be sunny again. That's the weather. Have a lovely weekend.",
            [
                new("What is the report about?", ["The weather for next month", "Traffic on the mountain roads", "A new park in the city", "The weather for Saturday and Sunday"], 3, "The speaker says, \"Here is the weather for the weekend.\""),
                new("What will Saturday afternoon be like?", ["Cold and cloudy", "Windy and rainy", "Sunny and warmer", "Snowy"], 2, "The speaker says, \"In the afternoon the sun will come out, and it will be warmer.\""),
                new("What may happen in the mountains on Sunday?", ["It may snow", "It may be very hot", "The roads may close for repairs", "It may be sunny"], 0, "The speaker says, \"It may even snow in the mountains.\""),
                new("What will the weather be like next week?", ["Rainy every day", "Sunny again", "Very windy", "Cold and snowy"], 1, "The speaker says, \"Next week it will be sunny again.\""),
            ])),
        new("l-a2-10", "A2", new ComprehensionExercise(
            "A Birthday Message from Kamola",
            "Hi Sevara, it's Kamola. How are you? I'm calling because it's my birthday next Sunday, and I'm having a small party at my flat. It starts at five o'clock in the afternoon. My mum is making her famous chocolate cake, and we're going to play some games and sing. Please don't buy me an expensive present. A card is enough, really. My flat is on the fourth floor, and the lift isn't working this week, sorry. Oh, and can you bring your guitar? Everyone loves your music. Please call me or send me a message and tell me if you can come. See you soon. Bye.",
            [
                new("Why is Kamola calling Sevara?", ["To ask her for a guitar lesson", "To invite her to a birthday party", "To tell her about a new flat", "To say thank you for a present"], 1, "Kamola says, \"It's my birthday next Sunday, and I'm having a small party at my flat.\""),
                new("Who is making the cake?", ["Kamola", "Sevara", "A bakery", "Kamola's mum"], 3, "Kamola says, \"My mum is making her famous chocolate cake.\""),
                new("What problem does Kamola mention?", ["The lift isn't working", "Her flat is very small", "The party may start late", "Her mum is ill"], 0, "She says, \"The lift isn't working this week, sorry.\""),
                new("What does Kamola ask Sevara to bring?", ["A chocolate cake", "Some games", "Her guitar", "An expensive present"], 2, "Kamola asks, \"Can you bring your guitar?\""),
            ])),
        new("l-a2-11", "A2", new ComprehensionExercise(
            "The Cat Who Came Home",
            "We have a grey cat called Pishka. One morning last winter, she went out into the garden and didn't come back. We looked for her everywhere. My sister and I walked along every street near our house and called her name. We put pictures of her on the trees and in the shop windows. After three days we were very sad. Then on the fourth evening we heard a sound at the kitchen window. It was Pishka! She was hungry and a little dirty, but she was fine. We think she was in our neighbour's garage. Now we close the garage door every night, just in case.",
            [
                new("What is the story about?", ["Buying a new cat", "A neighbour who found a dog", "A family cat that went missing and came back", "Cleaning a garage"], 2, "The speaker says Pishka \"didn't come back\" and then \"It was Pishka!\""),
                new("What did the speaker and her sister do?", ["Walked along the streets calling the cat", "Called the police", "Asked a vet for help", "Looked for the cat in the park"], 0, "The speaker says, \"My sister and I walked along every street near our house and called her name.\""),
                new("Where did the family hear the cat?", ["At the front door", "In the garage", "On the roof", "At the kitchen window"], 3, "The speaker says, \"We heard a sound at the kitchen window.\""),
                new("Where do they think the cat was?", ["In a shop", "In the neighbour's garage", "Up a tree", "In their own garden"], 1, "The speaker says, \"We think she was in our neighbour's garage.\""),
            ])),
        new("l-b1-1", "B1", new ComprehensionExercise(
            "Radio Tip: Revising for Exams",
            "Good evening, and welcome back to Student Hour. Exams are coming soon, so tonight's tip is about revision. Many students read their notes again and again. It feels useful, but research shows it is not very effective. A better idea is to test yourself. Close your book and try to write down everything you remember. Then check what you missed. Another tip is to study in short blocks. Work for about twenty five minutes, then take a five minute break. Walk around and drink some water, but do not look at your phone. Finally, remember that sleep is not a waste of time. While you sleep, your brain stores the information you learned during the day. So please, do not stay up all night before an exam. That's all for today. Tomorrow we'll talk about how to stay calm in the exam room.",
            [
                new("What is the radio tip mainly about?", ["How to choose a university", "Why phones are bad for students", "Better ways to revise for exams", "How to take good notes in class"], 2, "The presenter says, \"Tonight's tip is about revision.\""),
                new("According to the speaker, what works better than reading notes again and again?", ["Studying all night", "Reading faster", "Studying with music", "Testing yourself"], 3, "The speaker says, \"A better idea is to test yourself.\""),
                new("How long should each study block be?", ["About five minutes", "About twenty-five minutes", "About one hour", "About two hours"], 1, "The speaker says, \"Work for about twenty five minutes, then take a five minute break.\""),
                new("What will tomorrow's programme be about?", ["How to stay calm in the exam room", "How to sleep well", "Healthy food for students", "How to choose a career"], 0, "The presenter says, \"Tomorrow we'll talk about how to stay calm in the exam room.\""),
            ])),
        new("l-b1-2", "B1", new ComprehensionExercise(
            "A Tour of the Crafts Museum",
            "Hello everyone, and welcome to the Museum of Traditional Crafts. My name is Otabek, and I'll be your guide this morning. Our tour will take about one hour. We'll start here on the ground floor, in the pottery room. You'll see bowls and plates that are more than three hundred years old. After that, we'll go upstairs to see the carpets and the silk scarves. Please don't touch anything, because many of the objects are very fragile. You are welcome to take photos, but please switch off the flash. At the end of the tour, there is a small workshop where a local artist will show you how to paint a ceramic bowl. You can even try it yourself. The museum shop is next to the exit. Okay, if everyone is ready, let's begin.",
            [
                new("What is the purpose of the talk?", ["To introduce a museum tour", "To sell carpets and scarves", "To explain how to become a guide", "To advertise a new art school"], 0, "Otabek says, \"I'll be your guide this morning,\" and explains the plan for the tour."),
                new("What will visitors see first?", ["The carpets", "The silk scarves", "The museum shop", "The pottery room"], 3, "The guide says, \"We'll start here on the ground floor, in the pottery room.\""),
                new("What are visitors asked not to do?", ["Take photos", "Talk during the tour", "Touch the objects", "Use the stairs"], 2, "The guide says, \"Please don't touch anything, because many of the objects are very fragile.\""),
                new("What happens at the end of the tour?", ["Visitors watch a short film", "An artist shows how to paint a bowl", "Visitors get a free scarf", "The guide sells tickets for another museum"], 1, "The guide says \"a local artist will show you how to paint a ceramic bowl\"."),
            ])),
        new("l-b1-3", "B1", new ComprehensionExercise(
            "A Voicemail from a Travel Agent",
            "Hi, this is Dilshod from Blue Sky Travel, calling for Sanjar Rahimov. I'm calling about your trip to Istanbul next month. I have some good news and some bad news. The bad news is that the hotel you chose is fully booked for your dates. I'm really sorry about that. The good news is that I found another hotel on the same street. It's a little bigger, and it has a swimming pool on the roof. The price is almost the same, only ten dollars more per night, and breakfast is included. I think it's a great option. But I need your answer by Thursday, because rooms are going quickly. Your flights are all confirmed, so you don't need to worry about them. Please call me back or send me an email. Thanks, and speak soon.",
            [
                new("Why is Dilshod calling?", ["To cancel Sanjar's flights", "To ask Sanjar to pay for breakfast", "To invite Sanjar to visit the travel agency", "To offer a different hotel for Sanjar's trip"], 3, "Dilshod says the first hotel is full and \"I found another hotel on the same street.\""),
                new("What is the problem with the first hotel?", ["It is too expensive", "It is closed for repairs", "It is fully booked", "It is far from the city centre"], 2, "Dilshod says, \"The hotel you chose is fully booked for your dates.\""),
                new("What is special about the new hotel?", ["It has a swimming pool on the roof", "It is much cheaper", "It is next to the airport", "It has a view of the sea"], 0, "Dilshod says, \"It's a little bigger, and it has a swimming pool on the roof.\""),
                new("When does Dilshod need an answer?", ["By tomorrow", "By Thursday", "By Friday", "By next month"], 1, "Dilshod says, \"I need your answer by Thursday, because rooms are going quickly.\""),
            ])),
        new("l-b1-4", "B1", new ComprehensionExercise(
            "Why I Started Running",
            "Two years ago, I couldn't run to the bus stop without losing my breath. I worked in an office all day, I ate a lot of fast food, and I felt tired all the time. Then my doctor told me that I needed to move more. I didn't like gyms, so I decided to try running. On my first day, I ran for only two minutes and then walked home. I felt a bit silly. But I kept going, three mornings a week. My friend Aziza joined me, and that helped a lot, because we didn't want to let each other down. After six months, I could run five kilometres without stopping. Last spring I finished my first half marathon. But the best part isn't the medal. It's that I sleep better and feel happier every day.",
            [
                new("What is the talk mainly about?", ["How to win a marathon", "How the speaker became a runner and how it helped", "Why gyms are better than running", "The speaker's problems at work"], 1, "The speaker describes going from losing breath at the bus stop to finishing \"my first half marathon\"."),
                new("Why did the speaker start running?", ["A friend needed a running partner", "The speaker wanted to win a medal", "The office started a running club", "The doctor said the speaker needed to move more"], 3, "The speaker says, \"My doctor told me that I needed to move more.\""),
                new("How often did the speaker run at first?", ["Three mornings a week", "Every day", "Once a week", "Two evenings a week"], 0, "The speaker says, \"I kept going, three mornings a week.\""),
                new("What does the speaker say is the best part?", ["Winning a medal", "Losing weight quickly", "Sleeping better and feeling happier", "Meeting new people"], 2, "The speaker says, \"The best part isn't the medal. It's that I sleep better and feel happier every day.\""),
            ])),
        new("l-b1-5", "B1", new ComprehensionExercise(
            "Community Clean-Up Day",
            "Hello, neighbours! This is a short announcement about this weekend. This Saturday we are organising a clean-up day in Navruz Park. We'll meet at the main gate at nine o'clock in the morning and finish at about one. We'll collect rubbish, paint the old benches and plant twenty new trees along the path. Gloves, bags and tools will be provided, so you only need to bring comfortable clothes and a hat, because it may be sunny. Children are very welcome, but they must come with an adult. After the work, there will be a free lunch for all volunteers. The local bakery has kindly offered bread and pastries. If it rains, the event will move to the following Saturday. We hope to see many of you there. Let's make our park beautiful together.",
            [
                new("What is the announcement mainly about?", ["The opening of a new bakery", "A tree-planting competition for children", "An invitation to help clean a local park", "A meeting about building a new park"], 2, "The speaker says, \"This Saturday we are organising a clean-up day in Navruz Park.\""),
                new("What time will people meet?", ["At nine o'clock", "At one o'clock", "At ten o'clock", "At eight o'clock"], 0, "The speaker says, \"We'll meet at the main gate at nine o'clock in the morning.\""),
                new("What should volunteers bring?", ["Gloves and bags", "Their own tools", "Bread and pastries", "Comfortable clothes and a hat"], 3, "The speaker says, \"You only need to bring comfortable clothes and a hat.\""),
                new("What will happen if it rains?", ["The event will take place indoors", "The event will move to the following Saturday", "The event will be cancelled", "The event will start later in the day"], 1, "The speaker says, \"If it rains, the event will move to the following Saturday.\""),
            ])),
        new("l-b1-6", "B1", new ComprehensionExercise(
            "Radio Tip: Saving Water at Home",
            "Welcome back to Green Living, the show that helps you live a little more lightly. Today's tip is about water. Most of us use much more water than we need, and we don't even notice it. So here are three easy changes. First, turn off the tap while you brush your teeth. It sounds small, but a running tap wastes several litres every minute. Second, take shorter showers. Try to finish in five minutes. Some listeners play one favourite song and get out when the song ends. Third, don't throw away the water you use to wash fruit and vegetables. Put it in a bowl and give it to your plants. Your garden will love it. If everyone in your family makes these changes, you'll also see a smaller water bill at the end of the month. Next week, we'll look at how to save electricity.",
            [
                new("What is the radio tip mainly about?", ["Simple ways to use less water at home", "How to grow vegetables in a garden", "Why water bills are going up", "How to choose a good shower"], 0, "The presenter says, \"Today's tip is about water,\" and gives \"three easy changes\"."),
                new("Why should you turn off the tap while brushing your teeth?", ["The water is too cold", "It is bad for your teeth", "A running tap wastes several litres every minute", "It makes the bathroom wet"], 2, "The speaker says, \"A running tap wastes several litres every minute.\""),
                new("How do some listeners keep their showers short?", ["They use a timer on their phone", "They play one song and get out when it ends", "They shower only in cold water", "They shower every second day"], 1, "The speaker says, \"Some listeners play one favourite song and get out when the song ends.\""),
                new("What will next week's programme be about?", ["Saving water in the garden", "Cooking healthy food", "Recycling plastic", "Saving electricity"], 3, "The presenter says, \"Next week, we'll look at how to save electricity.\""),
            ])),
        new("l-b1-7", "B1", new ComprehensionExercise(
            "Voicemail: Your Bicycle Is Ready",
            "Hi, this message is for Timur. It's Sardor from Wheels and Gears, the bike repair shop on Chilonzor Street. Just letting you know that your bicycle is ready. We changed the back tyre, and we fixed the brakes, which were in quite a bad condition, to be honest. We also noticed that your chain was very old, so we put on a new one. I hope that's okay. It was only a small extra cost. The total is two hundred thousand sum. You can pay by card or in cash when you pick it up. We're open until seven this evening, and tomorrow from ten. One more thing. Your front light isn't working. We didn't have the right part, but we can order it for you if you like. Just tell us when you come in. See you soon.",
            [
                new("Why is Sardor calling?", ["To sell Timur a new bicycle", "To ask Timur to work at the shop", "To say the shop is closing", "To say that Timur's bicycle has been repaired"], 3, "Sardor says, \"Just letting you know that your bicycle is ready.\""),
                new("What did the shop do without asking Timur first?", ["Changed the front tyre", "Put on a new chain", "Painted the bicycle", "Fixed the front light"], 1, "Sardor says the chain was very old, \"so we put on a new one. I hope that's okay.\""),
                new("When is the shop open tomorrow?", ["From seven", "Only in the evening", "From ten", "It is closed tomorrow"], 2, "Sardor says, \"We're open until seven this evening, and tomorrow from ten.\""),
                new("Why wasn't the front light fixed?", ["The shop didn't have the right part", "Timur didn't want it fixed", "It was too expensive", "The shop ran out of time"], 0, "Sardor says, \"We didn't have the right part, but we can order it for you.\""),
            ])),
        new("l-b1-8", "B1", new ComprehensionExercise(
            "The Wrong Bus",
            "A few years ago, I was travelling alone and I wanted to visit a famous old castle. I was very tired, and at the bus station I got on the wrong bus. I didn't notice for almost an hour. When I finally asked the driver, he laughed and said the castle was in the opposite direction. He dropped me in a tiny village in the hills. The next bus back was at six in the evening, so I had the whole afternoon there. At first I was annoyed. But then an old woman invited me into her garden and gave me fresh apricots and bread. Her grandson spoke a little English, and he showed me a waterfall behind the village. It was beautiful, and there were no tourists at all. I never saw the castle. But I still think that wrong bus gave me the best day of the whole trip.",
            [
                new("What is the main point of the story?", ["Buses in the countryside are always late", "A mistake led to an unexpectedly great day", "The castle was disappointing", "Travelling alone is dangerous"], 1, "The speaker says, \"I still think that wrong bus gave me the best day of the whole trip.\""),
                new("Why did the speaker get on the wrong bus?", ["The speaker was very tired", "The driver gave wrong information", "The signs were in another language", "The speaker was in a hurry"], 0, "The speaker says, \"I was very tired, and at the bus station I got on the wrong bus.\""),
                new("What did the old woman give the speaker?", ["A cup of tea and cake", "A map of the village", "A ride to the castle", "Fresh apricots and bread"], 3, "The speaker says she \"gave me fresh apricots and bread\"."),
                new("What did the grandson show the speaker?", ["The way to the castle", "An old church", "A waterfall behind the village", "His school"], 2, "The speaker says, \"He showed me a waterfall behind the village.\""),
            ])),
        new("l-b1-9", "B1", new ComprehensionExercise(
            "Changes at the City Library",
            "Good morning, and thank you for visiting the City Library. We'd like to tell you about some changes that start next month. First, our opening hours are getting longer. From Monday to Friday we will stay open until nine in the evening, instead of six. We hope this helps students and people who work during the day. Second, we are putting in new self-service machines near the entrance. You'll be able to borrow and return books yourself, without waiting in a queue. Our staff will be there to help you during the first few weeks. Third, the children's section on the second floor will be closed for two weeks while we paint it and add new shelves. During that time, children's books will be in the reading room on the ground floor. If you have any questions, please ask at the information desk. Thank you.",
            [
                new("What is the announcement mainly about?", ["A new book by a local writer", "The library closing for good", "Changes to the library's services", "A reading competition for children"], 2, "The speaker says, \"We'd like to tell you about some changes that start next month.\""),
                new("Until what time will the library stay open on weekdays?", ["Until six in the evening", "Until eight in the evening", "Until ten in the evening", "Until nine in the evening"], 3, "The speaker says, \"We will stay open until nine in the evening, instead of six.\""),
                new("What will the new machines let people do?", ["Print documents for free", "Borrow and return books themselves", "Buy coffee and snacks", "Read newspapers online"], 1, "The speaker says, \"You'll be able to borrow and return books yourself, without waiting in a queue.\""),
                new("Where will children's books be for two weeks?", ["In the reading room on the ground floor", "On the second floor", "Near the entrance", "At another library"], 0, "The speaker says, \"Children's books will be in the reading room on the ground floor.\""),
            ])),
        new("l-b1-10", "B1", new ComprehensionExercise(
            "Weekends at the Animal Shelter",
            "Hi everyone. I'd like to tell you about my Saturdays. For the last year, I've been a volunteer at an animal shelter on the edge of the city. The shelter looks after dogs and cats that have no home. When I started, I thought I would just play with puppies all day. In fact, the first job is always cleaning, and it isn't very exciting. After that, I take the older dogs for walks. They're my favourites, because people usually want young animals, so the older ones wait much longer for a family. I've also learned how to give medicine and how to help a scared animal feel calm. The best moment was last month. A dog called Bars, who lived at the shelter for two years, finally went home with a lovely family. I cried a little, to be honest. If you love animals, I really recommend it.",
            [
                new("What is the talk mainly about?", ["The speaker's experience as a shelter volunteer", "How to choose a puppy", "Why the speaker bought a dog", "A job as an animal doctor"], 0, "The speaker says, \"For the last year, I've been a volunteer at an animal shelter.\""),
                new("What is always the first job?", ["Walking the dogs", "Feeding the cats", "Playing with puppies", "Cleaning"], 3, "The speaker says, \"The first job is always cleaning, and it isn't very exciting.\""),
                new("Why are the older dogs the speaker's favourites?", ["They are calmer than puppies", "They are easier to walk", "They wait much longer for a family", "They need less medicine"], 2, "The speaker says people usually want young animals, \"so the older ones wait much longer for a family\"."),
                new("How long did Bars live at the shelter?", ["One month", "Two years", "One year", "Three years"], 1, "The speaker says Bars \"lived at the shelter for two years\"."),
            ])),
        new("l-b1-11", "B1", new ComprehensionExercise(
            "Radio Tip: Staying Cool in a Heatwave",
            "Good afternoon, and welcome to Health Minute. This week is going to be extremely hot, so here's some advice on staying safe in the heat. First, drink water regularly, even when you don't feel thirsty. By the time you feel thirsty, your body already needs more water. Try to avoid sweet fizzy drinks, because they don't help much. Second, stay out of the sun in the middle of the day, from about eleven until four. If you have to go out, wear a hat and light, loose clothes. Third, keep your home cool. Close the curtains in the morning, and open the windows in the evening when the air is cooler. Finally, please check on older neighbours and relatives. They can get ill from the heat more easily, and they may not ask for help. A short phone call can make a big difference.",
            [
                new("What is the radio tip mainly about?", ["How to keep your garden green", "Choosing clothes for a holiday", "The dangers of sweet drinks", "How to stay safe during very hot weather"], 3, "The presenter says, \"Here's some advice on staying safe in the heat.\""),
                new("Why should you drink water before you feel thirsty?", ["Water is cheaper than other drinks", "Thirst is a sign of a serious illness", "When you feel thirsty, your body already needs more water", "Cold water helps you sleep better"], 2, "The speaker says, \"By the time you feel thirsty, your body already needs more water.\""),
                new("When should you open the windows?", ["In the evening", "In the morning", "In the middle of the day", "Only at night after midnight"], 0, "The speaker says to \"open the windows in the evening when the air is cooler\"."),
                new("Why should people check on older neighbours?", ["They often need help with shopping", "They can get ill from the heat more easily", "They don't have phones", "They like to have visitors"], 1, "The speaker says, \"They can get ill from the heat more easily, and they may not ask for help.\""),
            ])),
        new("l-b2-1", "B2", new ComprehensionExercise(
            "Podcast: Life Inside a Beehive",
            "Welcome to Wild Minds, the podcast about the surprising lives of animals. Today we're looking at honeybees, and trust me, they're far more organised than most offices. A single hive can contain tens of thousands of bees, but only one of them is the queen. Her main job is to lay eggs, sometimes well over a thousand in a single day. Almost all the other bees are female workers, and what they do depends on their age. Young workers stay inside, cleaning cells and feeding the larvae. Older ones become foragers, flying out to collect nectar and pollen. Now here's my favourite part. When a forager finds a good patch of flowers, she returns to the hive and performs what scientists call the waggle dance. The angle of her dance shows the direction of the flowers compared to the sun, and the length of the dance tells the others how far away they are. It's essentially a map made of movement. After the break, we'll talk to a beekeeper about why bee numbers have been falling, and what gardeners can do to help.",
            [
                new("What is the podcast episode mainly about?", ["How honeybees organise their work and share information", "How to become a beekeeper", "Why honey is good for your health", "The dangers of bee stings"], 0, "The host says \"they're far more organised than most offices\" and describes their jobs and the waggle dance."),
                new("What do young worker bees do?", ["Collect nectar and pollen", "Lay eggs", "Clean cells and feed the larvae", "Guard the entrance of the hive"], 2, "The host says, \"Young workers stay inside, cleaning cells and feeding the larvae.\""),
                new("What does the length of the waggle dance show?", ["The direction of the sun", "How far away the flowers are", "How many flowers there are", "Which bee found the flowers"], 1, "The host says \"the length of the dance tells the others how far away they are\"."),
                new("What will happen after the break?", ["The host will read a report on queen bees", "Listeners will take part in a quiz", "The host will talk about wasps", "The host will talk to a beekeeper"], 3, "The host says, \"After the break, we'll talk to a beekeeper about why bee numbers have been falling.\""),
            ])),
        new("l-b2-2", "B2", new ComprehensionExercise(
            "Budgeting Tips for Students",
            "Hi everyone, thanks for coming to this short session on managing money at university. I know budgeting sounds boring, but trust me, it's much less boring than running out of money in the middle of the month. So, first things first. As soon as your grant or wages arrive, move a small amount into a separate savings account. Even a tenth makes a real difference. Treat that money as if it doesn't exist. Next, look at your fixed costs, things like rent, transport and your phone. These are the same every month, so take them away first. What's left is what you can actually spend on food, going out and everything else. Divide that by four, and you've got a weekly limit. Many students I talk to say their biggest problem isn't rent. It's small daily spending, like coffee on the way to lectures or ordering food late at night. So try cooking in batches on Sundays. It's cheaper and healthier. And finally, don't be embarrassed to use student discounts. Always ask. You'd be amazed how many shops, cinemas and museums offer them.",
            [
                new("What is the session mainly about?", ["How to find a part-time job", "Why students should never go out", "How to open a bank account online", "Practical advice on managing money as a student"], 3, "The speaker welcomes everyone to \"this short session on managing money at university\"."),
                new("What should students do as soon as their money arrives?", ["Pay for a month of food", "Move a small amount into savings", "Buy a monthly transport pass", "Pay their rent for the whole year"], 1, "The speaker says, \"As soon as your grant or wages arrive, move a small amount into a separate savings account.\""),
                new("According to the speaker, what is many students' biggest problem?", ["Paying rent", "Buying textbooks", "Small daily spending", "Phone bills"], 2, "The speaker says, \"Their biggest problem isn't rent. It's small daily spending.\""),
                new("Why does the speaker suggest cooking in batches on Sundays?", ["It is cheaper and healthier", "It saves time for studying", "Friends can eat together", "Shops are closed on Sundays"], 0, "The speaker says, \"Try cooking in batches on Sundays. It's cheaper and healthier.\""),
            ])),
        new("l-b2-3", "B2", new ComprehensionExercise(
            "The Long Road to the Zip",
            "Here's a question for you. What do jackets, bags and tents all have in common? The zip, of course. It's so ordinary that we never think about it. But it took inventors several decades to get it right. In the eighteen nineties, an American inventor called Whitcomb Judson showed a device for fastening shoes. It used hooks and eyes, and it was clever, but it often got stuck or came open by itself. People weren't impressed. Then, in nineteen thirteen, a Swedish engineer working in America, Gideon Sundback, designed a much better version. Instead of hooks, it had small teeth that locked together neatly, and it was far more reliable. Even so, the invention was slow to catch on. At first, it was mainly used for boots and tobacco pouches. The name zipper actually came from a company that made rubber boots, because of the sound the fastener made. It was only in the nineteen thirties, when fashion designers began putting zips into trousers and children's clothes, that the zip truly became part of everyday life.",
            [
                new("What is the talk mainly about?", ["Judson's device was an immediate success", "The zip took a long time to develop and become popular", "The zip was first designed for trousers", "Rubber boots were invented in Sweden"], 1, "The speaker says \"it took inventors several decades to get it right\" and that it \"was slow to catch on\"."),
                new("What was the problem with Judson's device?", ["It often got stuck or came open by itself", "It was too expensive to make", "It was too heavy to wear", "It only worked on bags"], 0, "The speaker says \"it often got stuck or came open by itself\"."),
                new("Where did the name zipper come from?", ["A famous fashion designer", "The inventor's surname", "A Swedish word for teeth", "A company that made rubber boots"], 3, "The speaker says, \"The name zipper actually came from a company that made rubber boots.\""),
                new("When did the zip truly become part of everyday life?", ["In the eighteen nineties", "In nineteen thirteen", "In the nineteen thirties", "In the nineteen fifties"], 2, "The speaker says \"it was only in the nineteen thirties\" that the zip \"truly became part of everyday life\"."),
            ])),
        new("l-b2-4", "B2", new ComprehensionExercise(
            "A Morning Walk Through Old Bukhara",
            "Good morning, and welcome to Bukhara. Before we set off, let me explain today's route. We're going to walk for about two and a half hours, so I hope you're wearing comfortable shoes. We'll begin at Lyabi Hauz, the old pond surrounded by mulberry trees. For centuries it was the social heart of this neighbourhood, a place where people came to drink tea, chat and escape the heat. From there, we'll walk through the trading domes. These covered markets were built so that merchants could do business protected from the sun, and you can still buy spices, knives and embroidered cloth there today. Then we'll see the Kalyan Minaret. It's almost fifty metres tall, and it has been standing for nearly nine hundred years. Many travellers say the square beside it is the most beautiful place in the city. Please drink plenty of water, because it gets very hot here by midday. And one last thing. Bargaining is normal in the markets, but please do it with a smile. Right, follow me.",
            [
                new("What is the guide mainly doing?", ["Giving a history lecture about China", "Selling souvenirs to tourists", "Explaining the route of a walking tour", "Announcing that a museum is closed"], 2, "The guide says, \"Before we set off, let me explain today's route.\""),
                new("What was Lyabi Hauz in the past?", ["A covered market", "A school for merchants", "A place to keep camels", "A place where people met to drink tea and chat"], 3, "The guide says it was \"the social heart of this neighbourhood, a place where people came to drink tea, chat and escape the heat\"."),
                new("Why were the trading domes built?", ["To store water", "To protect merchants from the sun", "To keep animals safe", "To hold festivals"], 1, "The guide says they \"were built so that merchants could do business protected from the sun\"."),
                new("What does the guide say about bargaining?", ["It is normal but should be done with a smile", "It is not allowed in the markets", "Only the guide should do it", "It is considered rude in Bukhara"], 0, "The guide says, \"Bargaining is normal in the markets, but please do it with a smile.\""),
            ])),
        new("l-b2-5", "B2", new ComprehensionExercise(
            "A Manager's Advice on Remote Work",
            "Hello, and thanks for tuning in to Work Smart. A listener asked me what I've learned from managing a team that works almost entirely from home. So here are my three lessons. The first is about boundaries. When your office is also your kitchen, work can easily take over your whole day. I encourage my team to have a clear finishing time and, if possible, a separate space for work, even if it's just a small desk in a corner. The second lesson is about communication. In an office, you notice when a colleague looks stressed. Online, you don't. So I have a short video call with each person every week, and it's not about tasks. It's simply to ask how they're doing. The third lesson surprised me. People who work from home often feel they have to prove they're busy, so they answer messages instantly, even late at night. I tell my team clearly that I judge results, not reply times. Since I started saying that, people seem calmer, and honestly, the quality of their work has improved.",
            [
                new("What is the speaker mainly talking about?", ["Lessons from managing a team that works from home", "How to find a job you can do from home", "Why offices are better than working from home", "How to set up video call software"], 0, "The speaker shares \"what I've learned from managing a team that works almost entirely from home\"."),
                new("What does the speaker encourage to keep work and home separate?", ["Working at the kitchen table", "Answering messages late at night", "Taking long lunch breaks", "A clear finishing time and a separate work space"], 3, "The speaker says, \"I encourage my team to have a clear finishing time and, if possible, a separate space for work.\""),
                new("What is the purpose of the weekly video call?", ["To check tasks and deadlines", "To train new staff", "To ask how each person is doing", "To plan team parties"], 2, "The speaker says the call is \"not about tasks. It's simply to ask how they're doing.\""),
                new("What does the speaker say they judge their team on?", ["How quickly people answer messages", "Results, not reply times", "How many hours people work", "How tidy their desks are"], 1, "The speaker says, \"I tell my team clearly that I judge results, not reply times.\""),
            ])),
        new("l-b2-6", "B2", new ComprehensionExercise(
            "A Potter on Learning Patience",
            "People often ask me what pottery has taught me, and my answer is always the same. Patience. Not skill, not creativity, but patience. When I started, I was twenty-five and I was used to getting results quickly. At work, I sent an email and got an answer in minutes. Clay doesn't work like that. My first teacher made me practise centring the clay on the wheel for a whole month before I was allowed to make a single bowl. I was furious. I thought she was wasting my time. But she was right. If the clay isn't perfectly centred, everything you build on top of it will wobble and eventually collapse. Then there's the drying, which can take a week, and the firing in the kiln, which can crack a piece you've spent days on. You learn to accept that some work will fail. Oddly enough, that lesson has made me calmer in the rest of my life too. When something goes wrong now, I simply start again.",
            [
                new("What is the speaker's main message?", ["Pottery is a good way to earn money", "Pottery taught the speaker to be patient", "Teachers should not be too strict", "Clay is difficult to buy"], 1, "The speaker says, \"People often ask me what pottery has taught me, and my answer is always the same. Patience.\""),
                new("How did the speaker feel about practising centring for a month?", ["Grateful", "Bored but calm", "Proud", "Furious"], 3, "The speaker says, \"I was furious. I thought she was wasting my time.\""),
                new("What happens if the clay isn't centred?", ["What you build will wobble and collapse", "It dries too quickly", "It changes colour in the kiln", "It becomes too heavy to lift"], 0, "The speaker says, \"Everything you build on top of it will wobble and eventually collapse.\""),
                new("How has pottery changed the speaker's life outside the studio?", ["The speaker now works faster", "The speaker has stopped using email", "The speaker is calmer when things go wrong", "The speaker has become a teacher"], 2, "The speaker says, \"That lesson has made me calmer in the rest of my life too.\""),
            ])),
        new("l-b2-7", "B2", new ComprehensionExercise(
            "Radio Report: The Village That Went Solar",
            "Good morning. In today's report, we travel to a small mountain village where something remarkable has happened. Until three years ago, the village had electricity for only a few hours a day, and power cuts were common in winter. Families used candles and old generators, and students did their homework in the dark. Then a group of residents decided to stop waiting for help. They formed a cooperative, saved money together and, with a small loan from a regional bank, put solar panels on the roof of the school and the clinic. The school became the first building with reliable power, and children could finally use computers in their lessons. Encouraged by that success, more families joined. Today almost every house has panels, and extra electricity is stored in batteries for cloudy days. The head of the cooperative told us the hardest part wasn't the technology. It was persuading people to trust one another with their savings. Now, she says, neighbouring villages are visiting to learn how they did it.",
            [
                new("What is the report mainly about?", ["How solar panels are manufactured", "A new bank opening in the mountains", "How a village organised itself to get reliable electricity", "Why power cuts happen in winter"], 2, "The reporter describes how residents \"formed a cooperative\" and put up solar panels until \"almost every house has panels\"."),
                new("Which buildings got solar panels first?", ["The school and the clinic", "The bank and the school", "Every family house", "The clinic and the shop"], 0, "The reporter says they \"put solar panels on the roof of the school and the clinic\"."),
                new("How is extra electricity used on cloudy days?", ["It is bought from the city", "It is shared with other villages", "It is produced by a generator", "It is stored in batteries"], 3, "The reporter says, \"Extra electricity is stored in batteries for cloudy days.\""),
                new("According to the head of the cooperative, what was the hardest part?", ["Understanding the technology", "Getting people to trust one another with their savings", "Getting a loan from the bank", "Carrying panels up the mountain"], 1, "She said the hardest part \"was persuading people to trust one another with their savings\"."),
            ])),
        new("l-b2-8", "B2", new ComprehensionExercise(
            "Podcast: Why We Forget Names",
            "Welcome back to the Curious Mind podcast. Here's a situation you probably know well. You meet someone at a party, they tell you their name, and ten seconds later it's gone. Why does this happen? One reason is attention. When we're introduced, we're often busy thinking about what to say next, or worrying about the impression we're making. So the name never really gets stored in the first place. Another reason is that names are, in a sense, arbitrary. If I tell you someone is a baker, your brain connects that word to bread, smells and early mornings. But a name like Anvar or Helen doesn't connect to anything, so it's harder to hold on to. So what can you do? Try repeating the name out loud straight away, as in, nice to meet you, Anvar. Then link it to something vivid, perhaps a friend with the same name. And use it once more before you say goodbye. It feels awkward at first, but it really works.",
            [
                new("What is the podcast episode mainly about?", ["Why names are easy to forget and how to remember them", "How to make a good impression at parties", "The history of common names", "Why some people have better memories than others"], 0, "The host asks, \"Why does this happen?\" and later, \"So what can you do?\""),
                new("What is one reason given for forgetting names?", ["Names are usually too long", "Parties are too noisy", "We are busy thinking about what to say next", "We meet too many people every day"], 2, "The host says, \"We're often busy thinking about what to say next.\""),
                new("Why is a job like baker easier to remember than a name?", ["It is a shorter word", "The word connects to other things in our brain", "We hear it more often", "It is easier to pronounce"], 1, "The host says the brain \"connects that word to bread, smells and early mornings\"."),
                new("What is the final piece of advice?", ["Write the name down", "Ask for a business card", "Repeat the name silently many times", "Use the name once more before saying goodbye"], 3, "The host says, \"Use it once more before you say goodbye.\""),
            ])),
        new("l-b2-9", "B2", new ComprehensionExercise(
            "A Mountain Guide on Changing Weather",
            "Right, before we set off, I want to say a few words about the weather, because it's the thing that surprises visitors most up here. The forecast this morning is good, but in the mountains conditions can change within an hour. A clear sky at breakfast can turn into fog and freezing wind by lunchtime. So, a few rules for today. Everyone must carry a waterproof jacket and a warm layer, even if it feels hot right now. If you see dark clouds building behind the ridge, tell me immediately. Don't assume I've noticed. We'll stop for lunch at the lake, and that's our decision point. If the weather looks uncertain, we'll turn back there rather than continue to the summit. I know some of you really want to reach the top, and I understand that. But the mountain will still be here next year. My job is to make sure you are too. Okay, fill your water bottles at the hut, and let's meet at the gate in five minutes. Any questions?",
            [
                new("What is the guide mainly talking about?", ["The history of the mountain", "How to cook lunch at the lake", "Why the summit is closed", "How changing weather affects the day's plans and safety"], 3, "The guide says, \"I want to say a few words about the weather, because it's the thing that surprises visitors most.\""),
                new("What must everyone carry?", ["A map and a compass", "A waterproof jacket and a warm layer", "Extra food and water", "A torch and a phone"], 1, "The guide says, \"Everyone must carry a waterproof jacket and a warm layer.\""),
                new("What should people do if they see dark clouds?", ["Walk faster to the summit", "Put on their jackets and wait", "Tell the guide immediately", "Go back to the lake alone"], 2, "The guide says, \"If you see dark clouds building behind the ridge, tell me immediately.\""),
                new("What will happen at the lake if the weather is uncertain?", ["The group will turn back", "The group will wait for the fog to clear", "The group will take a shorter path to the top", "The group will camp for the night"], 0, "The guide says, \"If the weather looks uncertain, we'll turn back there rather than continue to the summit.\""),
            ])),
        new("l-b2-10", "B2", new ComprehensionExercise(
            "A Voicemail from the Landlord",
            "Hello Malika, it's Farrukh, your landlord. I'm calling about the problems you reported last week. First, the good news. The plumber has finally found the cause of the leak in your bathroom. It's a broken pipe behind the wall, which explains why the ceiling in the flat below has been getting wet. Unfortunately, fixing it properly means opening up part of the wall, so the work will take two full days. He can start next Tuesday, and he'll need to begin quite early, at around eight in the morning. I'm afraid you won't have hot water on those days, so if you'd prefer to stay with friends, I'll take one week's rent off this month to make up for the inconvenience. As for the broken heater in the bedroom, I've ordered a new one, and it should arrive by the end of the month. In the meantime, I'll drop off a portable heater tomorrow evening. Please let me know if Tuesday works for you. Thanks for your patience.",
            [
                new("What is the main purpose of the call?", ["To ask Malika to pay her rent", "To explain how and when the reported problems will be fixed", "To tell Malika she has to move out", "To complain about noise from Malika's flat"], 1, "Farrukh says, \"I'm calling about the problems you reported last week.\""),
                new("What is causing the leak?", ["A broken pipe behind the wall", "A problem with the washing machine", "Rain coming through the roof", "A leak in the flat above"], 0, "Farrukh says, \"It's a broken pipe behind the wall.\""),
                new("What does Farrukh offer because of the inconvenience?", ["To pay for a hotel", "To give Malika a new heater for free", "To paint the bathroom", "To take one week's rent off"], 3, "He says, \"I'll take one week's rent off this month to make up for the inconvenience.\""),
                new("What will Farrukh bring tomorrow evening?", ["The new bedroom heater", "Some tools for the plumber", "A portable heater", "A new contract"], 2, "He says, \"I'll drop off a portable heater tomorrow evening.\""),
            ])),
        new("l-b2-11", "B2", new ComprehensionExercise(
            "The Night the Power Went Out",
            "It happened on the coldest night of that winter. At about seven in the evening, the lights in our whole building suddenly went out. At first everyone stayed in their own flats, waiting for the power to come back. But after an hour, it was clear this would take a while. Then someone knocked on our door. It was the quiet old man from the third floor, holding a candle and smiling. He said he had a gas stove and a huge pot of soup, and he wanted everyone to come and share it. I'd lived in that building for four years and had never really spoken to him. That night, about fifteen of us squeezed into his tiny kitchen. The children played games by candlelight, and he told stories about the building when it was new. The power came back just after midnight, and to be honest, some of us were almost disappointed. Since then, we have a dinner together every month.",
            [
                new("What is the story mainly about?", ["How to cook soup without electricity", "Why the building needed repairs", "How a power cut brought neighbours together", "A difficult winter holiday"], 2, "The speaker describes neighbours sharing soup and says, \"Since then, we have a dinner together every month.\""),
                new("Why did the old man knock on the door?", ["To ask for a candle", "To complain about the noise", "To borrow a gas stove", "To invite everyone to share his soup"], 3, "The speaker says he \"wanted everyone to come and share it\"."),
                new("How well did the speaker know the old man before that night?", ["They were close friends", "They had never really spoken", "He was the speaker's relative", "They met every week"], 1, "The speaker says, \"I'd lived in that building for four years and had never really spoken to him.\""),
                new("How did some people feel when the power came back?", ["Almost disappointed", "Very relieved", "Angry about the delay", "Too tired to notice"], 0, "The speaker says, \"To be honest, some of us were almost disappointed.\""),
            ])),
        new("l-c1-1", "C1", new ComprehensionExercise(
            "Podcast: Why Habits Stick",
            "Welcome back to The Curious Mind. Today we're exploring a question that has probably frustrated every single one of you at some point. Why is it so hard to build good habits, and so annoyingly easy to keep bad ones? Researchers who study behaviour describe a habit as a kind of loop. There's a cue, something in your environment that triggers the behaviour. There's the routine itself. And there's a reward, which is what persuades your brain that the whole thing is worth repeating. The crucial point is that once a habit is established, it runs largely on autopilot. That's wonderful when the habit is brushing your teeth, and rather less wonderful when it's reaching for your phone the moment you feel bored. Contrary to the popular claim that it takes exactly twenty one days to form a habit, the research suggests the timeframe varies enormously, from a few weeks to the better part of a year, depending on the person and the behaviour. Later in the episode, I'll be speaking to a psychologist who argues that willpower is overrated, and that the smartest strategy is to redesign your surroundings so that the good choice becomes the easy one. Stay with us.",
            [
                new("What is the episode mainly about?", ["The history of the toothbrush", "Why willpower is the key to success", "How to use your phone less at work", "How habits work and why they are hard to change"], 3, "The host asks, \"Why is it so hard to build good habits, and so annoyingly easy to keep bad ones?\""),
                new("According to the host, what is the role of the reward?", ["It triggers the behaviour in the first place", "It replaces the routine", "It persuades the brain that the behaviour is worth repeating", "It makes the habit disappear"], 2, "The host says the reward \"is what persuades your brain that the whole thing is worth repeating\"."),
                new("What does research say about how long it takes to form a habit?", ["It varies greatly depending on the person and the behaviour", "It always takes exactly twenty-one days", "It takes at least two years", "It takes only a few days"], 0, "The host says \"the timeframe varies enormously\", \"depending on the person and the behaviour\"."),
                new("What does the guest psychologist argue?", ["Willpower is the most important factor", "It is smarter to redesign your surroundings than to rely on willpower", "Bad habits can never really be changed", "Rewards should be avoided completely"], 1, "The host says the psychologist \"argues that willpower is overrated\" and recommends redesigning \"your surroundings\"."),
            ])),
        new("l-c1-2", "C1", new ComprehensionExercise(
            "Lecture: Why Great Cities Grew Beside Rivers",
            "Good afternoon. In today's lecture, I want to consider a pattern so familiar that we rarely question it. If you look at a map of the world's great historic cities, a remarkable number of them sit on the banks of a river. Why should that be? The obvious answer is drinking water, but that's only the beginning. Rivers deposit fertile soil when they flood, which allowed early farmers to produce a surplus of food. And a surplus, crucially, is what frees some people from farming altogether, so they can become craftsmen, traders and officials. In other words, city dwellers. Rivers were also the motorways of the ancient world. Moving heavy goods by boat was vastly cheaper and faster than hauling them overland, so places where routes met, or where a river could easily be crossed, tended to flourish as markets. Here in Central Asia, the oasis cities along the Zarafshan depended on careful irrigation for their very existence. That said, rivers were a mixed blessing. The same floods that enriched the soil could sweep away homes, and standing water brought disease. So next week, we'll look at how early engineers tried to control rivers, with varying degrees of success.",
            [
                new("What is the lecture mainly about?", ["How modern motorways are planned", "Why so many historic cities developed beside rivers", "The causes of floods in Central Asia", "Why people are leaving farms today"], 1, "The lecturer notes that many great cities \"sit on the banks of a river\" and asks, \"Why should that be?\""),
                new("Why, according to the lecturer, was a food surplus important?", ["It made rivers flood more often", "It was sold to other continents", "It made boats cheaper to build", "It allowed some people to do jobs other than farming"], 3, "The lecturer says a surplus \"is what frees some people from farming altogether\"."),
                new("What does the lecturer compare rivers to?", ["The motorways of the ancient world", "The walls of a city", "Modern markets", "A map of the world"], 0, "The lecturer says, \"Rivers were also the motorways of the ancient world.\""),
                new("What will next week's lecture be about?", ["The history of boat building", "Diseases in modern cities", "How early engineers tried to control rivers", "Farming in the desert"], 2, "The lecturer says, \"Next week, we'll look at how early engineers tried to control rivers.\""),
            ])),
        new("l-c1-3", "C1", new ComprehensionExercise(
            "Radio Essay: In Praise of Boredom",
            "When did you last do absolutely nothing? I don't mean scrolling through your phone while waiting for a bus. I mean genuinely sitting with no entertainment at all. For many of us, the honest answer is that we can't remember. We've become remarkably efficient at eliminating boredom, and I want to suggest tonight that this may come at a hidden cost. Boredom, after all, is uncomfortable for a reason. It's a signal that our current situation isn't satisfying, a nudge to go and find something more meaningful to do. When we instantly silence that signal with a screen, we never discover where it might have led. There's also intriguing evidence linking boredom to creativity. In one study, participants who first completed a deliberately tedious task, copying numbers out of a phone book, later came up with more imaginative ideas than those who hadn't. The theory is that a bored mind starts to wander, and a wandering mind is where unexpected connections are made. I'm not suggesting we should seek out misery. But perhaps, the next time you're standing in a queue, you might resist the urge to reach for your pocket, and simply see where your thoughts take you.",
            [
                new("What is the speaker's main message?", ["Phones should be banned in public places", "Boredom is usually a sign of illness", "Boredom can be useful, so we should not always avoid it", "Queues in modern cities are getting longer"], 2, "The speaker suggests that \"eliminating boredom\" \"may come at a hidden cost\"."),
                new("According to the speaker, what is boredom a signal of?", ["That our current situation is not satisfying", "That we need more sleep", "That we are hungry", "That we are working too hard"], 0, "The speaker says, \"It's a signal that our current situation isn't satisfying.\""),
                new("What task did participants in the study do first?", ["They read a long novel", "They played a video game", "They sat in silence for an hour", "They copied numbers out of a phone book"], 3, "The speaker describes \"a deliberately tedious task, copying numbers out of a phone book\"."),
                new("What does the speaker suggest doing in a queue?", ["Reading the news", "Resisting the phone and letting your thoughts wander", "Calling a friend", "Planning the rest of your day"], 1, "The speaker suggests you \"resist the urge to reach for your pocket, and simply see where your thoughts take you\"."),
            ])),
        new("l-c1-4", "C1", new ComprehensionExercise(
            "Radio Interview: The Chef Who Wastes Nothing",
            "Good evening, and welcome to Kitchen Table. My guest tonight runs a small restaurant with an unusual promise. Nothing that comes into her kitchen goes into the bin. Not the carrot tops, not the stale bread, not even the coffee grounds. Now, you might assume this is simply a clever marketing idea, but when I visited her last month, I was genuinely struck by how seriously she takes it. Vegetable peelings become stock. Yesterday's bread is turned into a crisp crumb for salads or a rather wonderful dessert. Fruit that's past its best ends up in jams and drinks, and whatever truly can't be eaten is composted for the farm that supplies her vegetables. She tells me the approach began out of necessity rather than principle. When she opened, money was so tight that she simply couldn't afford to throw anything away. Only later did she realise how much food restaurants typically waste, and how much flavour was hiding in the parts most cooks discard. Tonight she'll share some of her techniques, and she's also going to challenge us, the home cooks, to rethink what we consider rubbish. So if you've got a notebook handy, I'd suggest keeping it close.",
            [
                new("What is the presenter mainly doing?", ["Introducing a chef whose restaurant avoids wasting food", "Reviewing an expensive restaurant", "Explaining how to grow vegetables on a farm", "Warning listeners about unhealthy coffee"], 0, "The presenter says the guest's promise is that \"nothing that comes into her kitchen goes into the bin\"."),
                new("What happens to yesterday's bread?", ["It is thrown away", "It is given to the farm", "It becomes a crumb for salads or a dessert", "It is used to make stock"], 2, "The presenter says, \"Yesterday's bread is turned into a crisp crumb for salads or a rather wonderful dessert.\""),
                new("Why did the chef first start avoiding waste?", ["She wanted good publicity", "She could not afford to throw anything away", "A customer asked her to", "A cooking school taught her to"], 1, "The presenter says \"money was so tight that she simply couldn't afford to throw anything away\"."),
                new("What will the chef challenge listeners to do?", ["Open their own restaurants", "Stop eating bread", "Visit her farm", "Rethink what they consider rubbish"], 3, "The presenter says she will \"challenge us, the home cooks, to rethink what we consider rubbish\"."),
            ])),
        new("l-c1-5", "C1", new ComprehensionExercise(
            "Talk: Losing the Night Sky",
            "Thank you all for coming. I'd like to begin with a simple question. When did you last see the Milky Way? If you live in a city, the answer may well be never. Astronomers estimate that a large share of the world's population now lives under skies so brightened by artificial light that our own galaxy is effectively invisible. This is what we call light pollution, and unlike many environmental problems, it's remarkably easy to overlook, precisely because it's the absence of something. Yet its effects reach far beyond disappointed stargazers. Migrating birds, which navigate partly by the stars, can become disoriented by brightly lit buildings. Newly hatched sea turtles, which instinctively head towards the brightest horizon, may crawl inland towards streetlights instead of towards the sea. And in humans, bright light late at night can disrupt the body clock and interfere with sleep. The encouraging part is that, unlike most forms of pollution, this one can be reversed almost instantly. Shielding streetlights so they point downwards, choosing warmer colours and simply switching off lights that nobody needs can make a dramatic difference. Several towns have already been recognised for protecting their dark skies, and visitors now travel specifically to see them.",
            [
                new("What is the talk mainly about?", ["How to become an astronomer", "Why cities need more streetlights", "The migration routes of sea turtles", "The effects of light pollution and how to reduce it"], 3, "The speaker introduces \"what we call light pollution\", describes its effects and then its solutions."),
                new("Why, according to the speaker, is light pollution easy to overlook?", ["Because it only happens in summer", "Because it is the absence of something", "Because it only affects birds", "Because it is very rare"], 1, "The speaker says it is easy to overlook \"precisely because it's the absence of something\"."),
                new("What problem can newly hatched sea turtles face?", ["They cannot see the moon", "They hatch too early in the year", "They may crawl towards streetlights instead of the sea", "They are attacked by migrating birds"], 2, "The speaker says they \"may crawl inland towards streetlights instead of towards the sea\"."),
                new("Which solution does the speaker mention?", ["Shielding streetlights so they point downwards", "Building taller buildings", "Using brighter white lights", "Keeping all lights on through the night"], 0, "The speaker mentions \"shielding streetlights so they point downwards\" as a solution."),
            ])),
        new("l-c1-6", "C1", new ComprehensionExercise(
            "Lecture: The Hidden Life of Soil",
            "Good morning. Today I'd like you to look down rather than up, because the ground beneath your feet is one of the most crowded places on the planet. A single handful of healthy soil contains more living organisms than there are people on Earth. Most of them are bacteria and fungi, far too small to see. For a long time, we treated soil as little more than a place to anchor plants and store water. That view has changed dramatically. We now know that many fungi form partnerships with plant roots. The fungus spreads fine threads through the soil, reaching water and minerals the roots can't access, and in return the plant supplies it with sugars. It's a trade that has existed for hundreds of millions of years. The practical consequences are significant. Heavy ploughing and certain chemicals can break these networks apart, which may leave crops more dependent on fertiliser. So some farmers are now experimenting with disturbing the soil as little as possible. The results so far are promising, though, as ever, more long-term research is needed before we draw firm conclusions.",
            [
                new("What is the main focus of the lecture?", ["The complex living systems found in soil", "How to choose the right fertiliser", "The history of ploughing", "Why plants need sunlight"], 0, "The lecturer says \"the ground beneath your feet is one of the most crowded places on the planet\" and describes the organisms in it."),
                new("How was soil viewed for a long time?", ["As the most important source of food", "As something that should be ploughed daily", "As a dangerous source of disease", "Mainly as a place to anchor plants and store water"], 3, "The lecturer says, \"We treated soil as little more than a place to anchor plants and store water.\""),
                new("What do plants give fungi in return?", ["Water", "Minerals", "Sugars", "Shelter from bacteria"], 2, "The lecturer says, \"In return the plant supplies it with sugars.\""),
                new("How does the lecturer describe the results of disturbing soil less?", ["Completely proven", "Promising, but in need of more long-term research", "Disappointing so far", "Too expensive to measure"], 1, "The lecturer says, \"The results so far are promising, though, as ever, more long-term research is needed.\""),
            ])),
        new("l-c1-7", "C1", new ComprehensionExercise(
            "Radio Essay: Why We Keep Old Letters",
            "In the drawer of my desk there's a shoebox full of letters. Some are from my grandmother, written in careful, slanting handwriting. Others are from a school friend who moved abroad when we were twelve. I rarely read them, yet I've carried that box through four house moves. Why? I suspect it's because a letter is not simply information. An email tells you what someone said. A letter also tells you how they were when they said it. You can see where the pen pressed harder, where a word was crossed out, where a coffee cup left a faint ring. The object itself becomes a kind of witness. There's also the question of permanence. Our messages today are abundant but oddly fragile. They sit on servers we don't control, and a forgotten password can erase years of conversation. Paper, by contrast, simply waits. I'm not suggesting we abandon our phones and return to stamps. But perhaps, once or twice a year, it's worth writing to someone by hand. You're not just sending words. You're sending something they might keep for the rest of their lives.",
            [
                new("What is the central idea of the essay?", ["People should stop using phones and emails", "Old letters should be stored in museums", "Handwriting is becoming harder to read", "Handwritten letters carry a personal and lasting value that digital messages often lack"], 3, "The speaker says a letter is \"not simply information\" and that the reader might keep it \"for the rest of their lives\"."),
                new("What does the speaker say about how often they read the letters?", ["Every evening", "Only after moving house", "Rarely", "Once a year on a special date"], 2, "The speaker says, \"I rarely read them, yet I've carried that box through four house moves.\""),
                new("According to the speaker, what does a letter show that an email does not?", ["How the writer was when they wrote it", "The exact date it was written", "The writer's true opinions", "Who else read it"], 0, "The speaker says, \"A letter also tells you how they were when they said it.\""),
                new("Why does the speaker call digital messages fragile?", ["They are often written too quickly", "They can be lost, for example through a forgotten password", "They are easy to misunderstand", "They are read by too many people"], 1, "The speaker says, \"A forgotten password can erase years of conversation.\""),
            ])),
        new("l-c1-8", "C1", new ComprehensionExercise(
            "Talk: Streets Designed for People",
            "Thank you for having me. I'd like to begin with a simple question. Who is your street really for? In many cities over the last century, the honest answer has been cars. Roads were widened, pavements narrowed, and crossings were placed wherever they least disrupted traffic. The result is that walking, which is the most natural form of transport we have, often became unpleasant and even risky. Increasingly, though, planners are questioning that approach. Some of the most interesting changes are surprisingly modest. Widening a pavement by a metre, planting a row of trees or adding benches can transform how a street feels. People linger, local shops see more customers, and children can walk to school on their own. Of course, these changes are rarely uncontroversial. Business owners often fear that removing parking will drive customers away. Yet in many cases, studies have found the opposite, because people on foot tend to visit more often, even if they spend less each time. My argument isn't that cars should disappear. It's that a street should be designed around the people who use it, not merely those passing through it.",
            [
                new("What is the speaker's main argument?", ["Cars should be banned from city centres", "Streets should be designed around the people who use them", "Shops should move out of city centres", "Cities need more parking spaces"], 1, "The speaker says, \"A street should be designed around the people who use it, not merely those passing through it.\""),
                new("According to the speaker, who have streets mostly been designed for?", ["Children", "Shop owners", "Cyclists", "Cars"], 3, "The speaker says, \"In many cities over the last century, the honest answer has been cars.\""),
                new("What do business owners often fear?", ["That removing parking will drive customers away", "That trees will block their windows", "That benches will attract noise", "That rents will go up"], 0, "The speaker says, \"Business owners often fear that removing parking will drive customers away.\""),
                new("What have studies found about people on foot?", ["They spend more each time", "They rarely go into shops", "They tend to visit shops more often", "They prefer large shopping centres"], 2, "The speaker says \"people on foot tend to visit more often, even if they spend less each time\"."),
            ])),
        new("l-c1-9", "C1", new ComprehensionExercise(
            "Podcast: The Psychology of Queuing",
            "Welcome to Everyday Science. Today's topic is something we all do and almost nobody enjoys. Waiting in line. What's fascinating is that researchers have found that how long we wait often matters less than how the wait feels. Take unoccupied time. Minutes spent standing with nothing to do seem much longer than minutes spent doing something. That's partly why some buildings put mirrors next to lifts. People look at themselves, and complaints about slow lifts tend to fall. Uncertainty makes things worse, too. A wait of unknown length feels longer than a known one, which is why a simple sign saying, about ten minutes from here, can calm a crowd. But perhaps the most powerful factor is fairness. People will tolerate a surprisingly long wait if they believe everyone is being treated equally. What makes them furious is seeing someone push in, or noticing that the other line is moving faster. In fact, many banks and airports now use a single long line that feeds several desks. It isn't necessarily quicker, but it feels fairer, and that turns out to be what we care about most.",
            [
                new("What is the main idea of the episode?", ["Queues in banks are getting shorter", "Lifts should be made faster", "How a wait feels matters more than how long it actually is", "Airports need more staff"], 2, "The host says \"how long we wait often matters less than how the wait feels\"."),
                new("Why do some buildings put mirrors next to lifts?", ["People look at themselves and complain less about slow lifts", "To make the space look bigger", "To help security staff watch people", "To make the lifts actually move faster"], 0, "The host says, \"People look at themselves, and complaints about slow lifts tend to fall.\""),
                new("According to the host, what is perhaps the most powerful factor?", ["Comfort", "Uncertainty", "Boredom", "Fairness"], 3, "The host says, \"Perhaps the most powerful factor is fairness.\""),
                new("Why do banks and airports use a single line feeding several desks?", ["It is always much faster", "It feels fairer, even if it isn't necessarily quicker", "It needs fewer staff", "It takes up less space"], 1, "The host says, \"It isn't necessarily quicker, but it feels fairer.\""),
            ])),
        new("l-c1-10", "C1", new ComprehensionExercise(
            "Interview: A Translator on Words That Don't Travel",
            "People assume translation is about finding the matching word in another language. In my experience, that's the least of it. The real work is carrying over a feeling, a tone, sometimes even a joke, and those almost never have neat equivalents. I once spent an entire afternoon on a single greeting. In the original, an elderly character welcomes a guest with a long, warm formula that goes on for several lines. In English, that sounds absurdly formal, almost comic. But if I shortened it to a simple hello, the reader would lose any sense of this man's generosity. In the end I kept part of it and let the rest show through his actions in the next paragraph. That's typical. Readers never see the version I rejected, of course, but those invisible decisions are what the job really consists of. You're constantly making trade-offs, and you have to accept that something will be lost. What I find encouraging, though, is that something can also be gained. A good translation sometimes reveals meanings that readers of the original took for granted. Being forced to explain a culture to outsiders makes you see it more clearly yourself.",
            [
                new("What is the translator's main point?", ["Translation is mainly about carrying over feeling and tone, not matching words", "Some languages are impossible to translate", "Machines will soon replace human translators", "English is too formal for literature"], 0, "The translator says, \"The real work is carrying over a feeling, a tone, sometimes even a joke.\""),
                new("Why was the greeting difficult to translate?", ["It contained words that don't exist in English", "It was a joke the translator didn't understand", "In English it would sound absurdly formal", "The author asked for it to be removed"], 2, "The translator says, \"In English, that sounds absurdly formal, almost comic.\""),
                new("How did the translator finally solve the problem?", ["Translated every word exactly", "Kept part of it and showed the rest through the character's actions", "Replaced it with a simple hello", "Added a note at the bottom of the page"], 1, "The translator says, \"I kept part of it and let the rest show through his actions in the next paragraph.\""),
                new("What does the translator find encouraging?", ["Readers rarely notice what is lost", "Translators are now better paid", "Most jokes translate easily", "Translation can reveal meanings that were taken for granted"], 3, "The translator says, \"A good translation sometimes reveals meanings that readers of the original took for granted.\""),
            ])),
        new("l-c1-11", "C1", new ComprehensionExercise(
            "Lecture: Ice as an Archive of the Past",
            "Good afternoon. Today we're looking at one of the most remarkable records of our planet's history, and it's made of ice. In places like Antarctica and Greenland, snow has fallen for an immensely long time without ever melting. Each year's snow is buried under the next, and gradually it's compressed into solid ice. Crucially, as this happens, tiny bubbles of air become trapped inside. Those bubbles are, in effect, samples of the atmosphere as it was when the snow fell. By drilling deep into the ice and extracting long cylinders, known as cores, scientists can study conditions stretching back hundreds of thousands of years. The layers can reveal far more than the composition of the air. Ash may point to a distant volcanic eruption. Dust suggests periods when the climate was drier and windier. Even the chemistry of the ice itself provides clues about past temperatures. Of course, interpreting these signals is complex, and different cores must be compared carefully. But taken together, they give us an extraordinarily detailed picture of how the climate has changed, and that helps us understand how it might change in the future.",
            [
                new("What is the lecture mainly about?", ["Why the ice in Antarctica is melting", "How to drill safely in cold places", "The history of polar exploration", "How ice cores preserve a record of Earth's past climate"], 3, "The lecturer calls ice \"one of the most remarkable records of our planet's history\"."),
                new("Why are the trapped air bubbles so valuable?", ["They show how deep the ice is", "They are samples of the atmosphere from when the snow fell", "They contain ancient bacteria", "They make the ice easier to drill"], 1, "The lecturer says, \"Those bubbles are, in effect, samples of the atmosphere as it was when the snow fell.\""),
                new("What can dust in the ice suggest?", ["A distant volcanic eruption", "Very warm summers", "Periods when the climate was drier and windier", "Heavy snowfall"], 2, "The lecturer says, \"Dust suggests periods when the climate was drier and windier.\""),
                new("What does the lecturer say about interpreting the signals?", ["It is complex, and cores must be compared carefully", "It is simple and quick", "It can be done by computers alone", "It gives only very rough guesses"], 0, "The lecturer says, \"Interpreting these signals is complex, and different cores must be compared carefully.\""),
            ])),
    ];
}
